### ISSUE TITLE
[Bug]: Bodyguards spawn crash

### ISSUE THREAD

**Issue by WinCores** [Yimura/YimMenu#652] opened 2022-12-01 10:50 UTC
### Describe the bug

The game crashes when the NPC (bodyguard) spawns close to another player or when the NPC getting in the radius of the network. In an empty session and singleplayer game everything is fine. But another players still can see spawned peds after you getting crashed.

### Steps To Reproduce

1. Open >World tab>Ped spawn.
2. Select any ped, or clone yourself.
3. Spawn a bodyguard ped nearly to another player/drive with spawned ped to any another players.

### Expected Behavior

Spawn ped without crash in the near of other players

### Screenshots and/or Logs

>Old build [cout.log](https://github.com/YimMenu/YimMenu/files/10131560/cout.log)
>New un modified build [cout.log](https://github.com/YimMenu/YimMenu/files/10131643/cout.log)

### Store

Epic Games

### Build

- [X] I used YimMenu unmodified

**Comment by Yimura** [comment] 2022-12-01 10:51
Duplicate of #591

**Comment by Yimura** [comment] 2022-12-01 11:04
Let's keep it open for other people that might stumble across this, it lets us track this bug more easily. (I forgot this was even a crash for example)
Eventually we'll check why exactly equipping all weapons to a bodyguard causes a crash and how we may prevent this in the future.

**Comment by SkiddyToast** [comment] 2022-12-03 17:16
This crash is in the `CPedInventoryDataNode` serializer, It seems to be going out of bounds on the array of ammos in a ped's inventory, and trying to dereference the invalid data. Remember that the max amount of weapons is 105 and the max amount of ammos is 65.

**Comment by Yimura** [comment] 2023-02-05 12:00
Closing as this has been fixed.

**Closed as completed by Yimura** 2023-02-05 12:00 UTC
Labels: bug
