### ISSUE TITLE
[Bug]: Autodrive to Objective

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#3465] opened 2024-07-29 08:05 UTC
### Describe the bug

After pressing To Objective, when trying to autopilot, the vehicle stops every 15-20 seconds and the message "no waypoint found" appears. This happens during business battles or the delivery of all kinds of goods, etc.

### Steps To Reproduce

1. Start a business battle
2. Pick up the goods
3. Press Autopilot/To Objective
4. Wait for some time, 10-20 seconds
5. Vehicle stops
6. Sadness

### Expected Behavior

We must reach the yellow mark.

### Logs

Logs?

### Screenshots / Video

![image](https://github.com/user-attachments/assets/4ff6a99d-485e-4dc0-97ac-f24e519d7c84)

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment] 2024-07-29 13:51
Objective uses the following logic to make a deterministic result of which waypoint is the objective:

```
inline bool get_objective_location(Vector3& location)
{
	if (get_blip_location(location, (int)BlipIcons::Circle, (int)BlipColors::YellowMission))
		return true;
	if (get_blip_location(location, (int)BlipIcons::Circle, (int)BlipColors::YellowMission2))
		return true;
	if (get_blip_location(location, (int)BlipIcons::Circle, (int)BlipColors::Mission))
		return true;
	if (get_blip_location(location, (int)BlipIcons::RaceFinish, (int)BlipColors::None))
		return true;
	if (get_blip_location(location, (int)BlipIcons::Circle, (int)BlipColors::Green))
		return true;
	if (get_blip_location(location, (int)BlipIcons::Circle, (int)BlipColors::Blue))
		return true;
	if (get_blip_location(location, (int)BlipIcons::CrateDrop))
		return true;

	static const int blips[] = {1, 57, 128, 129, 130, 143, 144, 145, 146, 271, 286, 287, 288};
	for (const auto& blip : blips)
	{
		if (get_blip_location(location, blip, 5))
			return true;
	}

	return false;
}
```

I have absolutely no idea what those static values are, probably from whatever version this was made, and they are years out of date now. 

But the root logic seems to be based off the code from m0d-s0biet-v that I released in 2016.

```
for (rage::BlipEntry blip : g_pointers->m_blip_list->m_Blips) //Actual mission blips.
{
	if (blip.m_pBlip)
	{
		if ((blip.m_pBlip->m_color == BlipColors::Mission && blip.m_pBlip->m_icon == BlipIcons::Circle) ||
			(blip.m_pBlip->m_color == BlipColors::YellowMission && blip.m_pBlip->m_icon == BlipIcons::Circle) ||
			(blip.m_pBlip->m_color == BlipColors::YellowMission2 && (blip.m_pBlip->m_icon == BlipIcons::Circle || blip.m_pBlip->m_icon == BlipIcons::DollarSignCircled)) ||
			(/*blip.m_pBlip->m_color == BlipColors::None && */blip.m_pBlip->m_icon == BlipIcons::RaceFinish) ||
			(blip.m_pBlip->m_color == BlipColors::Green && blip.m_pBlip->m_icon == BlipIcons::Circle))
		{
			return blip.m_pBlip;
		}
	}
}
```

That should be succeeding, since the blip you have is a regular yellow mission blip on your HUD.

But I think what's happening is this:

```
bool interupted = (PAD::IS_CONTROL_PRESSED(0, (int)ControllerInputs::INPUT_VEH_MOVE_LEFT_ONLY) || PAD::IS_CONTROL_PRESSED(0, (int)ControllerInputs::INPUT_VEH_MOVE_RIGHT_ONLY) || PAD::IS_CONTROL_PRESSED(0, (int)ControllerInputs::INPUT_VEH_ACCELERATE) || PAD::IS_CONTROL_PRESSED(0, (int)ControllerInputs::INPUT_VEH_BRAKE) || PAD::IS_CONTROL_PRESSED(0, (int)ControllerInputs::INPUT_VEH_EXIT) || PAD::IS_CONTROL_PRESSED(0, (int)ControllerInputs::INPUT_VEH_HANDBRAKE));

if (current_destination == AutoDriveDestination::EMERGENCY_STOP || (to_waypoint && !does_waypoint_exist) || interupted)
{
	TASK::CLEAR_PRIMARY_VEHICLE_TASK(self::veh);
	TASK::CLEAR_PED_TASKS(self::ped);

	if (!interupted && started)
	{
		VEHICLE::SET_VEHICLE_FORWARD_SPEED(self::veh, 0);
	}

	current_destination = AutoDriveDestination::STOPPED;

	if (to_waypoint && !does_waypoint_exist)
	{
		g_notification_service.push_warning("AUTO_DRIVE"_T.data(), "TELEPORT_NO_WAYPOINT_SET"_T.data());
	}
	else
	{
		g_notification_service.push_warning("AUTO_DRIVE"_T.data(), "BACKEND_LOOPED_VEHICLE_AUTO_DRIVE_STOPPED"_T.data());
	}

	started = false;
}
```

I think you might be inadvertently pressing one of these interrupted buttons, causing it check the waypoint again, causing it to fault out.

Anyway, since you have 2 brain cells to rub together and can inject your own developer build, would you mind debugging this yourself? I'd put LOG(INFO) calls inside of each block to see what is being called and why, using << variable will allow you to dump the value if needed.

**Comment by gir489returns** [comment] 2024-07-29 16:58
Rest in RIP muslim wultuh.

**Comment by xesdoog** [comment] 2024-07-29 17:47
YimMenu's objective TP gets confused when there are more than one objective blips on the map. If you try to teleport to multiple objectives using a hotkey, it will only succeed on one blip then it will stop working. This seems related to this issue and I know nothing about cpp so I'm not sure why it's is happening but I tried doing my own Objective TP in Lua and so far it works on multiple objectives. All it does is iterate over a table of mission blip IDs then if one or more are found, it calls `GET_CLOSEST_BLIP_INFO_ID()` and breaks the loop so every time you press a hotkey or a button you get the info and tp to the closest objective and ignore the rest until you call it again.

**Comment by gir489returns** [comment] 2024-07-29 19:01
> YimMenu's objective TP gets confused when there are more than one objective blips on the map. If you try to teleport to multiple objectives using a hotkey, it will only succeed on one blip then it will stop working. This seems related to this issue and I know nothing about cpp so I'm not sure why it's is happening but I tried doing my own Objective TP in Lua and so far it works on multiple objectives. All it does is iterate over a table of mission blip IDs then if one or more are found, it calls `GET_CLOSEST_BLIP_INFO_ID()` and breaks the loop so every time you press a hotkey or a button you get the info and tp to the closest objective and ignore the rest until you call it again.

This seems to just be a product of multiple scripts running at once. Each script keeps track of its own mission blips with locals, and then when it's ready to terminate, it runs a while loop on the local of each blip it's made and deletes it, then calls terminate script.

The logic YimMenu uses to determine the blip is

```
inline bool get_blip_location(Vector3& location, int sprite, int color = -1)
{
	Blip blip;
	for (blip = HUD::GET_FIRST_BLIP_INFO_ID(sprite); HUD::DOES_BLIP_EXIST(blip) && color != -1 && HUD::GET_BLIP_COLOUR(blip) != color; blip = HUD::GET_NEXT_BLIP_INFO_ID(sprite))
		;

	if (!HUD::DOES_BLIP_EXIST(blip) || (color != -1 && HUD::GET_BLIP_COLOUR(blip) != color))
		return false;

	location = HUD::GET_BLIP_COORDS(blip);

	return true;
}
```

You're using GET_CLOSEST_BLIP_INFO_ID, but it's just using GET_FIRST_BLIP_INFO_ID. A lot of the scripts use that native to find the mission blip, so it's probably correct. The faut you're describing probably comes from the logic here:

`if (get_blip_location(location, (int)BlipIcons::Circle, (int)BlipColors::YellowMission))`

It's strongly typing the icon and color together. How are you determining mission blips? Can I see your Lua script?

**Comment by xesdoog** [comment] 2024-07-29 19:59
@gir489returns I'm just storing mission blip IDs [in a table](https://github.com/xesdoog/Samurais-Scripts/blob/main/samurais_scripts.lua#L89) then [iterating over it](https://github.com/xesdoog/Samurais-Scripts/blob/main/samurais_scripts.lua#L3037) when F10 is pressed. I'm not checking for colors since each objective blip has it's own ID, for example yellow circle is 146. There are a few useless IDs in the script but so far I've tested this with yellow circle blips and labeled red circle blips (A, B, C...) they worked without issues in both teleporting myself as well as getting an NPC to drive me there.

**Comment by gir489returns** [comment] 2024-07-29 21:48
> I'm not checking for colors since each objective blip has it's own ID, for example yellow circle is 146. There are a few useless IDs in the script but so far I've tested this with yellow circle blips and labeled red circle blips (A, B, C...) they worked without issues in both teleporting myself as well as getting an NPC to drive me there.

I see, so you're doing basically the same thing we are. Like finding the enemies with the aimbot, there doesn't seem to be an agreed upon way the scripts mark mission blips on the HUD. I think the problem is that potentially our code can return two different blips that makes get_objective_location returning inconsistent, and instead we need to iteratively walk the blip list like I was doing before in BBv2. I remember this too being an issue, that's why I moved all of them into a giant for loop, as I wanted to return the least ID'd waypoint, not the first criteria'd waypoint.

**Closed as completed** 2024-07-30 20:11 UTC
Labels: bug
