### ISSUE TITLE
[Bug]: [FATAL/tunables_service.cpp:87] Failed to cache tunables

### ISSUE THREAD

**Issue by MadG3yZ** [Yimura/YimMenu#1457] opened 2023-06-18 15:17 UTC
### Describe the bug

pops up after trying to inject 
[FATAL/tunables_service.cpp:87] Failed to cache tunables

### Steps To Reproduce

start the game open xenos try to inject 

### Expected Behavior

wasnt expected

### Screenshots and/or Logs

[FATAL/tunables_service.cpp:87] Failed to cache tunables

### Store

Steam

### Additional context

[FATAL/tunables_service.cpp:87] Failed to cache tunables

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment] 2023-06-18 15:18
Duplicate of #1442

**Closed as completed by Yimura** 2023-06-18 15:18 UTC
Labels: bug
