### ISSUE TITLE
[Bug]: Crashing / Freezing and Error Messages when injecting.

### ISSUE THREAD

**Issue by Rabtos** [Yimura/YimMenu#2179] opened 2023-09-22 11:44 UTC
### Describe the bug

The Menu is crashing pretty often. Also I sometimes get some error messages when injecting. 
Sometimes the game "freezes" on me. I can move the camera, but not the player. can't press ESC etc. 

### Steps To Reproduce

1. Inject
2. Play, enter Garage or Buildings, start Missions.
3. Crash / Freeze

### Expected Behavior

Injecting without errors, freezes or crashes.

### Logs and/or screenshots

**1st**
Injected with error, game froze. I unloded and injected again and game crashed (with one .lua script):
[09-22-2023-13-35-35_cout.log](https://github.com/YimMenu/YimMenu/files/12700309/09-22-2023-13-35-35_cout.log)

**2nd**
Injected with Error, game works (still playing right now - no .lua script):
[cout.log](https://github.com/YimMenu/YimMenu/files/12700314/cout.log)
Edit: 17 minutes later it crashed after trying to enter a Drug Stash. Here is the (same) updated .log:
[cout.log](https://github.com/YimMenu/YimMenu/files/12700485/cout.log)

**3rd**
Edit2: After game restart, YimMenu injected without any errors.
Edit3: Did A Mission, but after finishing it, game crashed. Crash after finishing Mission happened like 20 times already to me.
[cout.log](https://github.com/YimMenu/YimMenu/files/12700648/cout.log)

### Store

Rockstar

### Additional context

PS: Love your Menu 

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by kevinsousa95** [comment] 2023-09-22 18:56
I was having this same problem, until I was banned, after the last gtav update, I don't use scripts, and after facing this problem for almost a week, I had my account suspended. I've already deleted the yimmenu folder and used different yim .dlls in the hope that this would stop. something that didn't happen. I'm looking forward to solving this problem, a friend of mine also had his account suspended and used yimmenu for the same amount of time as me.

**Comment by gir489returns** [comment] 2023-09-22 20:01
Duplicate of #2178 #2173 and #2170

**Closed as completed by gir489returns** 2023-09-22 20:01 UTC
Labels: bug
