### ISSUE TITLE
[Bug]: need help with proper injection on linuxx

### ISSUE THREAD

**Issue by hl2jeep** [Yimura/YimMenu#1649] opened 2023-07-08 19:14 UTC
### Describe the bug

I have previously opened an issue here regarding Linux injection and I have tried all of the methods with various results, none of which are helpful. First off, cheat engine injection works however many gui tabs are missing and it often crashes, in addition the game sometimes has this weird thing where the actual game won't launch with cheat engine added as a custom command until you launch it without the custom command. ThirteenAG's asi loader didn't work either. GTA does not launch if you replace bink2w64.dll with the loader. GH injector I think had an issue too but I can't exactly remember and need to retest it. 

### Steps To Reproduce

1. Install steamtinkerlaunch.
2. Add an injector to the custom command and set it to fork in the background.
3. Launch the game
4. Sometimes the game will crash here or it will start.
5. Try to inject and either get a crash or an improperly working menu.

### Expected Behavior

Yimmenu working correctly and the game not crashing every 2 mins.

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Additional context

Just for the record I'm using a docked steam deck for all of this so there may be some steamOS only quirks I'm not aware of. I have another laptop I can test other Linux flavours on if it's a steamOS only issue.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by gir489returns** [comment] 2023-07-08 19:32
Why don't you abuse the WINEDLLOVERRIDES parameter from WINE? That should basically emulate LoadLibraryA in the environment.

**Comment by hl2jeep** [comment] 2023-07-08 20:24
> Why don't you abuse the WINEDLLOVERRIDES parameter from WINE? That should basically emulate LoadLibraryA in the environment.


I'm going to be honest I don't really know how to exactly do that, how will I get the game to actually load that DLL, and most of the game dlls are litterally required or the game will crash, I would need to find a dll that the game uses but is also redundant.
EDIT: if you mean using a command line parameter then I would need an example of how to achieve this because I only know of dll overrides in the configuration window.

**Comment by tupoy-ya** [comment] 2023-07-08 20:43
> EDIT: if you mean using a command line parameter then I would need an example of how to achieve this because I only know of dll overrides in the configuration window.

The window and the env var do the same thing.

In case of the asi loader what version are you using?
I can't seem to be able to find the exact one i'm using for some reason.

**Comment by hl2jeep** [comment] 2023-07-08 21:12
I used the version you linked in the issue I previously opened, you said to make the dll bink2w64.dll but this dll already exists and seems to be required by the game, also if there is a way to do this with dll overrides that could work too

**Comment by tupoy-ya** [comment] 2023-07-09 05:02
> I used the version you linked in the issue I previously opened, you said to make the dll bink2w64.dll but this dll already exists and seems to be required by the game, also if there is a way to do this with dll overrides that could work too

You just rename the original to `bink2w64Hooked.dll` and then rename the asi loader to `bink2w64.dll`.

**Comment by hl2jeep** [comment] 2023-07-09 05:57
Ok I'll try it later when I'm at my pc

**Comment by tim-gromeyer** [comment] 2023-07-09 18:09
I tried it, it doesn't load. The Rockstar Games Launcher just redownloads the `bink2w64.dll`

**Comment by hl2jeep** [comment] 2023-07-09 20:54
This

> I tried it, it doesn't load. The Rockstar Games Launcher just redownloads the `bink2w64.dll`

This is because you are using the rockstar games version of the game, it automatically deleted files before launching the game, I strongly recommend getting the steam version when it's on sale as it doesn't do this.

**Comment by Yimura** [comment] 2023-07-09 21:07
There's also #334 , you can look there for more information on what to do to get YimMenu injected on Linux.

**Comment by tim-gromeyer** [comment] 2023-07-10 10:11
Thank you, I got it working

**Comment by Yimura** [comment] 2023-07-27 17:16
Duplicate of #334

**Closed as completed by Yimura** 2023-07-27 17:16 UTC
Labels: bug
