### ISSUE TITLE
spoof username[Request]: 

### ISSUE THREAD

**Issue by mortalblast** [Yimura/YimMenu#1045] opened 2023-03-04 19:08 UTC
### Problem

spoof username is not longer avaliable?

### Solution

add spoof username

### Reason

because it gives an extra layer of secutiry using the mod. Also allow us to join a session if someone is block joining our ID

**Comment by Yimura** [comment] 2023-03-04 19:11
Duplicate of #948 

Name spoofing is no longer possible since 1.66

**Closed as completed by Yimura** 2023-03-04 19:11 UTC
Labels: request
