### ISSUE TITLE
[Request]: Auto-refill Boost

### ISSUE THREAD

**Issue by NjuuOwO** [Yimura/YimMenu#2017] opened 2023-08-24 17:49 UTC
### Solution

Add a "Auto-refill Boost" button in Vehicle tab that, well, refills boost (in e.g. Vigilante) upon ending.

### Reason

it would be cool 😎

**Comment by gir489returns** [comment] 2023-08-24 18:12
This is a duplicate of #1913

**Closed as completed** 2023-08-24 18:41 UTC
Labels: request
