### ISSUE TITLE
[Request]: change player model to default

### ISSUE THREAD

**Issue by StyleCanadian** [Yimura/YimMenu#3467] opened 2024-07-29 09:45 UTC
### Problem

When I change my character model , I can't change it back to normal, and I'll have to rejoin the session for my character to return to normal.
![Screenshot 2024-07-29 130936](https://github.com/user-attachments/assets/251ce524-5e4b-4c78-b88c-b18c18c3b971)

### Solution

Adding a 'Reset to Default Player Model' button next to the 'Change Player Model' button would be great. By the way, thanks for your awesome work!

**Comment by gir489returns** [comment] 2024-07-29 13:41
This is a duplicate of #2002.

**Closed as completed by gir489returns** 2024-07-29 13:41 UTC
Labels: request
