### ISSUE TITLE
[Bug]: Mouse pointer stuck

### ISSUE THREAD

**Issue by T1k4301** [Yimura/YimMenu#3265] opened 2024-06-18 20:44 UTC
### Describe the bug

When i try to use the menu my mouse pointer stays stuck in the middle of the screen

### Steps To Reproduce

1.open yimmenu
2. open gta
3. 3. try to select anything the mouse cursor wont work

### Expected Behavior

i expected the cursor to move freely

### Logs

i dont know wat to say here

### Store

Epic Games

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by lonelybud** [comment] 2024-06-18 20:54
duplicate of #2768. please check this issue

**Closed as completed** 2024-06-24 17:12 UTC
Labels: bug
