### ISSUE TITLE
[Bug]: Failed to find "PD"

### ISSUE THREAD

**Issue by With3skull** [Yimura/YimMenu#1361] opened 2023-05-16 17:40 UTC
### Describe the bug

I become this error while i try to injekt the menu. its injekting then the console opends

 Failed to find 'PD'.

After that the game close himself

### Steps To Reproduce

1. open gta
2. injekt the menu
3. done

### Expected Behavior

A normal injektion

### Screenshots and/or Logs

```
<paste your logs here>
```
[15:29:08.8134620][INFO/main.cpp:64] Yim's Menu Initializing
[15:29:08.8135060][INFO/main.cpp:65] Git Info
    Branch:    master
    Hash:    eede8978d7f3fe408cff6f937377c6eff5c51a1f-dirty
    Date:    Sun Apr 30 17:03:37 2023
[15:29:08.9225702][INFO/main.cpp:68] Translation Service initialized.
[15:29:08.9226287][INFO/main.cpp:71] Thread pool initialized.
[15:29:08.9228083][DEBUG/thread_pool.cpp:22] Allocating 12 threads in thread pool.
[15:29:08.9246960][INFO/main.cpp:74] Settings Loaded.
[15:29:08.9246960][DEBUG/thread_pool.cpp:87] Thread 8636 executing globals.cpp:18
[15:29:08.9249112][INFO/pointers.hpp:92] GTA5 pointers cache is up to date, using it.
[15:29:08.9249202][INFO/pointers.cpp:1432] Loading pointers instance from cache
[15:29:08.9249217][INFO/pointers.cpp:1441] Pointers cache: Loading 164 fields from the cache
[15:29:08.9249299][DEBUG/module.cpp:50] Waiting for socialclub.dll...
[15:29:08.9264231][INFO/batch.hpp:106] Found 'SGPA' GTA5.exe+0x2C07A8
[15:29:09.0288650][WARN/batch.hpp:113] Failed to find 'PD'.

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment] 2023-05-16 17:49
Duplicate of #1357

**Closed as completed by Yimura** 2023-05-16 17:49 UTC
Labels: bug
