### ISSUE TITLE
ISSUES

### ISSUE THREAD

**Issue by HyperSABIT** [Yimura/YimMenu#1555] opened 2023-06-29 04:12 UTC
Im facing an issue when playing heist whenever I invite my friend in the same session my friends cant join my heist, their game freezes until I quit the mission. Then I start the mission from another session and invite them through R* Social Club they can join the game but when the heist starts the Entry vehicle is glitched or bugged if I use my starting vehicle as Alkonost the plane doesn't load. I float in the sky and cant jump also and when using LongFin the boat is glitched in the same way but when I get out of the boat and the boat's bug gets fixed and the boat spawns then when me and my friend come to the main land sometime my friend is teleported outside the map. Also in Diamond Casino Heist my friend gets teleported outside of the map and my character disappears and the main big problem is that I cant enter the casino. When I enter it the game loads infinitely

**Comment by Yimura** [comment] 2023-06-29 07:37
Duplicate of #1015

**Closed as completed by Yimura** 2023-06-29 07:37 UTC
