### ISSUE TITLE
[Bug]: Weapon Hotkeys is a bit messed up

### ISSUE THREAD

**Issue by rr1231234** [Yimura/YimMenu#1724] opened 2023-07-15 14:30 UTC
### Describe the bug

2 key, 3 key, 6 key wont work when set to a weapon, but:
when you press 8 key (isnt listed in menu) it will show the weapon is previously set to 3 key
when you press 9 key (isnt listed in menu) it will show the weapon is previously set to 2 key

also the 7 key isnt listed in the menu but it will still disable the native key

1 key, 4 key, 5 key works well as intended

### Steps To Reproduce

Above

### Expected Behavior

Above

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by gir489returns** [comment] 2023-07-15 14:33
This is a duplicate of #1690.

**Closed as completed** 2023-07-18 13:22 UTC
Labels: bug
