### ISSUE TITLE
[Bug]: Brush out the vehicle

### ISSUE THREAD

**Issue by 1719952486** [Yimura/YimMenu#1305] opened 2023-04-29 08:28 UTC
### Describe the bug

The supercar category that displays the vehicle does not include Ignus, but all of them contain Ignus. The same applies to personal vehicles

### Steps To Reproduce

Open the menu, select the vehicle, swipe out the vehicle, and select the supercar by category

### Expected Behavior

I hope it can be fixed. The previous version did not have this issue

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by epicmusicpt** [comment] 2023-04-29 11:03
there´s other cars missing too, the buffallo STX for example

**Comment by Yimura** [comment] 2023-04-29 11:14
Duplicate of #1302

**Closed as completed by Yimura** 2023-04-29 11:14 UTC
Labels: bug
