### ISSUE TITLE
[Bug]: Unloading YimMenu sometimes crashes the game, or isn't unloaded properly.

### ISSUE THREAD

**Issue by GTMoraes** [Yimura/YimMenu#1939] opened 2023-08-09 01:41 UTC
### Describe the bug

Sometimes, unloading YimMenu crashes the game. 

But other times, it just seemingly unloads, but the "prompt" is still open in the background, and I'm unable to re-inject YimMenu (it gives an error as if it was already injected)

### Steps To Reproduce

1. Click to unload YimMenu
2. It either crashes the game, or unloads, but you can still see it on the background, and you cannot re-inject it anymore.

### Expected Behavior

YimMenu unloads without crashing.
An alternative method to unload when it hangs on unloading

### Logs and/or screenshots

Nothing seemingly relevant in the logs when it hung on unload, just that... it hung.

```
[00:46:55.8946687][INFO/main.cpp:65] Yim's Menu Initializing
[00:46:55.8946898][INFO/main.cpp:66] Git Info
	Branch:	master
	Hash:	1f6d0e7d3a88de2900963cbd2c98519ded4fa8c2
	Date:	Mon Aug 7 14:00:09 2023
[00:46:55.8947031][DEBUG/thread_pool.cpp:21] Resizing thread pool from 0 to 4
[00:46:55.8953533][INFO/main.cpp:69] Thread pool initialized.
[00:46:55.8977726][INFO/main.cpp:72] Settings Loaded.
[00:46:55.8977752][DEBUG/thread_pool.cpp:95] Thread 28648 executing settings.cpp:18
[00:46:55.8981202][INFO/pointers.hpp:94] GTA5 pointers cache is up to date, using it.
[00:46:55.8981288][INFO/pointers.cpp:1548] Loading pointers instance from cache
[00:46:55.8981307][INFO/pointers.cpp:1557] Pointers cache: Loading 181 fields from the cache
[00:46:55.8981387][DEBUG/module.cpp:50] Waiting for socialclub.dll...
[00:46:55.8982650][INFO/pointers.hpp:94] Social Club pointers cache is up to date, using it.
[00:46:55.8982681][INFO/pointers.cpp:1548] Loading pointers instance from cache
[00:46:55.8982702][INFO/pointers.cpp:1557] Pointers cache: Loading 5 fields from the cache
[00:46:55.8983116][INFO/main.cpp:75] Pointers initialized.
[00:46:55.8984227][INFO/main.cpp:78] Byte Patch Manager initialized.

```

But when I inject YimMenu it throws this exception on the initial inject, it's sure that it's gonna crash when unloaded.
YimMenu works perfectly fine, otherwise. You just can't unload it.

```
[22:18:36.4837624][INFO/main.cpp:65] Yim's Menu Initializing
[22:18:36.4838866][INFO/main.cpp:66] Git Info
	Branch:	master
	Hash:	e87931bf605cf967ac5b9d490bfa0dcb3c1bb168
	Date:	Mon Aug 7 10:16:08 2023
[22:18:36.4839044][DEBUG/thread_pool.cpp:21] Resizing thread pool from 0 to 4
[22:18:36.4845880][INFO/main.cpp:69] Thread pool initialized.
[22:18:36.4871850][INFO/settings.cpp:79] Updating settings.
[22:18:36.4893979][INFO/main.cpp:72] Settings Loaded.
[22:18:36.4894029][DEBUG/thread_pool.cpp:95] Thread 19960 executing settings.cpp:18
[22:18:36.4897273][INFO/pointers.hpp:94] GTA5 pointers cache is up to date, using it.
[22:18:36.4897343][INFO/pointers.cpp:1548] Loading pointers instance from cache
[22:18:36.4897367][INFO/pointers.cpp:1557] Pointers cache: Loading 181 fields from the cache
[22:18:36.4897453][DEBUG/module.cpp:50] Waiting for socialclub.dll...
[22:18:36.4898837][INFO/pointers.hpp:94] Social Club pointers cache is up to date, using it.
[22:18:36.4898887][INFO/pointers.cpp:1548] Loading pointers instance from cache
[22:18:36.4898902][INFO/pointers.cpp:1557] Pointers cache: Loading 5 fields from the cache
[22:18:36.4899250][INFO/main.cpp:75] Pointers initialized.
[22:18:36.4900523][INFO/main.cpp:78] Byte Patch Manager initialized.
[22:18:36.4911052][FATAL/exception_handler.cpp:42] EXCEPTION_ACCESS_VIOLATION
Dumping modules:
GTA5.exe Base Address: 0x7FF67D330000 Size: 67158528
ntdll.dll Base Address: 0x7FFFF8110000 Size: 1245184
KERNEL32.DLL Base Address: 0x7FFFF7670000 Size: 524288
KERNELBASE.dll Base Address: 0x7FFFF58B0000 Size: 1634304
USER32.dll Base Address: 0x7FFFF7140000 Size: 593920
win32u.dll Base Address: 0x7FFFF57C0000 Size: 49152
GDI32.dll Base Address: 0x7FFFF6A10000 Size: 57344
gdi32full.dll Base Address: 0x7FFFF5600000 Size: 679936
msvcp_win.dll Base Address: 0x7FFFF5720000 Size: 335872
ucrtbase.dll Base Address: 0x7FFFF5C60000 Size: 798720
PSAPI.DLL Base Address: 0x7FFFF8050000 Size: 4096
WS2_32.dll Base Address: 0x7FFFF6F80000 Size: 290816
RPCRT4.dll Base Address: 0x7FFFF68F0000 Size: 880640
CRYPT32.dll Base Address: 0x7FFFF5D80000 Size: 1138688
WINTRUST.dll Base Address: 0x7FFFF5510000 Size: 307200
msvcrt.dll Base Address: 0x7FFFF6A50000 Size: 507904
VERSION.dll Base Address: 0x7FFFECE70000 Size: 12288
GFSDK_ShadowLib.win64.dll Base Address: 0x7FFF94930000 Size: 96256
IMM32.dll Base Address: 0x7FFFF8010000 Size: 126976
DSOUND.dll Base Address: 0x7FFF9B560000 Size: 491520
SHLWAPI.dll Base Address: 0x7FFFF8070000 Size: 212992
advapi32.dll Base Address: 0x7FFFF75C0000 Size: 425984
SHELL32.dll Base Address: 0x7FFFF5F70000 Size: 6524928
sechost.dll Base Address: 0x7FFFF7510000 Size: 446464
bink2w64.dll Base Address: 0x7FFFB0630000 Size: 307712
ole32.dll Base Address: 0x7FFFF7D20000 Size: 897024
combase.dll Base Address: 0x7FFFF7990000 Size: 2539520
OLEAUT32.dll Base Address: 0x7FFFF7000000 Size: 647168
WININET.dll Base Address: 0x7FFFDA340000 Size: 2113536
WINMM.dll Base Address: 0x7FFFEE470000 Size: 114688
MF.dll Base Address: 0x7FFFEF880000 Size: 368640
MFPlat.DLL Base Address: 0x7FFFEED00000 Size: 1503232
shcore.dll Base Address: 0x7FFFF6770000 Size: 679936
msdmo.dll Base Address: 0x7FFFE3750000 Size: 16384
PROPSYS.dll Base Address: 0x7FFFF1120000 Size: 688128
MFReadWrite.dll Base Address: 0x7FFF58C40000 Size: 995328
WTSAPI32.dll Base Address: 0x7FFFF08A0000 Size: 40960
d3d9.dll Base Address: 0x7FFFC8B50000 Size: 1306624
D3DCOMPILER_43.dll Base Address: 0x7FFF9F600000 Size: 2423296
GFSDK_TXAA_AlphaResolve.win64.dll Base Address: 0x7FFFE4C70000 Size: 48128
XINPUT1_3.dll Base Address: 0x400000 Size: 85504
bcrypt.dll Base Address: 0x7FFFF4EC0000 Size: 110592
DINPUT8.dll Base Address: 0x7FFFD48C0000 Size: 176128
IPHLPAPI.DLL Base Address: 0x7FFFF40B0000 Size: 122880
SETUPAPI.dll Base Address: 0x7FFFF6B00000 Size: 913408
ResampleDmo.DLL Base Address: 0x7FFF9B4A0000 Size: 503808
powrprof.dll Base Address: 0x7FFFF4410000 Size: 77824
d3dx9_43.dll Base Address: 0x7FFF9CDA0000 Size: 2280960
winmmbase.dll Base Address: 0x7FFFDB050000 Size: 102400
cfgmgr32.dll Base Address: 0x7FFFF5220000 Size: 221184
OPENGL32.dll Base Address: 0x7FFFD6CC0000 Size: 798720
dwmapi.dll Base Address: 0x7FFFF1E00000 Size: 90112
dxcore.dll Base Address: 0x7FFFF2300000 Size: 135168
GLU32.dll Base Address: 0x7FFFD4C80000 Size: 126976
MFCORE.DLL Base Address: 0x7FFF5BCF0000 Size: 3256320
UMPDC.dll Base Address: 0x7FFFF43F0000 Size: 36864
kernel.appcore.dll Base Address: 0x7FFFF4640000 Size: 36864
bcryptPrimitives.dll Base Address: 0x7FFFF5580000 Size: 376832
RTWorkQ.DLL Base Address: 0x7FFFEEC80000 Size: 102400
MSASN1.dll Base Address: 0x7FFFF51E0000 Size: 36864
gameoverlayrenderer64.dll Base Address: 0x7FFFB0860000 Size: 983552
inputhost.dll Base Address: 0x7FFFDC100000 Size: 1515520
CoreMessaging.dll Base Address: 0x7FFFF0CF0000 Size: 860160
CRYPTBASE.DLL Base Address: 0x7FFFF4D40000 Size: 12288
windows.storage.dll Base Address: 0x7FFFF34E0000 Size: 6909952
wintypes.dll Base Address: 0x7FFFF3020000 Size: 544768
dbghelp.dll Base Address: 0x7FFFF2DF0000 Size: 1626112
dbgcore.DLL Base Address: 0x7FFFE3980000 Size: 131072
d3d12.dll Base Address: 0x7FFFD6C70000 Size: 81920
CRYPTSP.dll Base Address: 0x7FFFF4D20000 Size: 57344
rsaenh.dll Base Address: 0x7FFFF45B0000 Size: 147456
uxtheme.dll Base Address: 0x7FFFF1C60000 Size: 425984
RTSSHooks64.dll Base Address: 0x180000000 Size: 677888
imagehlp.dll Base Address: 0x7FFFF7FF0000 Size: 49152
clbcatq.dll Base Address: 0x7FFFF72F0000 Size: 471040
dxdiagn.dll Base Address: 0x7FFFB9460000 Size: 253952
d3d11.dll Base Address: 0x7FFFF3160000 Size: 1867776
dxgi.dll Base Address: 0x7FFFF33C0000 Size: 647168
DEVOBJ.dll Base Address: 0x7FFFF51B0000 Size: 110592
WMICLNT.dll Base Address: 0x7FFFEE1D0000 Size: 32768
wbemprox.dll Base Address: 0x7FFFEB7D0000 Size: 28672
wbemcomn.dll Base Address: 0x7FFFEB5B0000 Size: 311296
wbemsvc.dll Base Address: 0x7FFFEA040000 Size: 8192
fastprox.dll Base Address: 0x7FFFE2C80000 Size: 708608
amsi.dll Base Address: 0x7FFFE9250000 Size: 57344
USERENV.dll Base Address: 0x7FFFF4BC0000 Size: 102400
profapi.dll Base Address: 0x7FFFF5440000 Size: 90112
symamsi.dll Base Address: 0x7FFFE8F10000 Size: 503296
gpapi.dll Base Address: 0x7FFFF4B50000 Size: 77824
cryptnet.dll Base Address: 0x7FFFECE30000 Size: 139264
WINNSI.DLL Base Address: 0x7FFFF1D80000 Size: 16384
NSI.dll Base Address: 0x7FFFF68E0000 Size: 8192
directxdatabasehelper.dll Base Address: 0x7FFFEDCE0000 Size: 192512
steam_api64.dll Base Address: 0x514D0000 Size: 110592
steamclient64.dll Base Address: 0x7FFF830E0000 Size: 16099328
tier0_s64.dll Base Address: 0x7FFFB06C0000 Size: 260608
vstdlib_s64.dll Base Address: 0x7FFFD5C20000 Size: 285184
MSWSOCK.dll Base Address: 0x7FFFF4AC0000 Size: 331776
Secur32.dll Base Address: 0x7FFFD9E10000 Size: 12288
SSPICLI.DLL Base Address: 0x7FFFF48A0000 Size: 126976
nvapi64.dll Base Address: 0x7FFFE92C0000 Size: 6282752
drvstore.dll Base Address: 0x7FFFECC60000 Size: 1073152
wldp.dll Base Address: 0x7FFFF4DD0000 Size: 176128
D3D10_1.DLL Base Address: 0x7FFFCFD70000 Size: 147456
d3d10_1core.dll Base Address: 0x7FFFEF390000 Size: 12288
nvspcap64.dll Base Address: 0x7FFFCD320000 Size: 2055680
ntmarta.dll Base Address: 0x7FFFF4660000 Size: 147456
dhcpcsvc.DLL Base Address: 0x7FFFEE3F0000 Size: 69632
MSCTF.dll Base Address: 0x7FFFF7EC0000 Size: 942080
textinputframework.dll Base Address: 0x7FFFE3470000 Size: 921600
CoreUIComponents.dll Base Address: 0x7FFFECED0000 Size: 2036736
WINSTA.dll Base Address: 0x7FFFF4030000 Size: 229376
nvldumdx.dll Base Address: 0x7FFFEA080000 Size: 591360
nvwgf2umx.dll Base Address: 0x7FFFDC880000 Size: 36389376
NvCamera64.dll Base Address: 0x7FFF8FBD0000 Size: 4209664
HID.DLL Base Address: 0x7FFFF3DE0000 Size: 24576
XINPUT9_1_0.dll Base Address: 0x7FFFEFA80000 Size: 8192
WindowsCodecs.dll Base Address: 0x7FFFEFF30000 Size: 1331200
MessageBus.dll Base Address: 0x7FFFE6890000 Size: 5349888
d3dcompiler_47_64.dll Base Address: 0x7FFF94520000 Size: 3922944
nvcuda64.dll Base Address: 0x7FFF915A0000 Size: 5770240
dcomp.dll Base Address: 0x7FFFF0140000 Size: 1716224
MMDevApi.dll Base Address: 0x7FFFEA5C0000 Size: 462848
XAudio2_7.dll Base Address: 0x7FFFB05A0000 Size: 485376
AUDIOSES.DLL Base Address: 0x7FFFE5790000 Size: 1409024
resourcepolicyclient.dll Base Address: 0x7FFFF2140000 Size: 36864
Windows.UI.dll Base Address: 0x7FFFC3B70000 Size: 966656
avrt.dll Base Address: 0x7FFFF34D0000 Size: 8192
MessageBus.dll Base Address: 0x7FFFD4DF0000 Size: 5349888
napinsp.dll Base Address: 0x7FFFD88B0000 Size: 53248
pnrpnsp.dll Base Address: 0x7FFFD75E0000 Size: 69632
DNSAPI.dll Base Address: 0x7FFFF4120000 Size: 716800
winrnr.dll Base Address: 0x7FFFD75C0000 Size: 32768
wshbth.dll Base Address: 0x7FFFECEB0000 Size: 45056
nlansp_c.dll Base Address: 0x7FFFD7590000 Size: 81920
fwpuclnt.dll Base Address: 0x7FFFED8A0000 Size: 299008
rasadhlp.dll Base Address: 0x7FFFEBF00000 Size: 8192
socialclub.dll Base Address: 0x7FFFA7BB0000 Size: 5094912
chrome_elf.dll Base Address: 0x7FFFC45B0000 Size: 685568
libcef.dll Base Address: 0x7FFF50460000 Size: 109755392
COMDLG32.dll Base Address: 0x7FFFF7410000 Size: 774144
UIAutomationCore.DLL Base Address: 0x7FFFAE9D0000 Size: 3063808
OLEACC.dll Base Address: 0x7FFFE7090000 Size: 274432
NETAPI32.dll Base Address: 0x7FFFDBB40000 Size: 49152
COMCTL32.dll Base Address: 0x7FFFE6FD0000 Size: 573440
DWrite.dll Base Address: 0x7FFFF2910000 Size: 1605632
WINSPOOL.DRV Base Address: 0x7FFFE7100000 Size: 376832
USP10.dll Base Address: 0x7FFF84790000 Size: 4096
dxva2.dll Base Address: 0x7FFFA0510000 Size: 102400
credui.dll Base Address: 0x7FFF85720000 Size: 65536
urlmon.dll Base Address: 0x7FFFE75F0000 Size: 1298432
WINHTTP.dll Base Address: 0x7FFFEE550000 Size: 987136
ncrypt.dll Base Address: 0x7FFFF4E90000 Size: 114688
CRYPTUI.dll Base Address: 0x7FFFD1120000 Size: 278528
wevtapi.dll Base Address: 0x7FFFF1A30000 Size: 278528
ESENT.dll Base Address: 0x7FFFDC4B0000 Size: 3145728
iertutil.dll Base Address: 0x7FFFE5440000 Size: 557056
srvcli.dll Base Address: 0x7FFFE2BD0000 Size: 61440
netutils.dll Base Address: 0x7FFFF40A0000 Size: 20480
WKSCLI.DLL Base Address: 0x7FFFEE020000 Size: 53248
SAMCLI.DLL Base Address: 0x7FFFF18F0000 Size: 61440
NTASN1.dll Base Address: 0x7FFFF4E50000 Size: 69632
FirewallAPI.dll Base Address: 0x7FFFF3F50000 Size: 380928
fwbase.dll Base Address: 0x7FFFF3F00000 Size: 196608
FWPolicyIOMgr.dll Base Address: 0x7FFFDB7C0000 Size: 241664
wdmaud.drv Base Address: 0x7FFFA1FC0000 Size: 200704
ksuser.dll Base Address: 0x7FFFAC520000 Size: 8192
msacm32.drv Base Address: 0x7FFFA20D0000 Size: 20480
MSACM32.dll Base Address: 0x7FFFA11D0000 Size: 77824
midimap.dll Base Address: 0x7FFFA20C0000 Size: 16384
ondemandconnroutehelper.dll Base Address: 0x7FFFB8C10000 Size: 45056
DiscordHook64.dll Base Address: 0x7FFFA44E0000 Size: 780288
D3DCompiler_47.dll Base Address: 0x7FFFEFB40000 Size: 3043328
d3dx11_42.dll Base Address: 0x7FFFC82D0000 Size: 248832
d3dcompiler_42.dll Base Address: 0x7FFF95170000 Size: 2477568
LINKINFO.dll Base Address: 0x7FFFC1D40000 Size: 20480
mfsrcsnk.dll Base Address: 0x7FFF94340000 Size: 1613824
CompPkgSup.DLL Base Address: 0x7FFFE6060000 Size: 167936
Windows.Media.dll Base Address: 0x7FFFBADE0000 Size: 5017600
mp3dmod.dll Base Address: 0x7FFFE43D0000 Size: 65536
Windows.ApplicationModel.dll Base Address: 0x7FFFD0160000 Size: 704512
AppXDeploymentClient.dll Base Address: 0x7FFFEE8C0000 Size: 815104
schannel.DLL Base Address: 0x7FFFF44B0000 Size: 561152
ncryptsslp.dll Base Address: 0x7FFFD9AB0000 Size: 86016
YimMenu Vanilla.dll Base Address: 0x7FFF8B460000 Size: 6143488
MSVCP140.dll Base Address: 0x7FFFD4830000 Size: 346112
VCRUNTIME140.dll Base Address: 0x7FFFD4CB0000 Size: 64512
VCRUNTIME140_1.dll Base Address: 0x7FFFD8A70000 Size: 14848
Dumping registers:
RAX: 0x34
RCX: 0x1E15A92BF80
RDX: 0x17
RBX: 0x1E05E5DE708
RSI: 0x1E1C9467FFF
RDI: 0x1E1C9A64D01
RSP: 0x603C1BF670
RBP: 0x603C1BF709
R8:  0x7FF6801D0510
R9:  0x1E1CA510000
R10: 0x2
R11: 0x1E05E5B7CE0
R12: 0x8
R13: 0x1E1CFB31D10
R14: 0x1E05E5DE6E0
R15: 0x1E05EC55148
Dumping stacktrace:
[0]	GTA5.exe+0x160A980 0x7FF67E93A980
[1]	GTA5.exe+0x160B4C7 0x7FF67E93B4C7
[2]	GTA5.exe+0xA52404 0x7FF67DD82404
[3]	GTA5.exe+0x160BBA9 0x7FF67E93BBA9
[4]	GTA5.exe+0xA46AFC 0x7FF67DD76AFC
[5]	GTA5.exe+0xA4A43C 0x7FF67DD7A43C
[6]	GTA5.exe+0x161A8E9 0x7FF67E94A8E9
[7]	GTA5.exe+0x161A8E9 0x7FF67E94A8E9
[8]	GTA5.exe+0x161A11B 0x7FF67E94A11B
[9]	GTA5.exe+0x2781C 0x7FF67D35781C
[10]	GTA5.exe+0x20E9B 0x7FF67D350E9B
[11]	GTA5.exe+0x1619D24 0x7FF67E949D24
[12]	GTA5.exe+0x1494 0x7FF67D331494
[13]	GTA5.exe+0x12F22C3 0x7FF67E6222C3
[14]	GTA5.exe+0x180CE38 0x7FF67EB3CE38
[15]	KERNEL32.DLL BaseThreadInitThunk
[16]	ntdll.dll RtlUserThreadStart
--------End of exception--------

[22:18:37.0265072][INFO/main.cpp:81] Renderer initialized.
[22:18:37.2765067][INFO/main.cpp:85] Fiber pool initialized.
[22:18:37.7021936][INFO/main.cpp:88] Translation Service initialized.
[22:18:37.7171011][INFO/main.cpp:91] Hooking initialized.
[22:18:37.7202382][DEBUG/gta_data_service.cpp:162] Loading data from cache.
[22:18:37.7202446][INFO/gta_data_service.cpp:174] Loading 1029 peds from cache.
[22:18:37.7205750][INFO/gta_data_service.cpp:192] Loading 815 vehicles from cache.
[22:18:37.7208421][INFO/gta_data_service.cpp:209] Loading 117 weapons from cache.
[22:18:37.7208477][INFO/gta_data_service.cpp:210] Loading 378 weapon components from cache.
[22:18:37.7208615][DEBUG/gta_data_service.cpp:168] Loaded all data from cache.
[22:18:37.7272458][INFO/tunables_service.cpp:21] Loading tunables from cache
[22:18:37.7272699][INFO/main.cpp:111] Registered service instances...
[22:18:37.7272721][DEBUG/thread_pool.cpp:95] Thread 2528 executing tunables_service.cpp:24
[22:18:37.7273924][INFO/main.cpp:132] Scripts registered.
[22:18:37.7996192][INFO/main.cpp:135] Hooking enabled.
[22:18:37.8004841][INFO/main.cpp:138] Dynamic native hooker initialized.
[22:18:37.8058753][INFO/lua_module.cpp:226] Loaded CasinoPacino.lua
[22:18:37.8059206][INFO/main.cpp:141] Lua manager initialized.
[22:18:37.8059363][DEBUG/thread_pool.cpp:95] Thread 2528 executing player_database_service.cpp:276
[22:18:38.0019107][INFO/backend.cpp:51] Starting script: Self
[22:18:38.0019242][INFO/backend.cpp:76] Starting script: Weapons
[22:18:38.0019316][INFO/backend.cpp:99] Starting script: Vehicles
[22:18:38.0019552][INFO/backend.cpp:115] Starting script: Miscellaneous
[22:18:38.0019599][INFO/backend.cpp:135] Starting script: Remote
[22:18:38.0019781][INFO/backend.cpp:150] Starting script: Ls customs
[22:18:38.0019803][INFO/backend.cpp:162] Starting script: Rainbow paint
[22:18:38.0019824][INFO/backend.cpp:174] Starting script: Disable Control Action
[22:18:38.0019849][INFO/backend.cpp:187] Starting script: World
[22:21:11.8951845][INFO/main.cpp:152] Scripts unregistered.
[22:21:11.8972653][INFO/main.cpp:155] Lua manager uninitialized.
[22:21:11.9481121][INFO/main.cpp:158] Hooking disabled.
[22:21:11.9481858][INFO/main.cpp:161] Dynamic native hooker uninitialized.
[22:21:11.9481939][DEBUG/thread_pool.cpp:108] Thread 2528 exiting...
[22:21:11.9481988][DEBUG/thread_pool.cpp:108] Thread 27776 exiting...
[22:21:11.9481977][DEBUG/thread_pool.cpp:108] Thread 32348 exiting...
[22:21:11.9699910][DEBUG/thread_pool.cpp:108] Thread 19960 exiting...
[22:21:11.9703412][INFO/main.cpp:169] Destroyed thread pool.
[22:21:11.9703574][INFO/main.cpp:172] Script Connection Service reset.
[22:21:11.9716808][INFO/main.cpp:174] Tunables Service reset.
[22:21:11.9716891][INFO/main.cpp:176] Hotkey Service reset.
[22:21:11.9716911][INFO/main.cpp:178] Matchmaking Service reset.
[22:21:11.9717846][INFO/main.cpp:180] Player Database Service reset.
[22:21:11.9717881][INFO/main.cpp:182] API Service reset.
[22:21:11.9720542][INFO/main.cpp:184] Script Patcher Service reset.
[22:21:11.9720682][INFO/main.cpp:186] Gui Service reset.
[22:21:11.9724192][INFO/main.cpp:188] GTA Data Service reset.
[22:21:11.9724265][INFO/main.cpp:190] Vehicle Service reset.
[22:21:11.9724280][INFO/main.cpp:192] Model Preview Service reset.
[22:21:11.9724297][INFO/main.cpp:194] Mobile Service reset.
[22:21:11.9724372][INFO/main.cpp:196] Player Service reset.
[22:21:11.9724387][INFO/main.cpp:198] Pickup Service reset.
[22:21:11.9724411][INFO/main.cpp:200] Custom Text Service reset.
[22:21:11.9724471][INFO/main.cpp:202] Context Service reset.
[22:21:11.9724489][INFO/main.cpp:204] Xml Vehicles Service reset.
[22:21:11.9724498][INFO/main.cpp:205] Services uninitialized.
[22:21:11.9724800][INFO/main.cpp:208] Hooking uninitialized.
[22:21:11.9724842][INFO/main.cpp:211] Fiber pool uninitialized.
[22:21:11.9926187][INFO/main.cpp:214] Renderer uninitialized.
[22:21:11.9927328][INFO/main.cpp:217] Byte Patch Manager uninitialized.
[22:21:11.9927371][INFO/main.cpp:220] Pointers uninitialized.
[22:21:11.9927413][INFO/main.cpp:223] Thread pool uninitialized.
[22:21:11.9927424][INFO/main.cpp:225] Farewell!
```

### Store

Steam

### Additional context

I've been unloading YimMenu a lot, to run missions. It works 7/10 times.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by TheGreenBandit** [comment] 2023-08-09 10:26
Have you tried closing out the log after it says unloaded manually, then try reinfecting?

**Comment by GTMoraes** [comment] 2023-08-09 15:01
> Have you tried closing out the log after it says unloaded manually, then try reinfecting?

You mean that secondary prompt-like window? I'm unable to close it by normal means. The "X" button is not enabled.
When it unloads gracefully, it automatically closes.

**Comment by gir489returns** [comment] 2023-08-10 02:20
Duplicate of #1741.

**Comment by Yimura** [comment] 2023-09-10 20:33
Duplicate of #1741

**Closed as completed by Yimura** 2023-09-10 20:33 UTC
Labels: bug
