### ISSUE TITLE
[Bug]: failed to find 'PD' error while injecting

### ISSUE THREAD

**Issue by zwia** [Yimura/YimMenu#2457] opened 2023-11-27 15:16 UTC
### Describe the bug

I looked at thread #1358 but I have no idea what it's about, it doesn't say anywhere how to fix this error

### Steps To Reproduce

.

### Expected Behavior

.

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment] 2023-11-27 15:54
Welp social club launcher updated.

**Comment by gir489returns** [comment] 2023-11-27 16:02
![image](https://github.com/YimMenu/YimMenu/assets/100792176/fbbff560-d6cd-4c40-b4b0-8b6ee5728610)

Cannot reproduce.

**Comment by CypherMorgan** [comment] 2023-11-28 03:30
Unable to reproduce as well.

**Comment by gir489returns** [comment] 2023-11-28 03:43
Closing as PEBCAK.

**Closed as completed by gir489returns** 2023-11-28 03:43 UTC
Labels: bug
