### ISSUE TITLE
[Bug]:Vehicle list empty. "No vehicles in registry".

### ISSUE THREAD

**Issue by matveyel** [Yimura/YimMenu#3196] opened 2024-05-28 17:59 UTC
### Describe the bug

There are no vehicles in the register. You can only spawn a personal or saved vehicle.

### Steps To Reproduce

1. Open Menu.
2. Vehicle - Spawn Vehicle

### Expected Behavior

Displaying vehicle categories. Displaying a list of vehicles.

### Logs

[cout.log](https://github.com/YimMenu/YimMenu/files/15473915/cout.log)

### Screenshots / Video

![2024-05-28_20-51-22](https://github.com/YimMenu/YimMenu/assets/171076961/e230b9c7-192d-4062-9436-45d584d5133d)

### Store

Epic Games

### Language

Russian

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment] 2024-05-28 18:52
This is a duplicate of #2107, #2639 and #2955

**Closed as completed by gir489returns** 2024-05-28 18:52 UTC
Labels: bug
