### ISSUE TITLE
[Request]: Spoof Username and R* ID

### ISSUE THREAD

**Issue by OfflinePing** [Yimura/YimMenu#1315] opened 2023-05-01 17:14 UTC
### Problem

Why cant you Spoof Username and R* ID anymore?

### Solution

Add it again?

### Reason

Because I dont understand why it was removed in first place xD

**Comment by Yimura** [comment] 2023-05-01 17:15
Duplicate of #1301

**Comment by Rxann** [comment] 2023-05-01 17:16
R* patched it I believe

**Closed as completed** 2023-05-01 17:15 UTC
Labels: request
