### ISSUE TITLE
[Bug]: Release-FastCompile Console Doesnt Log Anything After Init

### ISSUE THREAD

**Issue by USBMenus** [Yimura/YimMenu#2826] opened 2024-03-13 22:49 UTC
### Describe the bug

after injecting, it will log everything as normal when injected, but then wont log anything after its loaded, tried reloading a script and logging in lua and nothing showed, not even the protections

### Steps To Reproduce

inject yimmenu
try to get something to log in the console

### Expected Behavior

expect the console the work normally and properly log information

### Logs and/or screenshots

this is the console
```
[22:43:18.8830904][INFO/main.cpp:155] Settings Loaded.
[22:43:19.4933279][INFO/main.cpp:159] Yim's Menu Initializing
[22:43:19.4933665][INFO/main.cpp:160] Git Info
        Branch:
        Hash:
        Date:
[22:43:19.4941045][INFO/main.cpp:172] Windows 10 Home Version 22H2 (OS Build 19045.4046)
[22:43:19.4983581][DEBUG/thread_pool.cpp:22] Resizing thread pool from 0 to 4
[22:43:19.4990737][INFO/main.cpp:180] Thread pool initialized.
[22:43:19.5013907][INFO/pointers.hpp:94] GTA5 pointers cache is up to date, using it.
[22:43:19.5015991][INFO/pointers.cpp:1830] Loading pointers instance from cache
[22:43:19.5016098][INFO/pointers.cpp:1839] Pointers cache: Loading 217 fields from the cache
[22:43:19.5016295][DEBUG/module.cpp:50] Waiting for socialclub.dll...
[22:43:19.5021585][INFO/pointers.hpp:94] Social Club pointers cache is up to date, using it.
[22:43:19.5021634][INFO/pointers.cpp:1830] Loading pointers instance from cache
[22:43:19.5021659][INFO/pointers.cpp:1839] Pointers cache: Loading 5 fields from the cache
[22:43:19.5021992][INFO/main.cpp:183] Pointers initialized.
[22:43:19.5022046][INFO/main.cpp:190] Disabled anticheat gameskeleton.
[22:43:19.5023718][INFO/main.cpp:193] Byte Patch Manager initialized.
[22:43:19.5060965][INFO/main.cpp:196] Renderer initialized.
[22:43:19.5188529][INFO/main.cpp:200] Fiber pool initialized.
[22:43:19.5195658][INFO/main.cpp:203] HTTP Client initialized.
[22:43:19.9274715][DEBUG/thread_pool.cpp:96] Thread 19124 executing font_mgr.cpp:103
[22:43:19.9290373][INFO/main.cpp:206] Translation Service initialized.
[22:43:19.9943307][INFO/main.cpp:209] Hooking initialized.
[22:43:20.0033126][DEBUG/gta_data_service.cpp:160] Loading data from cache.
[22:43:20.0033302][INFO/gta_data_service.cpp:172] Loading 1051 peds from cache.
[22:43:20.0038637][INFO/gta_data_service.cpp:190] Loading 843 vehicles from cache.
[22:43:20.0041400][INFO/gta_data_service.cpp:207] Loading 119 weapons from cache.
[22:43:20.0041445][INFO/gta_data_service.cpp:208] Loading 380 weapon components from cache.
[22:43:20.0041641][DEBUG/gta_data_service.cpp:166] Loaded all data from cache.
[22:43:20.0323891][DEBUG/thread_pool.cpp:96] Thread 19124 executing player_database_service.cpp:285
[22:43:20.0329267][INFO/main.cpp:230] Registered service instances...
[22:43:20.0330737][INFO/main.cpp:251] Scripts registered.
[22:43:20.0919423][INFO/main.cpp:254] Hooking enabled.
[22:43:20.0944959][INFO/main.cpp:257] Dynamic native hooker initialized.
[22:43:20.1121275][INFO/lua_module.cpp:330] Loaded animdata.lua
[22:43:20.1270310][INFO/lua_module.cpp:330] Loaded CasinoPacino.lua
[22:43:20.1372045][INFO/lua_module.cpp:330] Loaded challenges.lua
[22:43:20.1505131][INFO/lua_module.cpp:330] Loaded Coords.lua
[22:43:20.1661718][INFO/lua_module.cpp:330] Loaded DailyCollectibles.lua
[22:43:20.1821634][INFO/lua_module.cpp:330] Loaded EventCoords.lua
[22:43:20.1917374][INFO/lua_module.cpp:330] Loaded EventInfo.lua
[22:43:20.2608779][INFO/lua_module.cpp:330] Loaded Extras-Addon.lua
[22:43:20.2723550][INFO/lua_module.cpp:330] Loaded gangsteraim.lua
[22:43:20.2835643][INFO/lua_module.cpp:330] Loaded god figner.lua
[22:43:20.2965596][INFO/lua_module.cpp:330] Loaded god finger.lua
[22:43:20.3083314][INFO/lua_module.cpp:330] Loaded InternetComputers.lua
[22:43:20.3196172][INFO/lua_module.cpp:330] Loaded json.lua
[22:43:20.3382746][INFO/lua_module.cpp:330] Loaded killenemies.lua
[22:43:20.3542158][INFO/lua_module.cpp:330] Loaded gtaenums.lua
[22:43:20.3678277][INFO/lua_module.cpp:330] Loaded gtaoffsets.lua
[22:43:20.3791980][INFO/lua_module.cpp:330] Loaded xmlreader.lua
[22:43:20.3892777][INFO/lua_module.cpp:330] Loaded race-editor.lua
[22:43:20.4027444][INFO/lua_module.cpp:330] Loaded RandomEvents.lua
[22:43:20.4129089][INFO/lua_module.cpp:330] Loaded recovery.lua
[22:43:20.4240841][INFO/lua_module.cpp:330] Loaded reports.lua
[22:43:20.4376878][INFO/lua_module.cpp:330] Loaded salvage_yard.lua
[22:43:20.4513083][INFO/lua_module.cpp:330] Loaded samurais_animations.lua
[22:43:20.4617727][INFO/lua_module.cpp:330] Loaded silent night.lua
[22:43:20.4730523][INFO/lua_module.cpp:330] Loaded tunables.lua
[22:43:20.4823783][INFO/lua_module.cpp:330] Loaded Util.lua
[22:43:20.4960237][INFO/lua_module.cpp:330] Loaded WasabiWords.lua
[22:43:20.4963245][INFO/main.cpp:261] Lua manager initialized.
```
this is my cout.log
```
[22:43:18.8830904][INFO/main.cpp:155] Settings Loaded.
[22:43:19.4933279][INFO/main.cpp:159] Yim's Menu Initializing
[22:43:19.4933665][INFO/main.cpp:160] Git Info
	Branch:	
	Hash:	
	Date:	
[22:43:19.4941045][INFO/main.cpp:172] Windows 10 Home Version 22H2 (OS Build 19045.4046)
[22:43:19.4983581][DEBUG/thread_pool.cpp:22] Resizing thread pool from 0 to 4
[22:43:19.4990737][INFO/main.cpp:180] Thread pool initialized.
[22:43:19.5013907][INFO/pointers.hpp:94] GTA5 pointers cache is up to date, using it.
[22:43:19.5015991][INFO/pointers.cpp:1830] Loading pointers instance from cache
[22:43:19.5016098][INFO/pointers.cpp:1839] Pointers cache: Loading 217 fields from the cache
[22:43:19.5016295][DEBUG/module.cpp:50] Waiting for socialclub.dll...
[22:43:19.5021585][INFO/pointers.hpp:94] Social Club pointers cache is up to date, using it.
[22:43:19.5021634][INFO/pointers.cpp:1830] Loading pointers instance from cache
[22:43:19.5021659][INFO/pointers.cpp:1839] Pointers cache: Loading 5 fields from the cache
[22:43:19.5021992][INFO/main.cpp:183] Pointers initialized.
[22:43:19.5022046][INFO/main.cpp:190] Disabled anticheat gameskeleton.
[22:43:19.5023718][INFO/main.cpp:193] Byte Patch Manager initialized.
[22:43:19.5060965][INFO/main.cpp:196] Renderer initialized.
[22:43:19.5188529][INFO/main.cpp:200] Fiber pool initialized.
[22:43:19.5195658][INFO/main.cpp:203] HTTP Client initialized.
[22:43:19.9274715][DEBUG/thread_pool.cpp:96] Thread 19124 executing font_mgr.cpp:103
[22:43:19.9290373][INFO/main.cpp:206] Translation Service initialized.
[22:43:19.9943307][INFO/main.cpp:209] Hooking initialized.
[22:43:20.0033126][DEBUG/gta_data_service.cpp:160] Loading data from cache.
[22:43:20.0033302][INFO/gta_data_service.cpp:172] Loading 1051 peds from cache.
[22:43:20.0038637][INFO/gta_data_service.cpp:190] Loading 843 vehicles from cache.
[22:43:20.0041400][INFO/gta_data_service.cpp:207] Loading 119 weapons from cache.
[22:43:20.0041445][INFO/gta_data_service.cpp:208] Loading 380 weapon components from cache.
[22:43:20.0041641][DEBUG/gta_data_service.cpp:166] Loaded all data from cache.
[22:43:20.0323891][DEBUG/thread_pool.cpp:96] Thread 19124 executing player_database_service.cpp:285
[22:43:20.0329267][INFO/main.cpp:230] Registered service instances...
[22:43:20.0330737][INFO/main.cpp:251] Scripts registered.
[22:43:20.0919423][INFO/main.cpp:254] Hooking enabled.
[22:43:20.0944959][INFO/main.cpp:257] Dynamic native hooker initialized.
[22:43:20.1121275][INFO/lua_module.cpp:330] Loaded animdata.lua
[22:43:20.1270310][INFO/lua_module.cpp:330] Loaded CasinoPacino.lua
[22:43:20.1372045][INFO/lua_module.cpp:330] Loaded challenges.lua
[22:43:20.1505131][INFO/lua_module.cpp:330] Loaded Coords.lua
[22:43:20.1661718][INFO/lua_module.cpp:330] Loaded DailyCollectibles.lua
[22:43:20.1821634][INFO/lua_module.cpp:330] Loaded EventCoords.lua
[22:43:20.1917374][INFO/lua_module.cpp:330] Loaded EventInfo.lua
[22:43:20.2608779][INFO/lua_module.cpp:330] Loaded Extras-Addon.lua
[22:43:20.2723550][INFO/lua_module.cpp:330] Loaded gangsteraim.lua
[22:43:20.2835643][INFO/lua_module.cpp:330] Loaded god figner.lua
[22:43:20.2965596][INFO/lua_module.cpp:330] Loaded god finger.lua
[22:43:20.3083314][INFO/lua_module.cpp:330] Loaded InternetComputers.lua
[22:43:20.3196172][INFO/lua_module.cpp:330] Loaded json.lua
[22:43:20.3382746][INFO/lua_module.cpp:330] Loaded killenemies.lua
[22:43:20.3542158][INFO/lua_module.cpp:330] Loaded gtaenums.lua
[22:43:20.3678277][INFO/lua_module.cpp:330] Loaded gtaoffsets.lua
[22:43:20.3791980][INFO/lua_module.cpp:330] Loaded xmlreader.lua
[22:43:20.3892777][INFO/lua_module.cpp:330] Loaded race-editor.lua
[22:43:20.4027444][INFO/lua_module.cpp:330] Loaded RandomEvents.lua
[22:43:20.4129089][INFO/lua_module.cpp:330] Loaded recovery.lua
[22:43:20.4240841][INFO/lua_module.cpp:330] Loaded reports.lua
[22:43:20.4376878][INFO/lua_module.cpp:330] Loaded salvage_yard.lua
[22:43:20.4513083][INFO/lua_module.cpp:330] Loaded samurais_animations.lua
[22:43:20.4617727][INFO/lua_module.cpp:330] Loaded silent night.lua
[22:43:20.4730523][INFO/lua_module.cpp:330] Loaded tunables.lua
[22:43:20.4823783][INFO/lua_module.cpp:330] Loaded Util.lua
[22:43:20.4960237][INFO/lua_module.cpp:330] Loaded WasabiWords.lua
[22:43:20.4963245][INFO/main.cpp:261] Lua manager initialized.
[22:43:20.5142388][INFO/backend.cpp:53] Starting script: Self
[22:43:20.5142921][INFO/backend.cpp:78] Starting script: Weapons
[22:43:20.5143068][INFO/backend.cpp:101] Starting script: Vehicles
[22:43:20.5143186][INFO/backend.cpp:117] Starting script: Miscellaneous
[22:43:20.5143585][INFO/backend.cpp:138] Starting script: Remote
[22:43:20.5143648][INFO/backend.cpp:153] Starting script: Ls customs
[22:43:20.5143705][INFO/backend.cpp:165] Starting script: Rainbow paint
[22:43:20.5143738][INFO/backend.cpp:177] Starting script: Disable Control Action
[22:43:20.5143805][INFO/backend.cpp:190] Starting script: World
[22:43:20.5305963][INFO/tunables_service.cpp:36] Loading tunables from cache
[22:43:24.7219683][FATAL/lua_module.cpp:80] ...rs\user\AppData\Roaming\YimMenu\scripts\killenemies.lua:144: attempt to index a nil value (global 'v3')
stack traceback:
	...rs\user\AppData\Roaming\YimMenu\scripts\killenemies.lua:144: in function 'base.get_random_offset_in_range'
	(...tail calls...)
	...rs\user\AppData\Roaming\YimMenu\scripts\killenemies.lua:205: in function <...rs\user\AppData\Roaming\YimMenu\scripts\killenemies.lua:197>
[22:43:24.7220144][FATAL/lua_manager.cpp:335] killenemies.lua: ...rs\user\AppData\Roaming\YimMenu\scripts\killenemies.lua:144: attempt to index a nil value (global 'v3')
stack traceback:
	...rs\user\AppData\Roaming\YimMenu\scripts\killenemies.lua:144: in function 'base.get_random_offset_in_range'
	(...tail calls...)
	...rs\user\AppData\Roaming\YimMenu\scripts\killenemies.lua:205: in function <...rs\user\AppData\Roaming\YimMenu\scripts\killenemies.lua:197>
[22:43:32.2207640][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: MM; DATA: "mmList":"4B45524E454C33322E444C4C00|4B45524E454C424153452E646C6C00|61707068656C702E646C6C00|5553455233322E646C6C00|47444933322E646C6C00|676469333266756C6C2E646C6C00|6D737663705F77696E2E646C6C00|75637274626173652E646C6C00|50534150492E444C4C00|5753325F3332
[22:43:32.2209430][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: MM; DATA: "mmList":"64336431305F31636F72652E646C6C00|4D534354462E646C6C00|74657874696E7075746672616D65776F726B2E646C6C00|57494E5354412E646C6C00|61746963667836342E646C6C00|61746975787036342E646C6C00|61746964787836342E646C6C00|616D6469686B36342E646C6C00|6478636F72652
[22:43:33.0123970][INFO/lua_module.cpp:330] Loaded killenemies.lua
[22:43:39.6570166][WARN/notify.hpp:67] Blocked rope crash from -DerangedPsycho- (145465155)
[22:43:39.6776333][WARN/notify.hpp:67] Blocked rope crash from -DerangedPsycho- (145465155)
[22:43:39.7154798][WARN/allocate_memory_reliable.cpp:35] Failed to allocate 80 bytes for reliable message, free space: 16. Trying to free some memory
[22:43:39.7155645][WARN/allocate_memory_reliable.cpp:35] Failed to allocate 80 bytes for reliable message, free space: 16. Trying to free some memory
[22:43:39.7156086][WARN/allocate_memory_reliable.cpp:45] Failed to allocate 80 bytes for reliable message, free space: 16. Failed to free some memory, clearing all messages (including reliables) for connection
[22:43:39.9088989][WARN/notify.hpp:67] Blocked rope crash from -DerangedPsycho- (145465155)
[22:43:39.9294071][WARN/notify.hpp:67] Blocked rope crash from -DerangedPsycho- (145465155)
[22:43:39.9549811][WARN/allocate_memory_reliable.cpp:35] Failed to allocate 80 bytes for reliable message, free space: 0. Trying to free some memory
[22:43:39.9550614][WARN/allocate_memory_reliable.cpp:35] Failed to allocate 9 bytes for reliable message, free space: 0. Trying to free some memory
[22:43:39.9550884][WARN/allocate_memory_reliable.cpp:45] Failed to allocate 9 bytes for reliable message, free space: 0. Failed to free some memory, clearing all messages (including reliables) for connection
[22:43:50.1895721][WARN/notify.hpp:67] Blocked rope crash from LodielSi (153237379)
[22:43:50.2331758][WARN/notify.hpp:67] Blocked rope crash from LodielSi (153237379)
[22:43:50.2504870][WARN/notify.hpp:67] Blocked rope crash from LodielSi (153237379)
[22:43:50.2747084][WARN/allocate_memory_reliable.cpp:35] Failed to allocate 80 bytes for reliable message, free space: 0. Trying to free some memory
[22:43:50.2747739][WARN/allocate_memory_reliable.cpp:45] Failed to allocate 80 bytes for reliable message, free space: 0. Failed to free some memory, clearing all messages (including reliables) for connection
[22:43:50.2841431][WARN/allocate_memory_reliable.cpp:35] Failed to allocate 80 bytes for reliable message, free space: 0. Trying to free some memory
[22:43:50.2844945][WARN/allocate_memory_reliable.cpp:35] Failed to allocate 80 bytes for reliable message, free space: 0. Trying to free some memory
[22:43:50.2845859][WARN/allocate_memory_reliable.cpp:45] Failed to allocate 80 bytes for reliable message, free space: 0. Failed to free some memory, clearing all messages (including reliables) for connection
[22:43:50.3544457][DEBUG/script_function.cpp:35] Found pattern SFSA in script freemode
[22:43:50.3830066][WARN/notify.hpp:67] Blocked rope crash from LodielSi (153237379)
[22:43:50.4065581][WARN/notify.hpp:67] Blocked rope crash from LodielSi (153237379)
[22:43:50.4253397][WARN/notify.hpp:67] Blocked rope crash from LodielSi (153237379)
[22:43:50.4757337][WARN/allocate_memory_reliable.cpp:35] Failed to allocate 9 bytes for reliable message, free space: 0. Trying to free some memory
[22:43:50.4757720][WARN/allocate_memory_reliable.cpp:35] Failed to allocate 9 bytes for reliable message, free space: 0. Trying to free some memory
[22:43:50.4757768][WARN/allocate_memory_reliable.cpp:45] Failed to allocate 9 bytes for reliable message, free space: 0. Failed to free some memory, clearing all messages (including reliables) for connection
[22:43:51.0304265][WARN/allocate_memory_reliable.cpp:35] Failed to allocate 80 bytes for reliable message, free space: 224. Trying to free some memory
[22:43:51.0305459][WARN/allocate_memory_reliable.cpp:35] Failed to allocate 80 bytes for reliable message, free space: 224. Trying to free some memory
[22:43:51.0305694][WARN/allocate_memory_reliable.cpp:45] Failed to allocate 80 bytes for reliable message, free space: 224. Failed to free some memory, clearing all messages (including reliables) for connection
[22:43:53.4975630][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: UVC; DATA: "vc":false
[22:43:53.4976063][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: RDEV; DATA: "g":"SC 145465155"
[22:43:53.4976245][INFO/prepare_metric_for_sending.cpp:111] METRIC: SES_JOIN; DATA: "id":-5107374171340200882,"mode":0,"pub":32,"priv":0,"tr":false,"ip":"172.59.169.66","rip":"192.81.245.128","usedr":true,"nat":2,"mtkey":231629701,"exe":49634800,"sku":"P-M-EU","sst":4272704625753784462,"tc":1710325229,"bc":4,"jt":2
[22:43:53.4977091][INFO/prepare_metric_for_sending.cpp:111] METRIC: MMF; DATA: "u":-3702426132517082275,"m":0,"c":2,"t":15,"h":false,"n":6,"q":[{"i":5515518817499146970,"q":1,"u":24,"m":32,"t":1,"r":14},{"i":-5107374171340200882,"q":4,"u":9,"m":32,"t":2,"r":0},{"i":-7575619156360565025,"q":1,"u":8,"m":32,"t":0,"r":0}]
[22:43:53.4977995][INFO/prepare_metric_for_sending.cpp:111] METRIC: PLAYED_WITH; DATA: "s":-5107374171340200882,"pr":0,"st":4272704625753784462,"prst":0,"fr":1,"pa":"SC 219924446|SC 245428294|SC 77491611|SC 170734782|SC 177199031|SC 153237379|SC 223754101|SC 112430526"
[22:43:53.4978266][INFO/prepare_metric_for_sending.cpp:111] METRIC: SHOWROOM_OVERVIEW; DATA: "a":390,"c":[-1089039904,1426219628,-1829802492],"e":[167522317,-122993285],"f":[903794909,838982985,2035069708,1123216662,-1205801634]
[22:43:53.4978563][INFO/prepare_metric_for_sending.cpp:111] METRIC: PLAYER_CHECK; DATA: "a":98,"b":0
[22:43:53.4978755][INFO/prepare_metric_for_sending.cpp:111] METRIC: SPAWN; DATA: "c":[-773.49,336.56,196.09],"d":-1209204521,"loc":19,"res":1
[22:43:55.3652009][INFO/prepare_metric_for_sending.cpp:111] METRIC: HEADER; DATA: "t":1710369818,"bt":1710369813,"seq":0,"ver":2,"game":{"ver":202833920,"cid":3,"sid":-5107374171340200882,"mp":1,"ptsid":14744317941192450498,"ed":4055609728,"platid":8,"gev":390,"st":2}
[22:43:55.3652680][INFO/prepare_metric_for_sending.cpp:111] METRIC: ENTER_SESSION_PACK; DATA: "a":0,"b":53218755,"c":325849,"d":53544604,"e":0,"f":80000.00000,"g":1,"h":0,"j":0,"k":0,"l":0,"m":0,"n":0,"o":0,"p":-1
[22:44:18.2870443][INFO/lua_module.cpp:330] Loaded killenemies.lua
[22:44:19.6913009][[22:44:19.6912615][FATAL/lua_manager.cpp:335] killenemies.lua: ...rs\user\AppData\Roaming\YimMenu\scripts\killenemies.lua:198: attempt to index a nil value (global 'info')
stack traceback:
	...rs\user\AppData\Roaming\YimMenu\scripts\killenemies.lua:198: in function <...rs\user\AppData\Roaming\YimMenu\scripts\killenemies.lua:197>
FATAL/lua_module.cpp:80] ...rs\user\AppData\Roaming\YimMenu\scripts\killenemies.lua:198: attempt to index a nil value (global 'info')
stack traceback:
	...rs\user\AppData\Roaming\YimMenu\scripts\killenemies.lua:198: in function <...rs\user\AppData\Roaming\YimMenu\scripts\killenemies.lua:197>
[22:44:31.6178718][DEBUG/script_event_handler.cpp:444] Script Event:
	Player: Cat0on0Crack
	Args: { -642704387, 1, 885, 1481401191, 0, 256, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 448792093, -1109936520, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -307075051, 5, 855, 0, 759, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
[22:44:48.3889286][INFO/queue_dependency.cpp:63] Blocking AC Verifier 318b98
[22:44:48.3914137][INFO/queue_dependency.cpp:63] Blocking AC Verifier 335458
[22:44:48.3914541][INFO/queue_dependency.cpp:63] Blocking AC Verifier 335430
[22:44:48.3915018][INFO/queue_dependency.cpp:63] Blocking AC Verifier 4012b8
[22:44:48.4026328][INFO/queue_dependency.cpp:63] Blocking AC Verifier 45acf4
[22:44:48.4028137][INFO/queue_dependency.cpp:63] Blocking AC Verifier 459f38
[22:44:48.4028244][INFO/queue_dependency.cpp:63] Blocking AC Verifier 5ca880
[22:44:48.4092644][INFO/queue_dependency.cpp:63] Blocking AC Verifier 9621f0
[22:44:48.4093653][INFO/queue_dependency.cpp:63] Blocking AC Verifier a668ec
[22:44:48.4116295][INFO/queue_dependency.cpp:63] Blocking AC Verifier 66f724
[22:44:48.4116694][INFO/queue_dependency.cpp:63] Blocking AC Verifier 66f74c
[22:44:48.4116995][INFO/queue_dependency.cpp:63] Blocking AC Verifier 66f774
[22:44:48.4117068][INFO/queue_dependency.cpp:63] Blocking AC Verifier 66f6fc
[22:45:13.9514817][INFO/prepare_metric_for_sending.cpp:111] METRIC: PLAYED_WITH; DATA: "s":-5107374171340200882,"pr":0,"st":4272704625753784462,"prst":0,"fr":1,"pa":"SC 219924446|SC 245428294|SC 77491611|SC 170734782|SC 177199031|SC 223754101|SC 112430526"
[22:45:13.9515537][INFO/prepare_metric_for_sending.cpp:111] METRIC: NAT_INFO; DATA: "S":true,"D":true,"NT":2,"NTC":2,"PMM":1,"FM":2,"PAS":3,"PI":0,"UPNP":3,"UTS":2,"UTT":60,"URM":0,"UMN":false,"UAP":false,"PCP":3,"PRM":0,"PAP":false,"UDF":"","UDM":"","UDD":"","UDN":"","ERR":0,"MTU":0,"DEV":1
[22:45:13.9515861][INFO/prepare_metric_for_sending.cpp:111] METRIC: PLAYED_WITH; DATA: "s":-5107374171340200882,"pr":0,"st":4272704625753784462,"prst":0,"fr":1,"pa":"SC 219924446|SC 245428294|SC 77491611|SC 170734782|SC 177199031|SC 223754101|SC 112430526"
[22:45:13.9516105][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: UVC; DATA: "vc":false
[22:45:13.9516176][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":1537565,"type":3136273443,"cat":654913086,"pt":144508413,"slot":0
[22:45:13.9516263][INFO/prepare_metric_for_sending.cpp:111] METRIC: PLAYER_STYLE; DATA: "a":1416452187,"b":-1303438434,"c":true,"d":-2046239230,"e":0,"f":0,"g":1612315541,"h":-1547610679,"i":338572559,"j":0,"k":0,"l":0,"m":0,"n":0,"o":0,"p":55376048,"q":0,"r":0,"s":0,"t":0
[22:45:13.9516619][INFO/prepare_metric_for_sending.cpp:111] METRIC: TRN; DATA: "i":1710369775,"t":1,"x":999,"y":1,"z":1,"a":true,"s":[{"s":1,"h":1029735578,"t":654,"x":1,"y":4,"i":10012,"j":10214},{"s":2,"h":72602837,"t":6287,"i":5633,"j":6287},{"s":2,"h":1399453868,"t":7421,"i":1134,"j":7421},{"s":2,"h":2779932672,"t":7432,"i":11
[22:45:13.9518551][INFO/prepare_metric_for_sending.cpp:111] METRIC: GENERIC; DATA: "type":"STREET_DEALER","d":27
[22:45:13.9518611][INFO/prepare_metric_for_sending.cpp:111] METRIC: GENERIC; DATA: "type":"STREET_DEALER","d":33
[22:45:13.9518662][INFO/prepare_metric_for_sending.cpp:111] METRIC: GENERIC; DATA: "type":"STREET_DEALER","d":16
[22:45:13.9518714][INFO/prepare_metric_for_sending.cpp:111] METRIC: GENERIC; DATA: "type":"WEEKLY OBJECTIVES","d":74
[22:45:13.9518812][INFO/prepare_metric_for_sending.cpp:111] METRIC: NPC_PHONE; DATA: "a":195,"b":1406998518,"c":1850234899,"d":489303882,"e":false,"f":98,"g":5,"h":4096,"i":0,"j":1024,"k":0,"l":1073741824,"m":268435456,"n":32
[22:48:32.2447303][INFO/prepare_metric_for_sending.cpp:111] METRIC: PLAYED_WITH; DATA: "s":-5107374171340200882,"pr":0,"st":4272704625753784462,"prst":0,"fr":1,"pa":"SC 219924446|SC 112085197|SC 245428294|SC 77491611|SC 170734782|SC 177199031|SC 223754101|SC 112430526"
[22:48:32.2447696][INFO/prepare_metric_for_sending.cpp:111] METRIC: INVITE_RESULT; DATA: "st":4813524545696981820,"mid":"","m":0,"flags":32808,"iid":1418956026,"ia":4,"if":0,"it":0,"inviter":"147454454","isfriend":false
[22:48:32.2447955][INFO/prepare_metric_for_sending.cpp:111] METRIC: PLAYED_WITH; DATA: "s":-5107374171340200882,"pr":0,"st":4272704625753784462,"prst":0,"fr":1,"pa":"SC 219924446|SC 245428294|SC 77491611|SC 170734782|SC 77224056|SC 177199031|SC 223754101|SC 112430526"
[22:48:32.2448218][INFO/prepare_metric_for_sending.cpp:111] METRIC: PLAYED_WITH; DATA: "s":-5107374171340200882,"pr":0,"st":4272704625753784462,"prst":0,"fr":1,"pa":"SC 219924446|SC 245428294|SC 77491611|SC 170734782|SC 77224056|SC 177199031|SC 223754101|SC 112430526"
[22:48:32.2448475][INFO/prepare_metric_for_sending.cpp:111] METRIC: PLAYED_WITH; DATA: "s":-5107374171340200882,"pr":0,"st":4272704625753784462,"prst":0,"fr":1,"pa":"SC 245428294|SC 170734782|SC 77491611|SC 112430526|SC 77224056|SC 219924446|SC 177199031|SC 238165646|SC 223754101|SC 202666441|SC 243077487"
[22:48:32.2448651][INFO/prepare_metric_for_sending.cpp:111] METRIC: P2P_DTLS_CXN; DATA: "S":true,"F":0,"V":0,"A":0,"E":0,"L":-1,"T":1342,"R":1,"B":true,"TR":4,"U":4272704625753784462,"NS":5,"NR":6,"LS":11,"LR":20,"LP":14744317941192393568,"RP":12927791597262175133,"LG":"SC 240471267","RG":"SC 113508119","LY":"192.81.245.128:61456","RY":"192.
[22:48:32.2449083][INFO/prepare_metric_for_sending.cpp:111] METRIC: PLAYED_WITH; DATA: "s":-5107374171340200882,"pr":0,"st":4272704625753784462,"prst":0,"fr":1,"pa":"SC 227009588|SC 245428294|SC 170734782|SC 77491611|SC 112430526|SC 113508119|SC 219924446|SC 166195775|SC 177199031|SC 238165646|SC 223754101|SC 202666441|SC 243077487"

```

### Store

Rockstar

### Language

English

### YimMenu Language

English (US)

### Additional context

i havent tested it in debug or release
but it does log it in the cout.log

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by GreySideMM** [comment] 2024-03-13 23:43
Duplicate of #2773.
Please check other issues first.

**Closed as completed** 2024-03-13 23:44 UTC
Labels: bug
