### ISSUE TITLE
[Bug]:Game freezes after Injection 

### ISSUE THREAD

**Issue by SamooBabo** [Yimura/YimMenu#1164] opened 2023-03-31 01:52 UTC
### Describe the bug

After i inject the YimMenu.dll, the game just freezes. First when I started it, it worked pretty well. It just froze for about 10 seconds. Now it just completely freezes and idk what to do. I restarted the game several times and it still keeps happening. i made sure to start the mod, when I was online.

### Steps To Reproduce

As I said the game just freezes after injection.

### Expected Behavior

to not freeze maybe?

### Screenshots and/or Logs

[01:41:58.4706047][INFO/main.cpp:60] Yim's Menu Initializing
[01:41:58.4706310][INFO/main.cpp:61] Git Info
        Branch: master
        Hash:   75afed1c8b694d6c7624b58dd17c1f1c5bf87125
        Date:   Wed Mar 29 22:37:31 2023
[01:41:58.6437865][INFO/main.cpp:64] Translation Service initialized.
[01:41:58.6438676][INFO/main.cpp:67] Thread pool initialized.
[01:41:58.6441288][DEBUG/thread_pool.cpp:22] Allocating 12 threads in thread pool.
[01:41:58.6453490][INFO/main.cpp:70] Settings Loaded.
[01:41:58.6461509][INFO/batch.cpp:27] Found 'ISA' GTA5.exe+0xEEC7
[01:41:58.6473341][INFO/batch.cpp:27] Found 'SCREEN_RESOLUTION' GTA5.exe+0x16A2FB
[01:41:58.6477009][INFO/batch.cpp:27] Found 'GS' GTA5.exe+0x2C0B3C
[01:41:58.6492298][INFO/batch.cpp:27] Found 'PF' GTA5.exe+0x72CC08
[01:41:58.6505366][INFO/batch.cpp:27] Found 'MWL' GTA5.exe+0x5D7CC7
[01:41:58.6508078][INFO/batch.cpp:27] Found 'NRF' GTA5.exe+0x1DC9A
[01:41:58.6509563][INFO/batch.cpp:27] Found 'FV' GTA5.exe+0x15F4468
[01:41:58.6536311][INFO/batch.cpp:27] Found 'S' GTA5.exe+0x1369579
[01:41:58.6568482][INFO/batch.cpp:27] Found 'ST' GTA5.exe+0x15F743F
[01:41:58.6577583][INFO/batch.cpp:27] Found 'NPM' GTA5.exe+0x1096780
[01:41:58.6580341][INFO/batch.cpp:27] Found 'CGSHM' GTA5.exe+0x15FBF09
[01:41:58.6583550][INFO/batch.cpp:27] Found 'SP' GTA5.exe+0xA42375
[01:41:58.6589710][INFO/batch.cpp:27] Found 'GTS' GTA5.exe+0x15F6F58
[01:41:58.6596537][INFO/batch.cpp:27] Found 'RBWD' GTA5.exe+0x668A79
[01:41:58.6599742][INFO/batch.cpp:27] Found 'TK' GTA5.exe+0xA464A0
[01:41:58.6622076][INFO/batch.cpp:27] Found 'TSE' GTA5.exe+0xD802BC
[01:41:58.6629044][INFO/batch.cpp:27] Found 'WBQ' GTA5.exe+0x130F1A8
[01:41:58.6629332][INFO/batch.cpp:27] Found 'WBD' GTA5.exe+0x14185E8
[01:41:58.6631582][INFO/batch.cpp:27] Found 'SG' GTA5.exe+0x15F6D90
[01:41:58.6635347][INFO/batch.cpp:27] Found 'NH' GTA5.exe+0x15F74E9
[01:41:58.6662416][INFO/batch.cpp:27] Found 'RBA' GTA5.exe+0x13073F8
[01:41:58.6662832][INFO/batch.cpp:27] Found 'RI' GTA5.exe+0x1FCC
[01:41:58.6669885][INFO/batch.cpp:27] Found 'RBB' GTA5.exe+0x1119340
[01:41:58.6678227][INFO/batch.cpp:27] Found 'WPGSDN' GTA5.exe+0x10EE248
[01:41:58.6725880][INFO/batch.cpp:27] Found 'WMSB' GTA5.exe+0xCED185
[01:41:58.6730060][INFO/batch.cpp:27] Found 'SEA' GTA5.exe+0x16B1CC9
[01:41:58.6747419][INFO/batch.cpp:27] Found 'RBS' GTA5.exe+0x119488C
[01:41:58.6750956][INFO/batch.cpp:27] Found 'WBI64' GTA5.exe+0x1197F91
[01:41:58.6758976][INFO/batch.cpp:27] Found 'BE' GTA5.exe+0xA6BE3C
[01:41:58.6774495][INFO/batch.cpp:27] Found 'PTH' GTA5.exe+0x15FB9C5
[01:41:58.6775613][INFO/batch.cpp:27] Found 'GSH' GTA5.exe+0x15FCE94
[01:41:58.6806930][INFO/batch.cpp:27] Found 'EP' GTA5.exe+0xA6BF3C
[01:41:58.6812925][INFO/batch.cpp:27] Found 'CNOM' GTA5.exe+0xB18968
[01:41:58.6816180][INFO/batch.cpp:27] Found 'NPMI' GTA5.exe+0x10F8C7B
[01:41:58.6824603][INFO/batch.cpp:27] Found 'GSCFWC' GTA5.exe+0xA414D0
[01:41:58.6854497][INFO/batch.cpp:27] Found 'GPR' GTA5.exe+0x11B2AE0
[01:41:58.6862908][INFO/batch.cpp:27] Found 'RC' GTA5.exe+0x13E721C
[01:41:58.6875462][INFO/batch.cpp:27] Found 'WBB' GTA5.exe+0x1196964
[01:41:58.6894288][INFO/batch.cpp:27] Found 'RNM' GTA5.exe+0x142E5CD
[01:41:58.6910142][INFO/batch.cpp:27] Found 'WBI32' GTA5.exe+0x1196E63
[01:41:58.6912558][INFO/batch.cpp:27] Found 'GNED' GTA5.exe+0x1A05A20
[01:41:58.6913546][INFO/batch.cpp:27] Found 'MHT' GTA5.exe+0xB202
[01:41:58.6922483][INFO/batch.cpp:27] Found 'API' GTA5.exe+0x16B4260
[01:41:58.6961197][INFO/batch.cpp:27] Found 'CAD' GTA5.exe+0x1103B02
[01:41:58.6961662][INFO/batch.cpp:27] Found 'NPMS' GTA5.exe+0x112D132
[01:41:58.6989878][INFO/batch.cpp:27] Found 'WPGDN' GTA5.exe+0x10EED64
[01:41:58.7007282][INFO/batch.cpp:27] Found 'GLT' GTA5.exe+0xDA0A63
[01:41:58.7011581][INFO/batch.cpp:27] Found 'RCS/GSTFT/GNOFP/GNO/GSTI' GTA5.exe+0x110421D
[01:41:58.7022362][INFO/batch.cpp:27] Found 'RCC' GTA5.exe+0x1103264
[01:41:58.7025893][INFO/batch.cpp:27] Found 'GGCC' GTA5.exe+0xA7616A
[01:41:58.7054633][INFO/batch.cpp:27] Found 'RBIST' GTA5.exe+0x11033E4
[01:41:58.7090889][INFO/batch.cpp:27] Found 'FDGD' GTA5.exe+0x12FACEB
[01:41:58.7091620][INFO/batch.cpp:27] Found 'FR' GTA5.exe+0xCD9014
[01:41:58.7092198][INFO/batch.cpp:27] Found 'GMI' GTA5.exe+0x164974A
[01:41:58.7107295][INFO/batch.cpp:27] Found 'FPFOA' GTA5.exe+0x12FC614
[01:41:58.7109752][INFO/batch.cpp:27] Found 'FPFC' GTA5.exe+0x12F765A
[01:41:58.7110284][INFO/batch.cpp:27] Found 'REH' GTA5.exe+0x16AE140
[01:41:58.7124800][INFO/batch.cpp:27] Found 'WBA' GTA5.exe+0x16987A2
[01:41:58.7125049][INFO/batch.cpp:27] Found 'MCF' GTA5.exe+0x1671F5A
[01:41:58.7126935][INFO/batch.cpp:27] Found 'SCP' GTA5.exe+0x2EF335
[01:41:58.7130950][INFO/batch.cpp:27] Found 'FPFUM' GTA5.exe+0x6A208F
[01:41:58.7138595][INFO/batch.cpp:27] Found 'GVOV' GTA5.exe+0x2E1F2C
[01:41:58.7147370][INFO/batch.cpp:27] Found 'IMCD' GTA5.exe+0x537975
[01:41:58.7153226][INFO/batch.cpp:27] Found 'SGSBGH' GTA5.exe+0x43CC5D
[01:41:58.7163199][INFO/batch.cpp:27] Found 'SCM' GTA5.exe+0x10A8481
[01:41:58.7172288][INFO/batch.cpp:27] Found 'FPFM' GTA5.exe+0x12FDB4E
[01:41:58.7192743][INFO/batch.cpp:27] Found 'SPIDN' GTA5.exe+0x110F7B0
[01:41:58.7205777][INFO/batch.cpp:27] Found 'N' GTA5.exe+0x10616C1
[01:41:58.7222593][INFO/batch.cpp:27] Found 'SVGDN' GTA5.exe+0x1116F38
[01:41:58.7224181][INFO/batch.cpp:27] Found 'SGSBGH' GTA5.exe+0x13F5096
[01:41:58.7231904][INFO/batch.cpp:27] Found 'JSBI' GTA5.exe+0x11717C4
[01:41:58.7252127][INFO/batch.cpp:27] Found 'HJR' GTA5.exe+0x117654C
[01:41:58.7276367][INFO/batch.cpp:27] Found 'FDS' GTA5.exe+0x12FD8D8
[01:41:58.7277532][INFO/batch.cpp:27] Found 'WJRD' GTA5.exe+0x6E60A5
[01:41:58.7279756][INFO/batch.cpp:27] Found 'GVGAS' GTA5.exe+0x10F11E4
[01:41:58.7288111][INFO/batch.cpp:27] Found 'VM' GTA5.exe+0x15F6D9A
[01:41:58.7345449][INFO/batch.cpp:27] Found 'HT' GTA5.exe+0x13E7E69
[01:41:58.7348209][INFO/batch.cpp:27] Found 'SPDM' GTA5.exe+0x111939C
[01:41:58.7360197][INFO/batch.cpp:27] Found 'QP' GTA5.exe+0x145297A
[01:41:58.7362023][INFO/batch.cpp:27] Found 'APTS' GTA5.exe+0x11E6B94
[01:41:58.7365162][INFO/batch.cpp:27] Found 'PMFR' GTA5.exe+0x13FF66C
[01:41:58.7376521][INFO/batch.cpp:27] Found 'GU' GTA5.exe+0x1413C06
[01:41:58.7393209][INFO/batch.cpp:27] Found 'IMSV' GTA5.exe+0x116FAC4
[01:41:58.7415418][INFO/batch.cpp:27] Found 'C' GTA5.exe+0xCDB040
[01:41:58.7421039][INFO/batch.cpp:27] Found 'RENC' GTA5.exe+0x145A8DE
[01:41:58.7429386][INFO/batch.cpp:27] Found 'SGS' GTA5.exe+0x118A508
[01:41:58.7443314][INFO/batch.cpp:27] Found 'SCNM' GTA5.exe+0x11E6F54
[01:41:58.7450042][INFO/batch.cpp:27] Found 'PIGI' GTA5.exe+0x10A249F
[01:41:58.7450249][INFO/batch.cpp:27] Found 'SND' GTA5.exe+0xF4C9F3
[01:41:58.7452811][INFO/batch.cpp:27] Found 'PGI' GTA5.exe+0x14044B8
[01:41:58.7457734][INFO/batch.cpp:27] Found 'GCP&SRGC' GTA5.exe+0x11E7DB1
[01:41:58.7471448][INFO/batch.cpp:27] Found 'STOPVT' GTA5.exe+0x699468
[01:41:58.7476050][INFO/batch.cpp:27] Found 'CW' GTA5.exe+0x16487F
[01:41:58.7477291][INFO/batch.cpp:27] Found 'CD' GTA5.exe+0x18CFDF
[01:41:58.7478651][INFO/batch.cpp:27] Found 'CSH' GTA5.exe+0xA337E0
[01:41:58.7483852][INFO/batch.cpp:27] Found 'SJRM' GTA5.exe+0x1273EC6
[01:41:58.7496444][INFO/batch.cpp:27] Found 'RC' GTA5.exe+0xF7CD40
[01:41:58.7508663][INFO/batch.cpp:27] Found 'IDC' GTA5.exe+0x67594C
[01:41:58.7510415][INFO/batch.cpp:27] Found 'RR' GTA5.exe+0xC0B6A7
[01:41:58.7511242][INFO/batch.cpp:27] Found 'BP' GTA5.exe+0x16BE3EE
[01:41:58.7518539][INFO/batch.cpp:27] Found 'SSMA' GTA5.exe+0x13F79C0
[01:41:58.7528294][INFO/batch.cpp:27] Found 'HRGC' GTA5.exe+0x11E0AE6
[01:41:58.7534979][INFO/batch.cpp:27] Found 'LCF' GTA5.exe+0x5D5EDC
[01:41:58.7567942][INFO/batch.cpp:27] Found 'SJD' GTA5.exe+0xA89CC0
[01:41:58.7578453][INFO/batch.cpp:27] Found 'MFO' GTA5.exe+0xA6EF53
[01:41:58.7579925][INFO/batch.cpp:27] Found 'SAACF' GTA5.exe+0xA8A11C
[01:41:58.7585956][INFO/batch.cpp:27] Found 'DPI' GTA5.exe+0x1433860
[01:41:58.7599740][INFO/batch.cpp:27] Found 'DSI' GTA5.exe+0x13F6B44
[01:41:58.7608005][INFO/batch.cpp:27] Found 'BNA' GTA5.exe+0x16BE204
[01:41:58.7624870][INFO/batch.cpp:27] Found 'ESI' GTA5.exe+0x10EEE86
[01:41:58.7657880][INFO/batch.cpp:27] Found 'PMFS' GTA5.exe+0x13E301C
[01:41:58.7673098][INFO/batch.cpp:27] Found 'SP' GTA5.exe+0x1450338
[01:41:58.7691805][INFO/batch.cpp:27] Found 'NT' GTA5.exe+0xCCB286
[01:41:58.7711587][INFO/batch.cpp:27] Found 'CTP' GTA5.exe+0x14426D0
[01:41:58.7716358][INFO/batch.cpp:27] Found 'CAC' GTA5.exe+0x1480C5C
[01:41:58.7726656][INFO/batch.cpp:27] Found 'TPO270' GTA5.exe+0xBB5CE6
[01:41:58.7732650][INFO/batch.cpp:27] Found 'SOD' GTA5.exe+0x128B247
[01:41:58.7733115][INFO/batch.cpp:27] Found 'ITC' GTA5.exe+0x29D13B
[01:41:58.7741050][INFO/batch.cpp:27] Found 'SCI' GTA5.exe+0x13D1EA7
[01:41:58.7743374][INFO/batch.cpp:27] Found 'ICF' GTA5.exe+0xA9ED6B
[01:41:58.7744538][INFO/batch.cpp:27] Found 'NTQVMC' GTA5.exe+0x151787D
[01:41:58.7761871][INFO/batch.cpp:27] Found 'GEAT' GTA5.exe+0xA88B7C
[01:41:58.7774181][INFO/batch.cpp:27] Found 'WPCDN' GTA5.exe+0x10E0BD8
[01:41:58.7781130][INFO/batch.cpp:27] Found 'RAU' GTA5.exe+0x16AF3E0
[01:41:58.7785269][INFO/batch.cpp:27] Found 'RPI' GTA5.exe+0x6B04A0
[01:41:58.7792662][INFO/batch.cpp:27] Found 'SPCS' GTA5.exe+0x119DFBC
[01:41:58.7793632][INFO/batch.cpp:27] Found 'SS' GTA5.exe+0x105DDA0
[01:41:58.7827920][INFO/batch.cpp:27] Found 'EAD' GTA5.exe+0x11E0E5C
[01:41:58.7842684][INFO/batch.cpp:27] Found 'WPADN' GTA5.exe+0x10ED968
[01:41:58.7843771][INFO/batch.cpp:27] Found 'SNT' GTA5.exe+0x145B0C1
[01:41:58.7864920][INFO/batch.cpp:27] Found 'WPCDN' GTA5.exe+0x10EDE18
[01:41:58.7872415][INFO/batch.cpp:27] Found 'RS' GTA5.exe+0x35F8773
[01:41:58.7900929][INFO/batch.cpp:27] Found 'FPC2' GTA5.exe+0x147D0D7
[01:41:58.7903112][INFO/batch.cpp:27] Found 'WVPMDN' GTA5.exe+0x10F43A0
[01:41:58.7904207][INFO/batch.cpp:27] Found 'FPCR' GTA5.exe+0x113E35D
[01:41:58.7907442][INFO/batch.cpp:27] Found 'MO' GTA5.exe+0x11B27DC
[01:41:58.7917696][INFO/batch.cpp:27] Found 'FPC' GTA5.exe+0x147CEA8
[01:41:58.7926804][INFO/batch.cpp:27] Found 'DSCC' GTA5.exe+0x11E1F75
[01:41:58.7931160][INFO/batch.cpp:27] Found 'CPTN' GTA5.exe+0xD52E24
[01:41:58.7934915][INFO/batch.cpp:27] Found 'QD' GTA5.exe+0x12E526C
[01:41:58.7938400][INFO/batch.cpp:27] Found 'TJC' GTA5.exe+0xAF13F0
[01:41:58.7997200][INFO/batch.cpp:27] Found 'DC' GTA5.exe+0x148CE6F
[01:41:58.8021154][INFO/batch.cpp:27] Found 'RAI' GTA5.exe+0x1263C1A
[01:41:58.8218379][INFO/batch.cpp:27] Found 'CT' GTA5.exe+0x12E3EB4
[01:41:58.8406509][INFO/batch.cpp:27] Found 'AWIV' GTA5.exe+0xEFD242
[01:41:58.8407532][DEBUG/module.cpp:45] Waiting for socialclub.dll...
[01:41:58.8413104][INFO/batch.cpp:27] Found 'PD' GTA5.exe+0xDAFC8
[01:41:58.8419084][INFO/batch.cpp:27] Found 'SGPA' GTA5.exe+0x2BCB0C
[01:41:59.0405185][INFO/main.cpp:73] Pointers initialized.
[01:41:59.5709897][INFO/main.cpp:76] Renderer initialized.
[01:41:59.8174822][INFO/main.cpp:80] Fiber pool initialized.
[01:41:59.8359553][INFO/main.cpp:83] Hooking initialized.
[01:41:59.8371047][DEBUG/gta_data_service.cpp:137] Loading data from cache.
[01:41:59.8371146][INFO/gta_data_service.cpp:149] Loading 336 peds from cache.
[01:41:59.8372683][INFO/gta_data_service.cpp:167] Loading 793 vehicles from cache.
[01:41:59.8375717][INFO/gta_data_service.cpp:185] Loading 116 weapons from cache.
[01:41:59.8376443][DEBUG/gta_data_service.cpp:143] Loaded all data from cache.
[01:41:59.8381585][INFO/main.cpp:101] Registered service instances...
[01:41:59.8382988][INFO/main.cpp:120] Scripts registered.
[01:41:59.8791387][INFO/main.cpp:123] Hooking enabled.
[01:41:59.8802355][INFO/main.cpp:126] Dynamic native hooker initialized.
[01:41:59.9585244][INFO/backend.cpp:39] Starting script: Self
[01:41:59.9585472][INFO/backend.cpp:53] Starting script: Weapons
[01:41:59.9585570][INFO/backend.cpp:72] Starting script: Vehicles
[01:41:59.9585886][INFO/backend.cpp:101] Starting script: Miscellaneous
[01:41:59.9585998][INFO/backend.cpp:119] Starting script: Remote
[01:41:59.9586067][INFO/backend.cpp:134] Starting script: Ls customs
[01:41:59.9586113][INFO/backend.cpp:146] Starting script: Rainbow paint
[01:41:59.9586137][INFO/backend.cpp:158] Starting script: Vehicle fly
[01:41:59.9586186][INFO/backend.cpp:89] Starting script: turnsignal
[01:41:59.9586342][INFO/backend.cpp:170] Starting script: Disable Control Action
[01:41:59.9586385][INFO/backend.cpp:183] Starting script: World

### Store

Epic Games

### Additional context

it just freezes, it doesnt crash. 

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by epicmusicpt** [comment] 2023-03-31 08:28
yeah its been arround for some time,personaly i cant play with any of the latest releases, it always freeze my game after 10/15min.
but fortunatly theres a fix but not implemented on the Menu yet,check this: https://github.com/YimMenu/YimMenu/issues/1073

**Comment by inthecatsdreams** [comment] 2023-03-31 09:59
https://github.com/YimMenu/YimMenu/issues/1073#issuecomment-1487812807 I released a temporary fix until they can pinpoint the real issue

**Comment by Yimura** [comment] 2023-04-01 13:50
Duplicate of #1073

**Closed as completed by Yimura** 2023-04-01 13:50 UTC
Labels: bug
