### ISSUE TITLE
Kick[Bug]: 

### ISSUE THREAD

**Issue by Ollule** [Yimura/YimMenu#2530] opened 2023-12-13 17:16 UTC
### Describe the bug

When you join a session it kick all poeple

### Steps To Reproduce

you start the mod menu and you kick all people(invalid player data Crash)

### Expected Behavior

.

### Logs and/or screenshots

```
<paste your logs here>
```
.

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment] 2023-12-13 17:25
Duplicate of #2525

**Closed as completed by Yimura** 2023-12-13 17:25 UTC
Labels: bug
