### ISSUE TITLE
[Bug]: Problem when people enter a mission

### ISSUE THREAD

**Issue by TWRak3** [Yimura/YimMenu#1312] opened 2023-05-01 11:22 UTC
### Describe the bug

I tried to start the preparation for a robbery, when I invite someone from the session it shows me "accepted", but after 1 minute it disappears and no one can enter anymore

### Steps To Reproduce

1. Join an online session
2. Start shot preparations
3. Invite people to the session
4. Wait for someone to accept the invitation

### Expected Behavior

The player who accepts the mission does not let him enter

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Rockstar

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by epicmusicpt** [comment] 2023-05-01 13:18
the same as https://github.com/YimMenu/YimMenu/issues/1015

**Comment by Yimura** [comment] 2023-05-01 22:07
Duplicate of #1015

**Closed as completed by Yimura** 2023-05-01 22:08 UTC
Labels: bug
