### ISSUE TITLE
[Improvement]: What does Player Magnet do?

### ISSUE THREAD

**Issue by NjuuOwO** [Yimura/YimMenu#2025] opened 2023-08-25 16:06 UTC
### Which feature

Add some sort of description on what Network->Misc->Player Magnet does

### Reason

Because there's no information of its purpose

**Comment by WorthIessPricetag** [comment] 2023-08-25 17:41
It will force new lobby searchers into your lobby till it hits the desired player number. 
Duplicate of #2023

**Comment by spinoza-spinoza** [comment] 2023-08-26 07:56
> It will force new lobby searchers into your lobby till it hits the desired player number. Duplicate of #2023

tank you 
i have  that notificaition    many  time  in every session    (blocked sound spam crash from  name player  )   is that mean that the player tryed to crash my game  ???

**Comment by Yimura** [comment] 2023-08-26 12:25
This should've been a discussion.

**Closed as completed by Yimura** 2023-08-26 12:25 UTC
Labels: improvement

**Comment by xiaoxiao921** [comment] 2023-08-26 12:43
@Yimura issue is reasonable for me, the name isnt clear and a description could be shown in the ui

**Comment by Yimura** [comment] 2023-08-26 12:44
Is there a way to pull people in your session though?

And I'm not talking about forcefully pulling people into your session but talking about the part where the matchmaking server favours your session over others.
