### ISSUE TITLE
[Bug]: Vehicle scrolling menu when spectate players

### ISSUE THREAD

**Issue by Alpaca-exe** [Yimura/YimMenu#1088] opened 2023-03-14 00:29 UTC
### Describe the bug

Many of the options, except for vehicle kick, are bugged. I have to click multiple times for theses to function or sometimes it won't work at all. I can also have the notification "failed to take control of player vehicle".

I don't know if it happens only to me so tell me if it's the case.

### Steps To Reproduce

1. Click on a player of the session
2. Go to vehicle scrolling menu
3. Use everything except vehicle kick

### Expected Behavior

To work for sure by clicking once

### Screenshots and/or Logs

![Error](https://user-images.githubusercontent.com/35534727/224861655-76ad6bb0-eef2-41e1-bbeb-ccaba09a91ce.jpg)

### Store

Rockstar

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment] 2023-03-14 10:43
Duplicate of #1067

**Closed as completed** 2023-03-14 10:44 UTC
Labels: bug
