### ISSUE TITLE
[Request]: hide your name in yim menu so that we can post images and videos with less efforts

### ISSUE THREAD

**Issue by lonelybud** [Yimura/YimMenu#2060] opened 2023-08-30 11:11 UTC
### Problem

when attaching videos and images we often have yimmenu displayed in video as well which also shows your username.

### Solution

add this [commit](https://github.com/lonelybud/YimMenu/commit/3cb715616a83fe65bb0997e24ed9e2278b2a9e6a) to solve the problem.

Attaching an image showing player name is hidden at three important places.

![image](https://github.com/YimMenu/YimMenu/assets/139460769/64a1e02d-e988-4248-8dc1-8225aba0c48c)

### Reason

One have to use video editor or image editor to hide name which is annoying while posting these assets.

**Comment by Yimura** [comment] 2023-08-30 11:12
Duplicate of #200

**Closed as completed by Yimura** 2023-08-30 11:12 UTC
Labels: request
