### ISSUE TITLE
ESP Bug

### ISSUE THREAD

**Issue by KekN3t** [Yimura/YimMenu#148] opened 2022-04-24 21:52 UTC
**Describe the bug**
I joined a new gta online lobby and enabled esp but it didnt showed up esp of the players, tried many things like changeing some settings

**To Reproduce**
1. Go to 'Session'
2. Click on Enable ESP
3. Scroll down to ENABLE
4. See that its not working

**Expected behavior**
- Esp wont show up

**Logs**

**Build**
Select which applies for you:
- [x] I used YimMenu unmodified
- [ ] I use my own version of YimMenu

**Additional context**

**Comment by Yimura** [comment] 2022-04-24 21:59
No need to open a new issue if the other one got closed, the other one can be reopened if needed.

Duplicate of #147

**Closed as completed** 2022-04-24 22:06 UTC
Labels: bug, duplicate
