### ISSUE TITLE
[Bug]: Imani Tech Vehicles Can Be Easily Destroyed

### ISSUE THREAD

**Issue by stoopidforfun** [Yimura/YimMenu#1695] opened 2023-07-12 13:24 UTC
### Describe the bug

When you spawn your PV via the menu like the Omnis e-GT or the Granger with "Spawn In" ticked the vehicle will take one hit from a rocket or missile to be destroyed

### Steps To Reproduce

1. Go to to Vehicle Tab
2. Click "Spawn Vehicle"
3. Switch to "Personal"
4. Select "Spawn In"
5. Pick a maxed-out Imani Tech Vehicle
6. Then fire an RPG or Homing Missile at the vehicle (or any explosive).

### Expected Behavior

Though the amount of health differs when the player is not in the Imani tech vehicle, but this is not the case, while sitting in the vehicle it explodes once it has been hit once by a rocket or any explosive and I am confident that these vehicles should be able to withstand a certain number of rockets or any explosive before they explode.

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by gir489returns** [comment] 2023-07-12 13:29
How is this a bug? What from the original game is different from how YM is behaving?

**Comment by BugisoftRSG** [comment] 2023-07-12 14:01
> How is this a bug? What from the original game is different from how YM is behaving?

His point is "Pick a maxed-out Imani Tech Vehicle"

Imani Tech Vehicles tanks more than a tank, iirc ~10 rockets

**Comment by gir489returns** [comment] 2023-07-12 14:07
> > How is this a bug? What from the original game is different from how YM is behaving?
> 
> His point is "Pick a maxed-out Imani Tech Vehicle"
> 
> Imani Tech Vehicles tanks more than a tank, iirc ~10 rockets

That doesn't answer my question. He chose his personal vehicle. All Yim does is call the mechanic to tell him to spawn the vehicle, and then it teleports it to you. So I say again. How does what Yim is doing differ from what the game is doing? If he chose to spawn a new one and this wasn't maxing it out, I would consider this a bug. This is not a bug.

**Comment by xiaoxiao921** [comment] 2023-07-12 14:12
Duplicate of #1192

**Comment by tupoy-ya** [comment] 2023-07-12 14:13
> That doesn't answer my question. He chose his personal vehicle. All Yim does is call the mechanic to tell him to spawn the vehicle, and then it teleports it to you. So I say again. How does what Yim is doing differ from what the game is doing? If he chose to spawn a new one and this wasn't maxing it out, I would consider this a bug. This is not a bug.

This is a bug.
YimMenu removes armor from vehicles that would otherwise have it.
It's a problem with vehicle godmode always setting `m_deform_god`* to 0x9C.
Why are we doing it by the way, can't we just to it `on_disable()` instead.

You could fix it by disabling the vehicle loop, but now vehicle godmode is a command so a normal user can't fix this.

**Closed as completed by xiaoxiao921** 2023-07-12 14:12 UTC
Labels: bug

**Comment by M1lken01** [comment] 2023-07-15 23:29
> This is a bug. YimMenu removes armor from vehicles that would otherwise have it. It's a problem with vehicle godmode always setting `m_deform_god`* to 0x9C. Why are we doing it by the way, can't we just to it `on_disable()` instead.

Yes and Imani tech vehicles and most planes have `m_deform_god` set to `0x1C` by default. But the vehicle godmode sets every vehicles `m_deform_god`  to `0x9C` while turned off.
