### ISSUE TITLE
[Bug]: YimMenu is blocking scripts required for restarting Doomsday 3

### ISSUE THREAD

**Issue by VolkerSchlegel** [Yimura/YimMenu#942] opened 2023-02-04 14:35 UTC
### Describe the bug

YimMenu blocks some script that is necessary for restarting doomsday after running out of lives, thus making you look like you left.
It even happens even with all protections turned off.

### Steps To Reproduce

1. Start the final mission of the third doomsday heist
2. Run out of lives

### Expected Behavior

YimMenu should not block scripts that are necessary for missions.

### Store

Epic Games

### Additional context

The guy I was playing with wasn't using any mod menu.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by TheGreenBandit** [comment] 2023-02-04 15:01
Duplicate of #926

**Closed as completed** 2023-02-04 15:16 UTC
Labels: bug
