### ISSUE TITLE
[Bug]: EXCEPTION_INT_DIVIDE_BY_ZERO

### ISSUE THREAD

**Issue by rrAsus** [Yimura/YimMenu#1169] opened 2023-04-01 13:23 UTC
### Describe the bug

This Happens when sometimes you just play i dont know what is causing this

### Steps To Reproduce

just play

### Expected Behavior

Not to generate it

### Screenshots and/or Logs

EXCEPTION_INT_DIVIDE_BY_ZERO
Dumping registers:
RAX: 0x871
RCX: 0x871
RDX: 0x0
RBX: 0x0
RSI: 0x0
RDI: 0x8F7156A3142A6BAD
RSP: 0xE7D0C8F340
RBP: 0x0
R8:  0x2
R9:  0xE7D0C8F2B8
R10: 0x13
R11: 0xE7D0C8F0F0
R12: 0x18B35
R13: 0x27561561732A7842
R14: 0x25FBA4DAB48
R15: 0x25FBA4DAB80
Dumping stacktrace:
[0]     YimMenu.dll+0x3654ED 0x7FFC650E54ED
[1]     YimMenu.dll+0x3BA643 0x7FFC6513A643
[2]     YimMenu.dll+0x3B66F5 0x7FFC651366F5
[3]     YimMenu.dll+0x1ADC0A 0x7FFC64F2DC0A
[4]     YimMenu.dll+0x1ADAF0 0x7FFC64F2DAF0
[5]     YimMenu.dll+0x24C0C0 0x7FFC64FCC0C0
[6]     YimMenu.dll+0x24C02C 0x7FFC64FCC02C
[7]     YimMenu.dll+0x24BE71 0x7FFC64FCBE71
[8]     KERNELBASE.dll PackageIdFromFullName
[9]     ntdll.dll RtlUserFiberStart
--------End of exception--------

### Store

Steam

### Additional context

Im using the temp fix

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment] 2023-04-01 13:27
Could you drop your settings.json also here just in case, I have a feeling we might need it.

You can find it here`%appdata%/BigBaseV2/settings.json`.

**Comment by rrAsus** [comment] 2023-04-01 13:35
[settings.txt](https://github.com/YimMenu/YimMenu/files/11129658/settings.txt)
i made it a txt so i could upload it

**Comment by Yimura** [comment] 2023-04-01 13:57
Which version of YimMenu was this exactly?

Could you paste the first 5 lines of your cout.log?

**Comment by rrAsus** [comment] 2023-04-01 14:01
[12:03:22.8383715][INFO/main.cpp:59] Yim's Menu Initializing
[12:03:22.8384064][INFO/main.cpp:60] Git Info
	Branch:	master
	Hash:	5144d6ce45242e11d16bebbcc80778ea0e9ae0ed
	Date:	Sun Mar 26 19:45:46 2023

**Comment by Yimura** [comment] 2023-04-01 14:02
Thanks a lot, I'll have a look.

**Comment by rrAsus** [comment] 2023-04-01 23:26
#1073 temporary fix is the im using

**Comment by Yimura** [comment] 2023-04-01 23:30
Yeah ok that makes sense cause I couldn't match any DLL to those stack dumps.

**Comment by Yimura** [comment] 2023-04-01 23:30
Possible duplicate of #1073

**Comment by rrAsus** [comment] 2023-04-01 23:46
Should i update or should i stay with it?

**Comment by Yimura** [comment] 2023-04-04 13:31
Could you try to reproduce this bug on the latest version of YimMenu?

**Comment by rrAsus** [comment] 2023-04-04 18:54
> Could you try to reproduce this bug on the latest version of YimMenu?

i don't think so

**Closed as completed** 2023-04-05 13:42 UTC
Labels: bug
