### ISSUE TITLE
[Bug]: Game Update broke YimMenu

### ISSUE THREAD

**Issue by Yimura** [Yimura/YimMenu#3138] opened 2024-05-16 17:02 UTC
### Describe the bug

[Forwarding bug report from UnknownCheats](https://www.unknowncheats.me/forum/4081763-post2806.html)

Failed to find `CTSHP`.
https://github.com/YimMenu/YimMenu/blob/00f5c34e2a1e2f60fabbfa9163c5b53c86696239/src/pointers.cpp#L1612-L1620

### Steps To Reproduce

1. Launch GTA
2. Inject current version of YimMenu
3. Crash on failed pattern

### Expected Behavior

Not crash.

### Logs

https://pastebin.com/raw/ijWmFUBA

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by lonelybud** [comment] 2024-05-16 17:16
there were updates related to rockstar launcher recently but no game update received so far. Not able to reproduce.

Edit: Purchased from epic games

**Comment by Yimura** [comment] 2024-05-16 17:31
I had an update in Steam and my launcher updated.

**Comment by gir489returns** [comment] 2024-05-16 17:33
> I had an update in Steam and my launcher updated.

I just played 10 minutes ago, it worked fine for me.

**Comment by gir489returns** [comment] 2024-05-16 17:33
![image](https://github.com/YimMenu/YimMenu/assets/100792176/4aea05f0-1c6c-4de9-87f9-f54b25670f6c)

Game is still on 3179.

**Comment by Rxann** [comment] 2024-05-16 17:33
> I had an update in Steam and my launcher updated.

I had the same update thing yesterday and YimMenu seemingly loaded fine. I will test when I get home. But, as it seems many cannot reproduce so I may not need to test.

**Comment by Yimura** [comment] 2024-05-16 18:17
Actually might be a false positive if they've loaded any other mods like menyoo which fucks with that particular signature (E.g. byte patches it).

**Comment by RiceBomber** [comment] 2024-05-16 21:22
Running into the same issue without other mod menus loaded. Epic Games version.
https://pastebin.com/raw/h18zUTK0

**Comment by xiaoxiao921** [comment] 2024-05-16 21:33
> Running into the same issue without other mod menus loaded. Epic Games version. https://pastebin.com/raw/h18zUTK0

That yimmenu.dll is from march 1, update to latest

**Comment by gir489returns** [comment] 2024-05-19 22:45
Closing as cannot reproduce.

**Closed as completed by gir489returns** 2024-05-19 22:45 UTC
Labels: bug, more info required
