### ISSUE TITLE
[Request]: Add where bodyguards can attack players...

### ISSUE THREAD

**Issue by Qi2nR9uw** [Yimura/YimMenu#2373] opened 2023-11-03 04:40 UTC
### Problem

Bodyguards will only attack NPCs that pose a threat to a player, and they won't attack players at all.

### Solution

Add a toggle switch that would let you spawn a NPC bodyguard that would attack a player is they harm you. It would be bonus if they would also be set to target specific entities such as all NPCs or all players too.

### Reason

It seems like a basic but needed feature that would continue making YimMenu the best :)

### [EDIT TO TRY AND CLEAR ANY CONFUSION:]

I am referring to the spawn a ped feature. There is currently a switch to spawn a ped as a "Bodyguard", but these peds will only attack other NPCs that pose a threat to any player in general, instead of attacking other players who attack you.

**But now that I've had time to think about it, an entire dedicated bodyguards section and options would be so much better and less confusing to explain.**

Option ideas for bodyguards could include:

- Formations (such as walking around the player or behind the player in a line)
- Who they attack (such as all NPCs or players who harm you)
- Bodyguards who drive vehicles and follow behind you?
- Stay in vehicle option (for if you exit the vehicle they will wait inside for you)

**Comment by pierrelasse** [comment] 2023-11-03 10:09
~I think you are talking about a script or so spawning a ped (npc) that is in your group and defends you when you get attacked.~
~Since there is no feature that lets you spawn bodyguards in yimmenu and the only way to do so is through a script, the feature you suggested should also be done in the script that spawns the bodyguards.~

~Long story short: Do it in the script that spawns the bodyguard/s.~

I think that first it should be checked if it's even possible to do using natives and then consider adding it to the menu.

**Comment by Yimura** [comment] 2023-12-08 08:22
Duplicate of #429

**Closed as completed by Yimura** 2023-12-08 08:22 UTC
Labels: request
