### ISSUE TITLE
[Request]: Co-Loading 

### ISSUE THREAD

**Issue by Akshansh16** [Yimura/YimMenu#3232] opened 2024-06-06 15:27 UTC
### Problem

YimMenu is not be able to Co-Load with the Stand Mod Menu. I want to Co-Load YimMenu after the Stand Menu is loaded in the game. But when I Co-Load it, it crashes the game everytime. 

### Solution

It is great to make a build to use YimMenu to be co-loaded after the Stand Menu.

### Reason

Because YimMenu has some more good time saving options. I know it was able to Co-Load it with the stand in privious privious builds. But it's not good now that the game is crashing.

### Additional context

Please look into this and make a Yim compatible to be co-loaded with other good menus. But be sure I want Yim second to be co-loaded.

Thanks a lot

**Comment by xiaoxiao921** [comment] 2024-06-06 15:30
Duplicate of https://github.com/YimMenu/YimMenu/issues/2341

**Closed as completed by xiaoxiao921** 2024-06-06 15:30 UTC
Labels: request
