### ISSUE TITLE
[Bug]: Missing vehicles in spawn menu

### ISSUE THREAD

**Issue by applegoos** [Yimura/YimMenu#1382] opened 2023-05-31 14:20 UTC
### Describe the bug

I might be being a bit of a goober but: as of a few weeks ago in the vehicle spawn menu, I am missing a lot of vehicles such as Thrax, Reever, Bus, Prison bus, and many more that I haven't noticed

### Steps To Reproduce

open vehicle spawn menu

### Expected Behavior

half the vehicles wont be there

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by tyackman** [comment] 2023-05-31 16:48
Try deleting the vehicle cache from the appdata/BigBaseV2 folder, also be sure you have the category "all" selected under the spawner menu.

**Comment by xiaoxiao921** [comment] 2023-05-31 17:20
Duplicate of https://github.com/YimMenu/YimMenu/issues/1302

**Closed as completed by xiaoxiao921** 2023-05-31 17:20 UTC
Labels: bug
