### ISSUE TITLE
[Bug]: ERR_MEM_EMBEDDEDALLOC_ALLOC

### ISSUE THREAD

**Issue by R3CKLES2** [Yimura/YimMenu#2201] opened 2023-09-26 19:56 UTC
### Describe the bug

Recently the game often crashes due to this error, this happens if I often change the session and then play for a while. The error window is not displayed, the error is only visible in count.log. I know that this error has been fixed before, but perhaps it has appeared again or is there something wrong with my computer?
P.S. It crashed 2 times when I tried to check #2195  , I changed the session 10-14 times in a row without stopping, the game did not crash, but when I decided to play, after some time the game crashed.

### Steps To Reproduce

For me.
1. Change session 11-14 times
2. Play 5 - 30 minutes
3. Crash

### Expected Behavior

Crash shouldn't happen

### Logs and/or screenshots

[cout.log](https://github.com/YimMenu/YimMenu/files/12731412/cout.log)

### Store

Steam

### Additional context

I changed the session through the game menu.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment] 2023-09-26 19:59
Duplicate of #2195 

Will update the title of the other issue so others that have the same issue don't create another issue.

**Closed as completed by Yimura** 2023-09-26 19:59 UTC
Labels: bug
