### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ChaT0n** [Yimura/YimMenu#1861] opened 2023-07-26 20:27 UTC
### Describe the bug

Ip address of players not showing correctly, or it is empty or showing unknown, or 255.255.255.255
This wasn't present 10 days ago

### Steps To Reproduce

Clikc on a player in the player list whosing when u open the menu
And read what is showing in the player info in ip address

### Expected Behavior

Show correct ip

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment] 2023-07-26 20:33
Duplicate of #1836

**Closed as completed by Yimura** 2023-07-26 20:33 UTC
Labels: bug
