### ISSUE TITLE
[Bug]:Game crashes when I'm injecting dll

### ISSUE THREAD

**Issue by opium-user** [Yimura/YimMenu#2728] opened 2024-02-20 16:00 UTC
### Describe the bug

After pressing "Inject" in Xenos, the game crashes immediately and I can see the logs just for a few seconds, then the window closes. The problem only started to occur today(yesterday it was all good)
Please find attached full logs

### Steps To Reproduce

1. Launch game
2. Inject the menu
3. Watch the game crash with no error codes
4. See logs

### Expected Behavior

Well... i expected it to work just as before :)

### Logs and/or screenshots

[cout.log](https://github.com/YimMenu/YimMenu/files/14348088/cout.log)

### Store

Epic Games

### Language

Russian

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment] 2024-02-20 16:00
Duplicate of #2726

**Closed as completed by Yimura** 2024-02-20 16:00 UTC
Labels: bug
