### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ChaT0n** [Yimura/YimMenu#1930] opened 2023-08-06 23:39 UTC
### Describe the bug

Lately i've frequently noticed the following error in the log:
[WARN/log_message_error_box.cpp:37] Error Code: ERR_MEM_EMBEDDEDALLOC_ALLOC

### Steps To Reproduce

Using Yimmenu

### Expected Behavior

avoiding the mem error (i think i ain't a guru)

### Logs and/or screenshots

```
[cout.log](https://github.com/YimMenu/YimMenu/files/12270867/cout.log)

```

### Store

Epic Games

### Additional context

The presence of the empty lines in the log files is because i've removed the "player joined" for some privacy

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment] 2023-08-07 00:03
This is a duplicate of #1545

**Comment by Yimura** [comment] 2023-08-07 07:06
Duplicate of #1545

**Closed as completed by Yimura** 2023-08-07 07:06 UTC
Labels: bug
