### ISSUE TITLE
[Request]: make the mods folder (in BigBaseV2) works

### ISSUE THREAD

**Issue by iswaxan** [Yimura/YimMenu#1209] opened 2023-04-07 17:15 UTC
### Problem

title says it

### Solution

e

### Reason

aaah when injecting yimmenu and having any mods (SP) make me instacrash

### Additional context

already did a bug issue as of it didnt work

**Comment by Yimura** [comment] 2023-04-07 17:21
Duplicate of #1206

**Closed as completed by Yimura** 2023-04-07 17:21 UTC
Labels: request

**Comment by Yimura** [comment] 2023-04-07 17:28
Duplicate of #117
