### ISSUE TITLE
[Bug]: can't see friends

### ISSUE THREAD

**Issue by jvsandhu** [Yimura/YimMenu#2526] opened 2023-12-13 15:20 UTC
### Describe the bug

latest dll from nightly 

joined crew session of a friend and could not see him not in list or his model and the menu kept on showing error something like invalid model from my friend. 
also, he couldn't get in lsc when menu was loaded. 
things went back to normal as soon as I unloaded the menu.

behavior is different when loading menu after joining friend.

### Steps To Reproduce

start the game inject in single player and join a friend's session.

### Expected Behavior

idk maybe some new content is not recognized by menu which is trigging the unknown model error.

### Logs and/or screenshots

```
<[15:17:37.8812771][INFO/main.cpp:104] Yim's Menu Initializing
[15:17:37.8813034][INFO/main.cpp:105] Git Info
        Branch: master
        Hash:   efef962fe8406e88f57982606a2530b1de1b4838
        Date:   Tue Dec 12 23:37:31 2023
[15:17:37.8813174][DEBUG/thread_pool.cpp:22] Resizing thread pool from 0 to 4
[15:17:37.8814892][INFO/main.cpp:108] Thread pool initialized.
[15:17:37.8842192][INFO/main.cpp:111] Settings Loaded.
[15:17:37.8842285][DEBUG/thread_pool.cpp:96] Thread 2228 executing settings.cpp:12
[15:17:37.8844517][INFO/pointers.hpp:94] GTA5 pointers cache is up to date, using it.
[15:17:37.8844584][INFO/pointers.cpp:1808] Loading pointers instance from cache
[15:17:37.8844598][INFO/pointers.cpp:1817] Pointers cache: Loading 215 fields from the cache
[15:17:37.8844680][DEBUG/module.cpp:50] Waiting for socialclub.dll...
[15:17:37.8845316][INFO/pointers.hpp:94] Social Club pointers cache is up to date, using it.
[15:17:37.8845339][INFO/pointers.cpp:1808] Loading pointers instance from cache
[15:17:37.8845352][INFO/pointers.cpp:1817] Pointers cache: Loading 5 fields from the cache
[15:17:37.8845826][INFO/main.cpp:114] Pointers initialized.
[15:17:37.8845917][INFO/main.cpp:121] Disabled anticheat gameskeleton.
[15:17:37.8850578][INFO/main.cpp:124] Byte Patch Manager initialized.
[15:17:37.8861181][FATAL/exception_handler.cpp:42] EXCEPTION_ACCESS_VIOLATION
Dumping modules:
GTA5.exe Base Address: 0x7FF66AC40000 Size: 67215872
ntdll.dll Base Address: 0x7FFBBB030000 Size: 1249280
KERNEL32.DLL Base Address: 0x7FFBB9260000 Size: 528384
KERNELBASE.dll Base Address: 0x7FFBB8590000 Size: 1638400
apphelp.dll Base Address: 0x7FFBB5710000 Size: 335872
USER32.dll Base Address: 0x7FFBB9090000 Size: 610304
win32u.dll Base Address: 0x7FFBB84C0000 Size: 49152
GDI32.dll Base Address: 0x7FFBB9760000 Size: 57344
gdi32full.dll Base Address: 0x7FFBB8940000 Size: 675840
msvcp_win.dll Base Address: 0x7FFBB84F0000 Size: 335872
ucrtbase.dll Base Address: 0x7FFBB83A0000 Size: 798720
PSAPI.DLL Base Address: 0x7FFBBAA60000 Size: 4096
WS2_32.dll Base Address: 0x7FFBBA060000 Size: 290816
RPCRT4.dll Base Address: 0x7FFBBA3D0000 Size: 880640
CRYPT32.dll Base Address: 0x7FFBB8A60000 Size: 1134592
VERSION.dll Base Address: 0x7FFBB0E40000 Size: 12288
WINTRUST.dll Base Address: 0x7FFBB8BD0000 Size: 307200
GFSDK_ShadowLib.win64.dll Base Address: 0x7FFB2B630000 Size: 96256
DSOUND.dll Base Address: 0x7FFB8A050000 Size: 491520
msvcrt.dll Base Address: 0x7FFBBA940000 Size: 507904
advapi32.dll Base Address: 0x7FFBBA880000 Size: 434176
IMM32.dll Base Address: 0x7FFBB9720000 Size: 126976
bink2w64.dll Base Address: 0x7FFB89FC0000 Size: 307712
sechost.dll Base Address: 0x7FFBB9670000 Size: 446464
SHLWAPI.dll Base Address: 0x7FFBB9790000 Size: 212992
ole32.dll Base Address: 0x7FFBB8EF0000 Size: 909312
SHELL32.dll Base Address: 0x7FFBB97F0000 Size: 6848512
combase.dll Base Address: 0x7FFBBA4F0000 Size: 2539520
OLEAUT32.dll Base Address: 0x7FFBBA1C0000 Size: 647168
WININET.dll Base Address: 0x7FFBA36C0000 Size: 2113536
WINMM.dll Base Address: 0x7FFBAF380000 Size: 114688
MFPlat.DLL Base Address: 0x7FFB99B80000 Size: 1503232
MF.dll Base Address: 0x7FFB99DB0000 Size: 372736
msdmo.dll Base Address: 0x7FFBAFAF0000 Size: 16384
shcore.dll Base Address: 0x7FFBBAEF0000 Size: 684032
MFReadWrite.dll Base Address: 0x7FFB81E50000 Size: 995328
PROPSYS.dll Base Address: 0x7FFBB3520000 Size: 692224
WTSAPI32.dll Base Address: 0x7FFBB7150000 Size: 40960
d3d9.dll Base Address: 0x7FFBAA530000 Size: 1306624
D3DCOMPILER_43.dll Base Address: 0x7FFB474D0000 Size: 2423296
ResampleDmo.DLL Base Address: 0x7FFB89F00000 Size: 503808
GFSDK_TXAA_AlphaResolve.win64.dll Base Address: 0x7FFBAD3D0000 Size: 48128
DINPUT8.dll Base Address: 0x7FFBAB9A0000 Size: 176128
XINPUT1_3.dll Base Address: 0x400000 Size: 85504
SETUPAPI.dll Base Address: 0x7FFBBAA70000 Size: 913408
IPHLPAPI.DLL Base Address: 0x7FFBB6E20000 Size: 122880
bcrypt.dll Base Address: 0x7FFBB7D50000 Size: 110592
powrprof.dll Base Address: 0x7FFBB7BE0000 Size: 77824
winmmbase.dll Base Address: 0x7FFBA3C30000 Size: 102400
d3dx9_43.dll Base Address: 0x7FFB28C50000 Size: 2280960
cfgmgr32.dll Base Address: 0x7FFBB8060000 Size: 221184
dwmapi.dll Base Address: 0x7FFBB5B30000 Size: 90112
OPENGL32.dll Base Address: 0x7FFB99680000 Size: 798720
GLU32.dll Base Address: 0x7FFBACF70000 Size: 126976
dxcore.dll Base Address: 0x7FFBB59C0000 Size: 131072
MFCORE.DLL Base Address: 0x7FFB825B0000 Size: 3026944
UMPDC.dll Base Address: 0x7FFBB7BC0000 Size: 36864
kernel.appcore.dll Base Address: 0x7FFBB73A0000 Size: 36864
bcryptPrimitives.dll Base Address: 0x7FFBB8D00000 Size: 376832
RTWorkQ.DLL Base Address: 0x7FFBA2E30000 Size: 102400
MSASN1.dll Base Address: 0x7FFBB7B40000 Size: 36864
inputhost.dll Base Address: 0x7FFB9E330000 Size: 1540096
CoreMessaging.dll Base Address: 0x7FFBB52F0000 Size: 860160
CRYPTBASE.DLL Base Address: 0x7FFBB7B00000 Size: 12288
windows.storage.dll Base Address: 0x7FFBB62C0000 Size: 7032832
wintypes.dll Base Address: 0x7FFBB6180000 Size: 544768
dbghelp.dll Base Address: 0x7FFBAD9A0000 Size: 1646592
dbgcore.DLL Base Address: 0x7FFBAC560000 Size: 131072
d3d12.dll Base Address: 0x7FFBAB460000 Size: 102400
CRYPTSP.dll Base Address: 0x7FFBB7AE0000 Size: 57344
uxtheme.dll Base Address: 0x7FFBB5850000 Size: 425984
rsaenh.dll Base Address: 0x7FFBB7300000 Size: 147456
clbcatq.dll Base Address: 0x7FFBBA2A0000 Size: 471040
dxdiagn.dll Base Address: 0x7FFB8B400000 Size: 253952
d3d11.dll Base Address: 0x7FFBB4820000 Size: 1867776
WMICLNT.dll Base Address: 0x7FFBB2580000 Size: 32768
DEVOBJ.dll Base Address: 0x7FFBB80B0000 Size: 110592
dxgi.dll Base Address: 0x7FFBB5A20000 Size: 651264
imagehlp.dll Base Address: 0x7FFBB8ED0000 Size: 49152
wbemprox.dll Base Address: 0x7FFBAF370000 Size: 28672
wbemcomn.dll Base Address: 0x7FFBAC780000 Size: 311296
gpapi.dll Base Address: 0x7FFBB7920000 Size: 77824
wbemsvc.dll Base Address: 0x7FFBAB800000 Size: 8192
cryptnet.dll Base Address: 0x7FFBB0E00000 Size: 139264
fastprox.dll Base Address: 0x7FFBAC010000 Size: 708608
profapi.dll Base Address: 0x7FFBB82D0000 Size: 90112
amsi.dll Base Address: 0x7FFBAB700000 Size: 57344
USERENV.dll Base Address: 0x7FFBB7980000 Size: 102400
MpOav.dll Base Address: 0x7FFBAB680000 Size: 204800
WINNSI.DLL Base Address: 0x7FFBB5970000 Size: 16384
NSI.dll Base Address: 0x7FFBBA050000 Size: 8192
EOSSDK-Win64-Shipping.dll Base Address: 0x7FFB14040000 Size: 7229440
WLDAP32.dll Base Address: 0x7FFBBA9F0000 Size: 282624
Normaliz.dll Base Address: 0x7FFBB9250000 Size: 4096
Secur32.dll Base Address: 0x7FFBB7170000 Size: 12288
WINHTTP.dll Base Address: 0x7FFBB2010000 Size: 987136
MSVCP140.dll Base Address: 0x7FFBABB80000 Size: 345600
VCRUNTIME140.dll Base Address: 0x7FFBAE800000 Size: 65024
VCRUNTIME140_1.dll Base Address: 0x7FFBB4E40000 Size: 15360
SSPICLI.DLL Base Address: 0x7FFBB7600000 Size: 126976
dhcpcsvc6.DLL Base Address: 0x7FFBB1FF0000 Size: 28672
dhcpcsvc.DLL Base Address: 0x7FFBB1FD0000 Size: 69632
mswsock.dll Base Address: 0x7FFBB7820000 Size: 331776
directxdatabasehelper.dll Base Address: 0x7FFBB1AD0000 Size: 196608
napinsp.dll Base Address: 0x7FFB9E000000 Size: 53248
pnrpnsp.dll Base Address: 0x7FFB9AA20000 Size: 69632
DNSAPI.dll Base Address: 0x7FFBB6E90000 Size: 737280
winrnr.dll Base Address: 0x7FFB99D50000 Size: 32768
wshbth.dll Base Address: 0x7FFBB1B20000 Size: 45056
nlansp_c.dll Base Address: 0x7FFB89CD0000 Size: 81920
nvapi64.dll Base Address: 0x7FFB9E9D0000 Size: 5586944
D3D10_1.DLL Base Address: 0x7FFBAB420000 Size: 147456
d3d10_1core.dll Base Address: 0x7FFBAC6C0000 Size: 12288
MSCTF.dll Base Address: 0x7FFBB8D80000 Size: 1073152
textinputframework.dll Base Address: 0x7FFB9A1B0000 Size: 1015808
rasadhlp.dll Base Address: 0x7FFBAF2F0000 Size: 8192
WINSTA.dll Base Address: 0x7FFBB7890000 Size: 229376
nvldumdx.dll Base Address: 0x7FFBAD4D0000 Size: 830976
fwpuclnt.dll Base Address: 0x7FFBB16F0000 Size: 294912
nvwgf2umx.dll Base Address: 0x7FFB4E5F0000 Size: 21153792
HID.DLL Base Address: 0x7FFBB6BC0000 Size: 24576
MMDevApi.dll Base Address: 0x7FFBAEEB0000 Size: 462848
XAudio2_7.dll Base Address: 0x7FFB89E70000 Size: 485376
AUDIOSES.DLL Base Address: 0x7FFBA6690000 Size: 1409024
resourcepolicyclient.dll Base Address: 0x7FFBB5E70000 Size: 36864
Windows.UI.dll Base Address: 0x7FFBA3FA0000 Size: 966656
avrt.dll Base Address: 0x7FFBB2290000 Size: 8192
socialclub.dll Base Address: 0x7FFB29290000 Size: 5133824
chrome_elf.dll Base Address: 0x7FFBAB9F0000 Size: 676864
libcef.dll Base Address: 0x7FFB14A60000 Size: 109744128
COMDLG32.dll Base Address: 0x7FFBB9570000 Size: 778240
UIAutomationCore.DLL Base Address: 0x7FFB94020000 Size: 3063808
OLEACC.dll Base Address: 0x7FFBAC870000 Size: 274432
NETAPI32.dll Base Address: 0x7FFB95D20000 Size: 49152
COMCTL32.dll Base Address: 0x7FFBAA980000 Size: 573440
DWrite.dll Base Address: 0x7FFBB3FB0000 Size: 1650688
WINSPOOL.DRV Base Address: 0x7FFBAA870000 Size: 405504
USP10.dll Base Address: 0x7FFB88A70000 Size: 4096
dxva2.dll Base Address: 0x7FFB88A90000 Size: 102400
credui.dll Base Address: 0x7FFB92CE0000 Size: 65536
urlmon.dll Base Address: 0x7FFBAC9C0000 Size: 1298432
ncrypt.dll Base Address: 0x7FFBB7D20000 Size: 114688
CRYPTUI.dll Base Address: 0x7FFB88AC0000 Size: 278528
wevtapi.dll Base Address: 0x7FFBB1CF0000 Size: 282624
ESENT.dll Base Address: 0x7FFBA0950000 Size: 3145728
srvcli.dll Base Address: 0x7FFBA6F80000 Size: 57344
iertutil.dll Base Address: 0x7FFBA6CC0000 Size: 557056
netutils.dll Base Address: 0x7FFBB6E10000 Size: 20480
WKSCLI.DLL Base Address: 0x7FFBB1BC0000 Size: 49152
SAMCLI.DLL Base Address: 0x7FFBAC380000 Size: 61440
NTASN1.dll Base Address: 0x7FFBB7CE0000 Size: 69632
FirewallAPI.dll Base Address: 0x7FFBB6D30000 Size: 385024
fwbase.dll Base Address: 0x7FFBB6C70000 Size: 208896
FWPolicyIOMgr.dll Base Address: 0x7FFBA2E90000 Size: 245760
wdmaud.drv Base Address: 0x7FFB89DD0000 Size: 200704
ksuser.dll Base Address: 0x7FFBABB70000 Size: 8192
msacm32.drv Base Address: 0x7FFBABB20000 Size: 20480
MSACM32.dll Base Address: 0x7FFBA4490000 Size: 77824
midimap.dll Base Address: 0x7FFBAB920000 Size: 16384
ondemandconnroutehelper.dll Base Address: 0x7FFBAAF40000 Size: 45056
DiscordHook64.dll Base Address: 0x7FFB2AC30000 Size: 791040
ntmarta.dll Base Address: 0x7FFBB73C0000 Size: 147456
D3DCompiler_47.dll Base Address: 0x7FFBB3BC0000 Size: 3043328
xinput1_4.dll Base Address: 0x7FFBAADA0000 Size: 32768
schannel.DLL Base Address: 0x7FFBB71F0000 Size: 561152
ncryptsslp.dll Base Address: 0x7FFB9E540000 Size: 86016
CoreUIComponents.dll Base Address: 0x7FFBB1090000 Size: 2039296
YimMenu.dll Base Address: 0x7FFB134B0000 Size: 9088512
Dumping registers:
RAX: 0x35
RCX: 0x23A67153548
RDX: 0x23
RBX: 0x23A67174400
RSI: 0x23B2CDCBFFF
RDI: 0x23B2D42A615
RSP: 0xA19C0FF340
RBP: 0xA19C0FF3D9
R8:  0x7FF66DB359A0
R9:  0x23B364A0000
R10: 0x2
R11: 0x23A6714D230
R12: 0x8
R13: 0x23B364DECE0
R14: 0x23A671743C0
R15: 0x23A67510B88
Dumping stacktrace:
[0]     GTA5.exe+0x161F9A4 0x7FF66C25F9A4
[1]     GTA5.exe+0x16204CF 0x7FF66C2604CF
[2]     GTA5.exe+0xA59780 0x7FF66B699780
[3]     GTA5.exe+0x1620BB1 0x7FF66C260BB1
[4]     GTA5.exe+0xA4DFC4 0x7FF66B68DFC4
[5]     GTA5.exe+0xA51880 0x7FF66B691880
[6]     GTA5.exe+0x162FA85 0x7FF66C26FA85
[7]     GTA5.exe+0x162FA85 0x7FF66C26FA85
[8]     GTA5.exe+0x162F2B7 0x7FF66C26F2B7
[9]     GTA5.exe+0x27B94 0x7FF66AC67B94
[10]    GTA5.exe+0x21283 0x7FF66AC61283
[11]    GTA5.exe+0x162EEC0 0x7FF66C26EEC0
[12]    GTA5.exe+0x1494 0x7FF66AC41494
[13]    GTA5.exe+0x130538F 0x7FF66BF4538F
[14]    GTA5.exe+0x1821344 0x7FF66C461344
[15]    KERNEL32.DLL BaseThreadInitThunk
[16]    ntdll.dll RtlUserThreadStart
--------End of exception--------

[15:17:38.3530188][INFO/main.cpp:127] Renderer initialized.
[15:17:38.5539579][INFO/main.cpp:131] Fiber pool initialized.
[15:17:38.5547658][INFO/main.cpp:134] HTTP Client initialized.
[15:17:38.6132502][INFO/main.cpp:137] Translation Service initialized.
[15:17:38.6317263][INFO/main.cpp:140] Hooking initialized.
[15:17:38.6353969][DEBUG/gta_data_service.cpp:160] Loading data from cache.
[15:17:38.6354064][INFO/gta_data_service.cpp:172] Loading 1051 peds from cache.
[15:17:38.6357126][INFO/gta_data_service.cpp:190] Loading 843 vehicles from cache.
[15:17:38.6359708][INFO/gta_data_service.cpp:207] Loading 119 weapons from cache.
[15:17:38.6359725][INFO/gta_data_service.cpp:208] Loading 380 weapon components from cache.
[15:17:38.6359866][DEBUG/gta_data_service.cpp:166] Loaded all data from cache.
[15:17:38.6365857][DEBUG/thread_pool.cpp:96] Thread 12668 executing player_database_service.cpp:285
[15:17:38.6366584][INFO/main.cpp:161] Registered service instances...
[15:17:38.6367471][INFO/main.cpp:182] Scripts registered.
[15:17:38.6728200][INFO/main.cpp:185] Hooking enabled.
[15:17:38.6758619][INFO/main.cpp:188] Dynamic native hooker initialized.
[15:17:38.6818809][INFO/lua_module.cpp:293] Loaded AcidLab.lua
[15:17:38.6862942][INFO/lua_module.cpp:293] Loaded CasinoPacino.lua
[15:17:38.6916845][INFO/lua_module.cpp:293] Loaded Coords.lua
[15:17:38.6988904][INFO/lua_module.cpp:293] Loaded DailyCollectibles.lua
[15:17:38.7042139][WARN/log.cpp:27] pessi_v0.2_[unknowncheats.me]_.lua: Use At Your Own Risk This Hasn't Been Tested With YimMenu, But It's Safe With Some Menus..
[15:17:38.7043547][INFO/lua_module.cpp:293] Loaded pessi_v0.2_[unknowncheats.me]_.lua
[15:17:38.7100477][INFO/lua_module.cpp:293] Loaded VehicleNames.lua
[15:17:38.7101086][INFO/main.cpp:192] Lua manager initialized.
[15:17:38.7892403][INFO/backend.cpp:53] Starting script: Self
[15:17:38.7892547][INFO/backend.cpp:78] Starting script: Weapons
[15:17:38.7892638][INFO/backend.cpp:101] Starting script: Vehicles
[15:17:38.7892701][INFO/backend.cpp:117] Starting script: Miscellaneous
[15:17:38.7892983][INFO/backend.cpp:138] Starting script: Remote
[15:17:38.7893043][INFO/backend.cpp:153] Starting script: Ls customs
[15:17:38.7893070][INFO/backend.cpp:165] Starting script: Rainbow paint
[15:17:38.7893096][INFO/backend.cpp:177] Starting script: Disable Control Action
[15:17:38.7893117][INFO/backend.cpp:190] Starting script: World
[15:17:38.8041487][INFO/tunables_service.cpp:36] Loading tunables from cache
>
```

### Store

Epic Games

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment] 2023-12-13 15:30
Duplicate of #2525

**Closed as completed by Yimura** 2023-12-13 15:30 UTC
Labels: bug
