### ISSUE TITLE
[Request]: Rockstar Admin Alert

### ISSUE THREAD

**Issue by Rxann** [Yimura/YimMenu#1181] opened 2023-04-03 14:08 UTC
### Solution

A logo next to their name and when you join a lobby and an admin is in there it gives you a notification. Also if one joins it could also give you a notification.

### Reason

So no one accidentally kicks and admin or uses stuff on an admin

**Comment by Yimura** [comment] 2023-04-03 14:09
Duplicate of #650

**Closed as completed by Yimura** 2023-04-03 14:09 UTC
Labels: request
