### ISSUE TITLE
Old aimbot to come back

### ISSUE THREAD

**Issue by meowmeowmoew3** [Yimura/YimMenu#2812] opened 2024-03-09 19:33 UTC
### Problem

the new aimbot is a little too snappy and i have no control over it

### Solution

Creating a new "aim assist " with the older aimbot implementation

### Reason

New aimbot too strong

**Comment by Yimura** [comment] 2024-03-09 19:34
Duplicate of #2671

**Closed as completed by Yimura** 2024-03-09 19:34 UTC
Labels: request
