### ISSUE TITLE
[Build]: CMake Error at minhook

### ISSUE THREAD

**Issue by N3OA** [Yimura/YimMenu#2049] opened 2023-08-29 11:17 UTC
### Describe the build issues

When building i get this error:

Severity	Code	Description	Project	File	Line	Suppression State
Error		CMake Error at minhook-subbuild/minhook-populate-prefix/tmp/minhook-populate-gitclone.cmake:62 (message):
  **Failed to update submodules in:
  'D:/VisualStudioFiles/YimMenu/out/build/x64-Release/_deps/minhook-src'**

[1/9] Creating directories for 'minhook-populate'
[1/9] Performing download step (git clone) for 'minhook-populate'
FAILED: minhook-populate-prefix/src/minhook-populate-stamp/minhook-populate-download D:/VisualStudioFiles/YimMenu/out/build/x64-Release/_deps/minhook-subbuild/minhook-populate-prefix/src/minhook-populate-stamp/minhook-populate-download 
cmd.exe /C "cd /D D:\VisualStudioFiles\YimMenu\out\build\x64-Release\_deps && "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -P D:/VisualStudioFiles/YimMenu/out/build/x64-Release/_deps/minhook-subbuild/minhook-populate-prefix/tmp/minhook-populate-gitclone.cmake && "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E touch D:/VisualStudioFiles/YimMenu/out/build/x64-Release/_deps/minhook-subbuild/minhook-populate-prefix/src/minhook-populate-stamp/minhook-populate-download"
ninja: build stopped: subcommand failed.		D:\VisualStudioFiles\YimMenu\minhook-subbuild/minhook-populate-prefix/tmp/minhook-populate-gitclone.cmake		

and

Severity	Code	Description	Project	File	Line	Suppression State
Error		CMake Error at C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.26/Modules/FetchContent.cmake:1622 (message):
  Build step for minhook failed: 1	CrossCompileExample	C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.26/Modules/FetchContent.cmake	1622	

### Screenshots and/or Logs

```

```

### IDE/Compiler

Visual Studio 2022

### Additional context

Did follow the instructions.

### Setup Guide

- [X] I confirm that I followed the setup guide correctly.

### YimMenu Source Code

- [X] I've confirmed this is an issue with building unmodified YimMenu.

**Comment by Yimura** [comment] 2023-08-29 11:20
Possible duplicate of #1992 
Duplicate of #1707 

Please make sure you follow the setup instructions properly.

**Comment by N3OA** [comment] 2023-08-29 11:32
> Possible duplicate of #1992 Duplicate of #1707
> 
> Please make sure you follow the setup instructions properly.

If you look you can see it says: **Failed to update submodules in: 'D:/VisualStudioFiles/YimMenu/out/build/x64-Release/_deps/minhook-src'**.

Git is working and installed. Followed everything(not first time using git or cmake). 
So no its not a duplicate if you read the error.

**Comment by Yimura** [comment] 2023-08-29 11:33
Have you tried deleting the `out/` directory and then pressing CTRL + S in the CMakeLists.txt file again?

**Comment by N3OA** [comment] 2023-08-29 11:39
> Have you tried deleting the `out/` directory and then pressing CTRL + S in the CMakeLists.txt file again?

Yes just did, same error.

https://i.postimg.cc/zB3X6DbP/image.png

**Comment by Yimura** [comment] 2023-08-29 11:53
Are you sure you added `git` to your Path environment variable? With your current CMake output the only issue could be with the git executable not being present in your Path or not installed.

You can verify this and let us know by opening a new terminal and just typing `git` in it.

**Comment by N3OA** [comment] 2023-08-29 12:00
> Are you sure you added `git` to your Path environment variable? With your current CMake output the only issue could be with the git executable not being present in your Path or not installed.
> 
> You can verify this and let us know by opening a new terminal and just typing `git` in it.

Yes i have. Also i used git to download the project (git clone https://github.com/YimMenu/YimMenu.git).

https://i.postimg.cc/s2c7DjJJ/image.png

**Comment by Yimura** [comment] 2023-08-29 18:22
Yeah I've got no clue on what the issue is, if you've followed the guide correctly it should just work.

**Comment by gir489returns** [comment] 2023-09-05 23:44
@N3OA Please advise if you want to continue this ticket or not, it's been a week, if not close it.

**Comment by N3OA** [comment] 2023-09-06 12:51
The problem hasn't been fixed, i have tried again and still it doesn't work.

**Comment by xiaoxiao921** [comment] 2023-09-07 22:03
What about `cmake /V` in a terminal? Seems to be purely a CMake issue on your end, it somehow fail to clone a repo through the CMake FetchContent directive

**Comment by N3OA** [comment] 2023-09-08 00:23
I tried again same error, tried with other project works perfect so idk. I use cmake for other projects and have no issues.

**Comment by xiaoxiao921** [comment] 2023-09-08 07:47
? Does your other cmake projects use the FetchContent directive? What does cmake /V say??

**Comment by Yimura** [comment] 2023-09-10 14:27
Using the setup guide on a clean Windows installation I was not able to reproduce this issue.

Try uninstalling Visual Studio and following the installation guide again. CMake should come with Visual Studio and does not need to be installed separately.

**Closed as completed by Yimura** 2023-09-10 14:27 UTC
Labels: build
