### ISSUE TITLE
[Bug]: ped crash spam

### ISSUE THREAD

**Issue by DSTC69** [Yimura/YimMenu#2528] opened 2023-12-13 16:52 UTC
### Describe the bug

so its a player model protection spam of everyone in the lobby i think its just because some of the code is outdated 

### Steps To Reproduce

![Capture](https://github.com/YimMenu/YimMenu/assets/153653110/fcdff602-7772-477e-a426-88f408aa8505)

### Expected Behavior

i know the menu is being fixed but after a few secs of being a semi full lobby it crashes to what i assume is a loopin the code overloading and it fully crashes its fine in a small lobby but still has the spam

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Epic Games

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by CypherMorgan** [comment] 2023-12-13 16:54
Duplicate of #2525

**Closed as completed** 2023-12-13 17:04 UTC
Labels: bug
