### ISSUE TITLE
[Request]: Addition of Emotes 

### ISSUE THREAD

**Issue by CypherMorgan** [Yimura/YimMenu#1263] opened 2023-04-18 13:02 UTC
### Problem

Being able to use Emotes would be cool addition :D

### Solution

A way through which we might be able to use emotes..

### Reason

Would be Fun to use Emotes

**Comment by TheGreenBandit** [comment] 2023-04-18 13:54
Dupe of #187?

**Comment by CypherMorgan** [comment] 2023-04-18 13:56
Ah, My bad... Didn't saw that:(
Closing this one..

**Closed as completed** 2023-04-18 13:56 UTC
Labels: request
