### ISSUE TITLE
[Bug]: when trying to build file it doesn't  want to build 

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#1065] opened 2023-03-11 00:20 UTC
### Describe the bug

when trying to build file it doesn't  want to build 

### Steps To Reproduce

![cmake](https://user-images.githubusercontent.com/69077883/224452639-f97ea5e2-a02d-43ec-868b-0ae9887e4511.png)
![cmake2](https://user-images.githubusercontent.com/69077883/224452640-3da74951-3d78-40d8-b2a1-bbc55c4fe647.png)
![cmake3](https://user-images.githubusercontent.com/69077883/224452641-e88131d9-a5fb-4102-9da7-af33f2660555.png)

### Expected Behavior

i expected it to build 

### Screenshots and/or Logs

```
<paste your logs here>
```
![cmake](https://user-images.githubusercontent.com/69077883/224452409-be28d894-86bd-46ec-b474-71a0af2c0dc0.png)

### Store

Steam

### Additional context

wont compile or build

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by GeopJr** [comment] 2023-03-11 00:24
try this: https://github.com/YimMenu/YimMenu/issues/642#issuecomment-1328062288

**Comment by Yimura** [comment] 2023-03-12 17:10
The comment from @GeopJr should be the fix to your issue.

Duplicate of #642

**Closed as completed by Yimura** 2023-03-12 17:10 UTC
Labels: bug
