### ISSUE TITLE
Crash freemode_script_recovery | line 23

### ISSUE THREAD

**Issue by revolutionxk** [Yimura/YimMenu#10] opened 2021-12-17 23:01 UTC
Crashes on join casino or roll the roulette

**Comment by Yimura** [comment] 2021-12-18 01:16
I have been able to reproduce the issue mentioned above.

As of now I have no idea what's causing this. The call to the original method causes an exception I'm unsure what's causing it.

**Comment by Yimura** [comment] 2021-12-18 01:35
When I disable the hook for GTA V Thread Tick the error occurs somewhere else in the menu.

<details>
<summary>Log</summary>

```
***** FATAL EXCEPTION RECEIVED ******* 

***** Vectored Exception Handler: Received fatal exception EXCEPTION_ACCESS_VIOLATION	PID: 14556

*******	STACKDUMP *******
stack dump [0]	
stack dump [1]	
stack dump [2]	
stack dump [3]	
stack dump [4]	
stack dump [5]	
stack dump [6]	
stack dump [7]	
stack dump [8]		C:\Users\andre\Coding\cpp\YimMenu\BigBaseV2\src\hooking.cpp L: 162 big::hooks::run_script_threads
stack dump [9]	
stack dump [10]	
stack dump [11]	
stack dump [12]	
stack dump [13]	
stack dump [14]	
stack dump [15]	
stack dump [16]	
stack dump [17]	
stack dump [18]	
stack dump [19]	
stack dump [20]	 BaseThreadInitThunk
stack dump [21]	 RtlUserThreadStart

Exiting after fatal event  (FATAL_EXCEPTION). Fatal type:  EXCEPTION_ACCESS_VIOLATION
Log content flushed successfully to sink
```
</details>

**Comment by Yimura** [comment] 2021-12-18 12:24
Freemode script recovery is not at all the culprit, after I disabled everything that ran in the background the crash no longer occurs.

**Comment by Yimura** [comment] 2021-12-18 12:37
The crash is related to protections replay interface, disabling this will completely stop this from happening ever again.

I will push a commit later today to remove replay interface.

**Comment by Yimura** [comment] 2021-12-18 13:31
This has been fixed by no longer calling the replay interface on tick, this is fine since it wasn't accessible directly without first adding buttons to enable the features present or changing the settings.json file.

**Closed as completed by Yimura** 2021-12-18 13:31 UTC
