### ISSUE TITLE
[Bug]: Aim bot

### ISSUE THREAD

**Issue by raviyaaas** [Yimura/YimMenu#1508] opened 2023-06-23 04:53 UTC
### Describe the bug

aim bot is not working properly. The aim rotates in all directions while playing

### Steps To Reproduce

1 wepon
2aim bot

### Expected Behavior

aim bot is not working properly. The aim rotates in all directions while playing

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Additional context

aim bot is not working properly. The aim rotates in all directions while playing

### Build

- [x] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment] 2023-06-23 06:24
Did you change the settings of the aimbot and then it suddenly stopped working correctly?

Can you try to remove the `settings.json` file under `%appdata/BigBaseV2/` and see if that fixes it?

**Comment by T14D3** [comment] 2023-06-25 08:43
I'm 99% sure this Issue is caused by #1507 since I can only reproduce the Issue after that commit

**Comment by gir489returns** [comment] 2023-12-12 01:15
This should be fixed with https://github.com/YimMenu/YimMenu/pull/2480.

**Comment by lonelybud** [comment] 2023-12-21 05:57
try this - 

smoothing_speed = 4
fov             = 90
distance you can vary

**Closed as completed** 2024-07-22 21:48 UTC
Labels: bug
