### ISSUE TITLE
[Build]: 

### ISSUE THREAD

**Issue by kekobob122** [Yimura/YimMenu#3287] opened 2024-06-25 12:52 UTC
### Describe the build issues

you need a update fot the new gta version

### Screenshots and/or Logs

```
<paste your logs here>
```

### IDE/Compiler

Visual Studio 2022

### Additional context

please update yimmenu

### Setup Guide

- [X] I confirm that I followed the setup guide correctly.

### YimMenu Source Code

- [X] I've confirmed this is an issue with building unmodified YimMenu.

**Comment by gir489returns** [comment] 2024-06-25 13:01
This is a duplicate of #3285

**Closed as completed by gir489returns** 2024-06-25 13:01 UTC
Labels: build
