### ISSUE TITLE
[Bug]: #2492 broke console logging in Lua

### ISSUE THREAD

**Issue by Harmless05** [Yimura/YimMenu#2793] opened 2024-03-01 20:51 UTC
### Describe the bug

Update #2492 broke console logging in Lua, so `log.info, log.warn, log.debug` no longer work. The only time logging will work is **before you go into single player** (So, when you are on the loading screen when GTAV starts).

The last build **before it broke** was Nightly Build [#857](https://github.com/YimMenu/YimMenu/actions/runs/8020313387) after which, when #2492 was added, console logging broke.

I have tested every build up to 857

This also broke the display of Lua code errors (at least for me).

### Steps To Reproduce

Create a lua script (Lua example script can be used)
```Lua
missionsTab = gui.get_tab("GUI_TAB_SELF")
missionsTab:add_button("Click me", function ()
    log.info("You clicked!")
end)
```

### Expected Behavior

Console logging should work.

### Logs and/or screenshots

You cannot get any logs.

### Store

Epic Games

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment] 2024-03-01 20:52
Please always verify if there aren’t any open issues already explaining your problem.

**Comment by Yimura** [comment] 2024-03-01 20:52
Duplicate of #2773

**Closed as completed by Yimura** 2024-03-01 20:52 UTC
Labels: bug

**Comment by Harmless05** [comment] 2024-03-01 21:06
Lol, I glanced at that issue, but I thought it was related to something else. 👍
