### ISSUE TITLE
[Bug]: Random repeating EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by Rxann** [Yimura/YimMenu#1128] opened 2023-03-21 01:12 UTC
### Describe the bug

I was going about my time in online and then a random error came up.

### Steps To Reproduce

Well, I pretty much noticed it appear as I was in a vehicle, so I guess enter a vehicle to see if this appears. 

### Expected Behavior

I guess to not have this happen.

### Screenshots and/or Logs

EXCEPTION_ACCESS_VIOLATION
Dumping registers:
RAX: 0x7FF7C94E550E
RCX: 0x1CF524EA128
RDX: 0x2
RBX: 0x8FF16C084C
RSI: 0x0
RDI: 0x8FF16C0858
RSP: 0x8FF16C0680
RBP: 0x2
R8:  0x1
R9:  0x1CF525B8170
R10: 0x7FF786668F70
R11: 0x8FF16C0678
R12: 0x1
R13: 0x1CF525B8170
R14: 0x8FF16C0808
R15: 0x1CF524EA128
Dumping stacktrace:
[0]	GTA5.exe+0x16BD62F 0x7FF78620D62F
[1]	GTA5.exe+0x11407B2 0x7FF785C907B2
[2]	GTA5.exe+0x16BD7D2 0x7FF78620D7D2
[3]	GTA5.exe+0x16B7BBE 0x7FF786207BBE
[4]	GTA5.exe+0x16BBDDA 0x7FF78620BDDA
[5]	GTA5.exe+0x1135B40 0x7FF785C85B40
[6]	GTA5.exe+0x16BA910 0x7FF78620A910
[7]	GTA5.exe+0x113536D 0x7FF785C8536D
[8]	GTA5.exe+0x10AB618 0x7FF785BFB618
[9]	GTA5.exe+0x1606401 0x7FF786156401
[10]	GTA5.exe+0x1605C37 0x7FF786155C37
[11]	GTA5.exe+0x27636 0x7FF784B77636
[12]	GTA5.exe+0x20D4B 0x7FF784B70D4B
[13]	GTA5.exe+0x1605840 0x7FF786155840
[14]	GTA5.exe+0x1494 0x7FF784B51494
[15]	GTA5.exe+0x12E0267 0x7FF785E30267
[16]	GTA5.exe+0x17F7EA4 0x7FF786347EA4
[17]	KERNEL32.DLL BaseThreadInitThunk
[18]	ntdll.dll RtlUserThreadStart
[19]	ntdll.dll RtlUserThreadStart
[20]	GTA5.exe+0x1494 0x7FF784B51494
[21]	GTA5.exe+0x12E0267 0x7FF785E30267
[22]	GTA5.exe+0x17F7EA4 0x7FF786347EA4
[23]	KERNEL32.DLL BaseThreadInitThunk
[24]	ntdll.dll RtlUserThreadStart
[25]	GTA5.exe+0x12E0267 0x7FF785E30267
[26]	GTA5.exe+0x17F7EA4 0x7FF786347EA4
[27]	KERNEL32.DLL BaseThreadInitThunk
[28]	ntdll.dll RtlUserThreadStart

### Store

Steam

### Additional context

It generated 1.3 gb of logs because it was repeating over and over again. This same message was repeated over and over again in the logs I believe

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Rxann** [comment] 2023-03-21 01:13
If you need the full thing, I made a full copy of the file so I can further send that to you

**Comment by steveosten2** [comment] 2023-03-24 18:13
this is happening to me too, it is crashing my game and making a 128mb cout file

**Comment by Aure7138** [comment] 2023-03-27 17:13
crash cannot be reproduced after entering the vehicle. You can tell me which features you have enabled and provide a full log file. Dont upload a log file with a size of 1GB

**Comment by Yimura** [comment] 2023-04-29 12:16
Unable to reproduce bug, closing for now.

**Closed as completed by Yimura** 2023-04-29 12:16 UTC
Labels: bug
