### ISSUE TITLE
[Request]: Add spawn vehicle external by support XML

### ISSUE THREAD

**Issue by D-Borkan** [Yimura/YimMenu#664] opened 2022-12-07 20:11 UTC
### Problem

.

### Solution

.

### Reason

.

### Additional context

That will be very fun

**Comment by tupoy-ya** [comment] 2022-12-08 06:47
Seems like a duplicate of 
* #103

**Comment by Yimura** [comment] 2022-12-08 11:10
Duplicate of #103

**Closed as completed by Yimura** 2022-12-08 11:10 UTC
Labels: request
