### ISSUE TITLE
[Bug]: Prenvent Received Start Script may cause player cant join other's job.

### ISSUE THREAD

**Issue by ProsperFall** [Yimura/YimMenu#936] opened 2023-02-04 03:09 UTC
### Describe the bug

Blocking Received Start Script may cause player cant join other's job.
This feature should have its own switch.

### Steps To Reproduce

1.Join a job.
2.Start job.

### Expected Behavior

Do not block this behavior if user not expected to use it.

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by TheGreenBandit** [comment] 2023-02-04 04:34
duplicate of #926

**Closed as completed** 2023-02-04 16:35 UTC
Labels: bug
