### ISSUE TITLE
[Bug]: End of exception

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#2514] opened 2023-12-12 11:40 UTC
### Describe the bug

After inject last message before crash is "End of exception"

### Steps To Reproduce

1. Inject
2. Wait cmd while cheat is injecting
3. --------End of exception--------

### Expected Behavior

Update of GTA V

### Logs and/or screenshots

[cout.log](https://github.com/YimMenu/YimMenu/files/13647623/cout.log)

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment] 2023-12-12 11:41
Duplicate of #2513

**Closed as completed by Yimura** 2023-12-12 11:41 UTC
Labels: bug
