### ISSUE TITLE
[Bug]: Not logging protections

### ISSUE THREAD

**Issue by SamphireOG** [Yimura/YimMenu#2799] opened 2024-03-03 20:30 UTC
### Describe the bug

Not logging protections

### Steps To Reproduce

Wait for someone to target you and then check console and find no log

### Expected Behavior

to find who and what someone did to trigger protection

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Yimura** [comment] 2024-03-03 21:12
Duplicate of #2773

**Closed as completed by Yimura** 2024-03-03 21:12 UTC
Labels: bug
