### ISSUE TITLE
[Bug]: Crashed right after loading in gto

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#3033] opened 2024-05-02 22:35 UTC
### Describe the bug

crash

### Steps To Reproduce

i just joined online, pretty sure it was a crash sent by a player though since i do have a spoofed host token (force host)

### Expected Behavior

no crash

### Logs

itssa long one
[log.txt](https://github.com/YimMenu/YimMenu/files/15194663/log.txt)

### Screenshots / Video

no

### Store

Epic Games

### Language

English

### YimMenu Language

English (US)

### Additional context

[22:26:36.6271234][INFO/main.cpp:159] Git Info
	Branch:	master
	Hash:	d13b49ca0b7ee3f290de8ab073a158251fa456bd
	Date:	Wed May 1 23:30:25 2024
[22:26:36.6272014][INFO/main.cpp:171] Windows 11 Pro Version 21H2 (OS Build 22000.2538)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment] 2024-05-02 23:55
I too am getting this crash now.

[cout.log](https://github.com/YimMenu/YimMenu/files/15195036/cout.log)

**Comment by gir489returns** [comment] 2024-05-03 00:02
Duplicate of #3030.

**Closed as completed by gir489returns** 2024-05-03 00:02 UTC
Labels: bug, confirmed
