### ISSUE TITLE
[Bug]: im having this issue... how can i fix it someone help...

### ISSUE THREAD

**Issue by hx12x12** [Yimura/YimMenu#1643] opened 2023-07-07 16:16 UTC
### Describe the bug

AS SOON AS I JOIN A PUBLIC LPBBY WITH PLAYERS THIS STARTS HAPPENING
![Screenshot 2023-07-07 211424](https://github.com/YimMenu/YimMenu/assets/138899842/745b7358-1b80-4850-837a-23c13084cb38)

### Steps To Reproduce

AS SOON AS A PLAYER JOINS MY SECESSION OR I JOIN PUBLIC

### Expected Behavior

NEED HELP

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Rockstar

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by gir489returns** [comment] 2023-07-07 17:31
This is a duplicate of #1621.

**Comment by epicmusicpt** [comment] 2023-07-08 16:37
got it everytime i inject...

**Comment by Rxann** [comment] 2023-07-22 02:59
Well, It is not a duplicate anymore. This shows that the issue is still happening from the previous github issue.

**Comment by Yimura** [comment] 2023-07-27 17:01
Fixed

**Closed as completed by Yimura** 2023-07-27 17:01 UTC
Labels: bug
