### ISSUE TITLE
[Bug]: Other Menus can still crash Yimmenu

### ISSUE THREAD

**Issue by Ahmad23145** [Yimura/YimMenu#2895] opened 2024-03-30 16:47 UTC
### Describe the bug

A cheater tried to crash me multiple times and succeeded for him
(https://github.com/YimMenu/YimMenu/assets/165480150/5990b626-5383-4498-9e9f-41b67acd09a8)

### Steps To Reproduce

1. Inject Yimmenu 2. Go Online 3. Get crashed by other menus

### Expected Behavior

in order not to be crashed and that the protection of the menu improves

### Logs and/or screenshots

[cout.log](https://github.com/YimMenu/YimMenu/files/14812689/cout.log)

### Store

Epic Games

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment] 2024-03-30 17:11
This is a duplicate of #2842

**Closed as completed by gir489returns** 2024-03-30 17:11 UTC
Labels: bug
