### ISSUE TITLE
[Bug]: In First round of funding: garbage truck，Can‘t drive vehicle and rubbish truck

### ISSUE THREAD

**Issue by aierxiya** [Yimura/YimMenu#1556] opened 2023-06-29 04:54 UTC
### Describe the bug

Unable to drive your own vehicle and the operator's garbage truck during the Fundraising Round: Garbage Truck segment

### Steps To Reproduce

Unable to drive your own vehicle and the operator's garbage truck during the Fundraising Round: Garbage Truck segment

### Expected Behavior

Unable to drive your own vehicle and the operator's garbage truck during the Fundraising Round: Garbage Truck segment

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment] 2023-06-29 12:37
Most likely duplicate of #1540

**Closed as completed** 2023-07-05 07:30 UTC
Labels: bug
