### ISSUE TITLE
🛠️ [to improve Auto-Drive]

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#190] opened 2022-05-10 05:58 UTC
**Describe the bug**
On "Normal" mode, A-D doesn't hesitate to bump into traffic and some objects, even at low speeds.
On "Safe-ish" mode, this ↑ does not happen, but it still tries to overtake stopped cars at red lights / stop signs.

**To Reproduce**
Nothing else to say, so far.

**Expected behavior**

Suggestion:
###
	static constexpr int driving_styles[] = { 443, 524349 };
	static constexpr char const* driving_style_names[] = { "Law-Abiding", "The Road Is Yours" };

**Screenshots**
❌

**Logs**
❌

**Build**
Select which applies for you:
- [x] I used YimMenu unmodified
- [ ] I use my own version of YimMenu

**Additional context**
❌

**Comment by Yimura** [comment] 2022-05-10 06:11
No no, keep this one.

If this were a duplicate I would label it as so, please edit in your old contents as I'm unable to restore them (you hardcore deleted them).

**Comment by Yimura** [comment] 2022-05-10 06:21
You'll learn over time and you're doing a lot of stuff at once it's logical you're making more mistakes but please do take it slowly, as these features won't be implemented quickly either.

**Comment by xM4ddy** [comment] 2022-05-10 06:54
![Screenshot_20220510-024704](https://user-images.githubusercontent.com/59680197/167565489-0d3c801e-e081-43e6-8cd4-98176dc62681.jpg)
Pretty much functioning as intended. I made the feature but I asked the person who requested it what they wanted for the different styles and that's what they gave me. If you think the values should be different tell me what you believe they should be, the names, and why they should be changed to the new value. Here is the tool to make calculate the values https://vespura.com/fivem/drivingstyle/. The current values are 444 for Safe-ish, 525116 for Normal, and 787260 for Hit Everything. If your reasoning is sound I'll update the feature with your styles and new new names if you want to rename them.

**Comment by Yimura** [comment] 2022-05-10 06:57
Additionally native used (most likely, didn't look at the code): https://nativedb.spyral.dev/natives/0xE2A2AA2F659D77A7
~And for the driving modes (the values xM4ddy talked about): https://vespura.com/fivem/drivingstyle/~

~Just tell us the combination of driving modes you'd like us to implement, we'll have to figure out the values probably (unless you know how to calculate bitfields you may also give us the value directly).~

**Comment by LiamD-Flop** [comment] 2022-05-10 07:36
Some small thing on the auto drive. When you change settings you have to start auto drive again. This could be auto change when settings are changed?

**Comment by Yimura** [comment] 2022-09-25 00:47
Closing as Auto-Drive has had changes made to it and there have been no further comments on this issue.

**Closed as completed** 2022-09-25 00:48 UTC
Labels: bug
