### ISSUE TITLE
[Bug]: ContextMenu

### ISSUE THREAD

**Issue by vladdoser** [Yimura/YimMenu#640] opened 2022-11-25 23:25 UTC
### Describe the bug

Just broke game, cause i cant remove it.

### Steps To Reproduce

Press X on car, to open context menu and got stuck, cant close or remove menu, and see target entity(car) too far

### Expected Behavior

Open/Close

### Screenshots and/or Logs

https://imgur.com/j1aQmZr

### Store

Epic Games

### Build

- [X] I used YimMenu unmodified

**Comment by GeopJr** [comment] 2022-12-30 16:51
Does this still occur on latest YimMenu?

**Comment by vladdoser** [comment] 2022-12-30 17:37
In any of last ~10, if u try to apply any action to other user synced entities/vehs, or little spam actions

**Comment by Yimura** [comment] 2022-12-30 17:38
Have you tried using the latest version of YimMenu, it's likely the issues have been fixed.

**Comment by vladdoser** [comment] 2022-12-30 17:47
Tested rn, sometimes its repeat, now - more rarely, but unfreezing when user leave render zone or smt like that
![image](https://user-images.githubusercontent.com/49642466/210098567-eebeeeeb-dab6-4ec5-92db-2bacff73aba7.png)
![image](https://user-images.githubusercontent.com/49642466/210098873-1fa362b3-5eae-4135-9b0d-41978e1a622a.png)

**Comment by Yimura** [comment] 2023-02-05 12:02
This issue is a duplicate of #655.

Closing as this should have been fixed.

**Closed as completed by Yimura** 2023-02-05 12:02 UTC
Labels: bug
