### ISSUE TITLE
[Bug]: Have problem with injecting

### ISSUE THREAD

**Issue by KoreanETS2** [Yimura/YimMenu#2755] opened 2024-02-22 13:53 UTC
### Describe the bug

while injecting yimmenu, gta5 crashes(using extreme injector)

### Steps To Reproduce

1. open the injector 2. inject yimmenu 3. and it happens

### Expected Behavior

not good at english sorry i don't know what it means

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Rockstar

### Language

Korean

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment] 2024-02-22 13:58
No log posted, but due to the user's name and selected language, I fear this is a duplicate of #2753.

**Comment by hamzacherniy** [comment] 2024-02-22 17:20
I have the same problem, it crashes when injecting, did you solve the problem?

**Comment by Yimura** [comment] 2024-02-22 17:22
> I have the same problem, it crashes when injecting, did you solve the problem?

Try to see if the DLL from this PR fixes the issue #2756.

**Comment by Yimura** [comment] 2024-03-21 21:28
No response from issue author.

**Closed as completed by Yimura** 2024-03-21 21:28 UTC
Labels: bug
