### ISSUE TITLE
[Request]: Menu Identifier

### ISSUE THREAD

**Issue by 0xEmiil** [Yimura/YimMenu#1127] opened 2023-03-20 22:16 UTC
### Problem

This could help a lot and even could help at the time of make friends with Yim

### Solution

Im From old modding idk if this ideas are working on PC
Armoured ID: This could set with a Native
Decoration ID: This is also set with a Native, Idk if its working but using dec natives we can set our own 
proper name, and type
PeerPlayerTokenID:  I think YimClasses already dump something similar to this
If someone have a better way to do feel free to leave :)

### Reason

I think it would be cool if the menu have an ID to recognize other users and maybe we could set a no troll options if the user is using yim

### Additional context

Only bad thing its that other menus could try to detect yim :(

**Comment by Yimura** [comment] 2023-03-20 22:24
Duplicate of #727

**Closed as completed by Yimura** 2023-03-20 22:24 UTC
Labels: request
