### ISSUE TITLE
[Bug]: YimMenu crashing on injection

### ISSUE THREAD

**Issue by CentricGamer834** [Yimura/YimMenu#2948] opened 2024-04-17 13:13 UTC
### Describe the bug

YimMenu is crashing the game on injection.

Windows 11
I've tried using Xenos Injector, and Fate Injector. I've also deleted YimMenu folder in AppData

### Steps To Reproduce

Inject YimMenu.dll

### Expected Behavior

Work

### Logs and/or screenshots

[Link to log](https://pastebin.com/mZ0s767i)

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've tested this without co-loading anything.
- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by gir489returns** [comment] 2024-04-17 13:15
Duplicate of #2945

**Closed as completed by gir489returns** 2024-04-17 13:15 UTC
Labels: bug

**Comment by Yimura** [comment] 2024-04-17 13:23
Me when I forgot to check if there are other people having the same issue before creating an issue myself.
