### ISSUE TITLE
[Bug]: Aimbot is not working

### ISSUE THREAD

**Issue by raviyaaas** [Yimura/YimMenu#1076] opened 2023-03-12 15:11 UTC
### Describe the bug

aim bot is not working.I tried several times

### Steps To Reproduce

1Aimbot

### Expected Behavior

If you can fix it sir. please

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment] 2023-03-12 17:02
Duplicate of #1066

**Closed as completed by Yimura** 2023-03-12 17:02 UTC
Labels: bug
