### ISSUE TITLE
[Bug]: Odd lil Exception On Inject

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#2510] opened 2023-12-12 00:45 UTC
### Describe the bug

This appears on inject after Dynamic native hooker is initialized.

### Steps To Reproduce

1. Inject
2. Wait for load
3. Exception but loads

### Expected Behavior

No Error nor Exceptions whatsoever tbh

### Logs and/or screenshots

[FATAL/exception_handler.cpp:42] EXCEPTION_ACCESS_VIOLATION
Dumping modules:
GTA5.exe Base Address: 0x7FF72F780000 Size: 66857984
ntdll.dll Base Address: 0x7FF8827B0000 Size: 1249280
KERNEL32.DLL Base Address: 0x7FF880830000 Size: 528384
KERNELBASE.dll Base Address: 0x7FF87FE00000 Size: 1638400
USER32.dll Base Address: 0x7FF8819A0000 Size: 610304
win32u.dll Base Address: 0x7FF87FC90000 Size: 49152
GDI32.dll Base Address: 0x7FF881970000 Size: 57344
gdi32full.dll Base Address: 0x7FF8802C0000 Size: 675840
msvcp_win.dll Base Address: 0x7FF880220000 Size: 335872
ucrtbase.dll Base Address: 0x7FF8803E0000 Size: 798720
PSAPI.DLL Base Address: 0x7FF880D20000 Size: 4096
WS2_32.dll Base Address: 0x7FF880C40000 Size: 290816
VERSION.dll Base Address: 0x7FF8775C0000 Size: 12288
RPCRT4.dll Base Address: 0x7FF881BB0000 Size: 880640
msvcrt.dll Base Address: 0x7FF880EA0000 Size: 507904
CRYPT32.dll Base Address: 0x7FF87FB20000 Size: 1134592
WINTRUST.dll Base Address: 0x7FF8801B0000 Size: 307200
IMM32.dll Base Address: 0x7FF880B00000 Size: 126976
SHLWAPI.dll Base Address: 0x7FF880AA0000 Size: 212992
ADVAPI32.dll Base Address: 0x7FF8817B0000 Size: 434176
sechost.dll Base Address: 0x7FF881D50000 Size: 446464
SHELL32.dll Base Address: 0x7FF880F50000 Size: 6848512
ole32.dll Base Address: 0x7FF880900000 Size: 909312
combase.dll Base Address: 0x7FF881EB0000 Size: 2539520
OLEAUT32.dll Base Address: 0x7FF880520000 Size: 647168
WININET.dll Base Address: 0x7FF854A30000 Size: 2113536
WINMM.dll Base Address: 0x7FF8782B0000 Size: 114688
MF.dll Base Address: 0x7FF8793D0000 Size: 372736
shcore.dll Base Address: 0x7FF881870000 Size: 684032
MFPlat.DLL Base Address: 0x7FF8787C0000 Size: 1503232
msdmo.dll Base Address: 0x7FF84F530000 Size: 16384
MFReadWrite.dll Base Address: 0x7FF816570000 Size: 995328
PROPSYS.dll Base Address: 0x7FF87AC40000 Size: 692224
WTSAPI32.dll Base Address: 0x7FF87E9C0000 Size: 40960
d3d9.dll Base Address: 0x7FF857400000 Size: 1306624
DSOUND.dll Base Address: 0x7FF870D30000 Size: 491520
D3DCOMPILER_43.dll Base Address: 0x7FF82FDE0000 Size: 2423296
DINPUT8.dll Base Address: 0x7FF83E2C0000 Size: 176128
XINPUT1_3.dll Base Address: 0x400000 Size: 85504
SETUPAPI.dll Base Address: 0x7FF8822F0000 Size: 913408
bcrypt.dll Base Address: 0x7FF87F4B0000 Size: 110592
IPHLPAPI.DLL Base Address: 0x7FF87E660000 Size: 122880
cfgmgr32.dll Base Address: 0x7FF87F810000 Size: 221184
dwmapi.dll Base Address: 0x7FF87D180000 Size: 90112
ResampleDmo.DLL Base Address: 0x7FF858C50000 Size: 503808
powrprof.dll Base Address: 0x7FF87E970000 Size: 77824
winmmbase.dll Base Address: 0x7FF83E310000 Size: 102400
dxcore.dll Base Address: 0x7FF87CE50000 Size: 131072
GFSDK_ShadowLib.win64.dll Base Address: 0x7FF829E30000 Size: 96256
d3dx9_43.dll Base Address: 0x7FF82F7D0000 Size: 2280960
bink2w64.dll Base Address: 0x7FF836670000 Size: 307712
GFSDK_TXAA_AlphaResolve.win64.dll Base Address: 0x7FF83DB70000 Size: 48128
OPENGL32.dll Base Address: 0x7FF825E80000 Size: 798720
MFCORE.DLL Base Address: 0x7FF878E50000 Size: 3026944
GLU32.dll Base Address: 0x7FF832B40000 Size: 126976
UMPDC.dll Base Address: 0x7FF87E950000 Size: 36864
kernel.appcore.dll Base Address: 0x7FF87EC10000 Size: 36864
bcryptPrimitives.dll Base Address: 0x7FF87FD80000 Size: 376832
RTWorkQ.DLL Base Address: 0x7FF878DB0000 Size: 102400
MSASN1.dll Base Address: 0x7FF87F7C0000 Size: 36864
gameoverlayrenderer64.dll Base Address: 0x7FF837B50000 Size: 996864
inputhost.dll Base Address: 0x7FF859190000 Size: 1540096
CoreMessaging.dll Base Address: 0x7FF87C8A0000 Size: 860160
CRYPTBASE.DLL Base Address: 0x7FF87F300000 Size: 12288
sdk_legacy_led_x64.dll Base Address: 0x7FF828230000 Size: 2594816
VCRUNTIME140.dll Base Address: 0x7FF86F5E0000 Size: 73728
MSVCP140.dll Base Address: 0x7FF86F4C0000 Size: 340480
VCRUNTIME140_1.dll Base Address: 0x7FF86F620000 Size: 15360
ZLIB1.dll Base Address: 0x7FF83AEF0000 Size: 54784
CRYPTSP.dll Base Address: 0x7FF87F2E0000 Size: 57344
rsaenh.dll Base Address: 0x7FF87EB70000 Size: 147456
mswsock.dll Base Address: 0x7FF87F090000 Size: 331776
windows.storage.dll Base Address: 0x7FF87DA40000 Size: 7032832
wintypes.dll Base Address: 0x7FF87D900000 Size: 544768
dbghelp.dll Base Address: 0x7FF87D540000 Size: 1646592
dbgcore.DLL Base Address: 0x7FF8590B0000 Size: 131072
uxtheme.dll Base Address: 0x7FF87CD50000 Size: 425984
clbcatq.dll Base Address: 0x7FF881E00000 Size: 471040
amsi.dll Base Address: 0x7FF86C3F0000 Size: 57344
USERENV.dll Base Address: 0x7FF87F180000 Size: 102400
profapi.dll Base Address: 0x7FF87FA50000 Size: 90112
MpOav.dll Base Address: 0x7FF86C370000 Size: 204800
imagehlp.dll Base Address: 0x7FF8822D0000 Size: 49152
gpapi.dll Base Address: 0x7FF87F120000 Size: 77824
cryptnet.dll Base Address: 0x7FF877470000 Size: 139264
WINNSI.DLL Base Address: 0x7FF87CD00000 Size: 16384
NSI.dll Base Address: 0x7FF880D30000 Size: 8192
steam_api64.dll Base Address: 0x6C4E0000 Size: 110592
steamclient64.dll Base Address: 0x7FF81AF80000 Size: 16284672
vstdlib_s64.dll Base Address: 0x7FF83A4C0000 Size: 285184
tier0_s64.dll Base Address: 0x7FF836CA0000 Size: 259584
Secur32.dll Base Address: 0x7FF87E9F0000 Size: 12288
SSPICLI.DLL Base Address: 0x7FF87EE70000 Size: 126976
drvstore.dll Base Address: 0x7FF877200000 Size: 1044480
devobj.dll Base Address: 0x7FF87F7E0000 Size: 110592
wldp.dll Base Address: 0x7FF87F390000 Size: 188416
nvspcap64.dll Base Address: 0x7FF811FB0000 Size: 2056192
ntmarta.dll Base Address: 0x7FF87EC30000 Size: 147456
dhcpcsvc.DLL Base Address: 0x7FF8784E0000 Size: 69632
D3D11.DLL Base Address: 0x7FF87B9E0000 Size: 1867776
dxgi.dll Base Address: 0x7FF87CE90000 Size: 651264
directxdatabasehelper.dll Base Address: 0x7FF865FD0000 Size: 196608
nvapi64.dll Base Address: 0x7FF8739E0000 Size: 6290432
D3D10_1.DLL Base Address: 0x7FF8365F0000 Size: 147456
d3d10_1core.dll Base Address: 0x7FF84F830000 Size: 12288
MSCTF.dll Base Address: 0x7FF880D50000 Size: 1073152
textinputframework.dll Base Address: 0x7FF86DE80000 Size: 1015808
Oleacc.dll Base Address: 0x7FF8730C0000 Size: 274432
WINSTA.dll Base Address: 0x7FF87E5B0000 Size: 229376
nvldumdx.dll Base Address: 0x7FF8731C0000 Size: 591872
nvgpucomp64.dll Base Address: 0x7FF860030000 Size: 29061632
nvwgf2umx.dll Base Address: 0x7FF85ABA0000 Size: 38347264
NvCamera64.dll Base Address: 0x7FFFE4B70000 Size: 4240896
HID.DLL Base Address: 0x7FF87E340000 Size: 24576
WindowsCodecs.dll Base Address: 0x7FF87B5B0000 Size: 1331200
XINPUT9_1_0.dll Base Address: 0x7FF871620000 Size: 8192
MessageBus.dll Base Address: 0x7FF8732A0000 Size: 5349888
d3dcompiler_47_64.dll Base Address: 0x7FF819DA0000 Size: 3922944
nvcuda64.dll Base Address: 0x7FFFE41C0000 Size: 5758976
MMDevApi.dll Base Address: 0x7FF8760E0000 Size: 462848
XAudio2_7.dll Base Address: 0x7FF835310000 Size: 485376
AUDIOSES.DLL Base Address: 0x7FF849CE0000 Size: 1409024
resourcepolicyclient.dll Base Address: 0x7FF87D200000 Size: 36864
Windows.UI.dll Base Address: 0x7FF8653D0000 Size: 966656
avrt.dll Base Address: 0x7FF87A4F0000 Size: 8192
MessageBus.dll Base Address: 0x7FF869F40000 Size: 5349888
napinsp.dll Base Address: 0x7FF84F540000 Size: 53248
pnrpnsp.dll Base Address: 0x7FF84C940000 Size: 69632
DNSAPI.dll Base Address: 0x7FF87E690000 Size: 737280
winrnr.dll Base Address: 0x7FF84C920000 Size: 32768
wshbth.dll Base Address: 0x7FF8780C0000 Size: 45056
nlansp_c.dll Base Address: 0x7FF84C8F0000 Size: 81920
fwpuclnt.dll Base Address: 0x7FF8779F0000 Size: 294912
rasadhlp.dll Base Address: 0x7FF877FF0000 Size: 8192
DPAPI.dll Base Address: 0x7FF87F880000 Size: 8192
socialclub.dll Base Address: 0x7FF82BC60000 Size: 5133824
chrome_elf.dll Base Address: 0x7FF838580000 Size: 676864
libcef.dll Base Address: 0x7FFFBEE60000 Size: 109744128
COMDLG32.dll Base Address: 0x7FF880B40000 Size: 778240
NETAPI32.dll Base Address: 0x7FF869F20000 Size: 49152
COMCTL32.dll Base Address: 0x7FF8579D0000 Size: 573440
DWrite.dll Base Address: 0x7FF87B760000 Size: 1650688
WINSPOOL.DRV Base Address: 0x7FF86E4C0000 Size: 405504
USP10.dll Base Address: 0x7FF838440000 Size: 4096
dxva2.dll Base Address: 0x7FF838410000 Size: 102400
credui.dll Base Address: 0x7FF8383F0000 Size: 65536
urlmon.dll Base Address: 0x7FF86EDC0000 Size: 1298432
WINHTTP.dll Base Address: 0x7FF878660000 Size: 987136
ncrypt.dll Base Address: 0x7FF87F480000 Size: 114688
CRYPTUI.dll Base Address: 0x7FF867730000 Size: 278528
ESENT.dll Base Address: 0x7FF867040000 Size: 3145728
wevtapi.dll Base Address: 0x7FF87AA20000 Size: 282624
UIAutomationCore.DLL Base Address: 0x7FF846930000 Size: 3063808
srvcli.dll Base Address: 0x7FF86E5B0000 Size: 57344
iertutil.dll Base Address: 0x7FF86E780000 Size: 557056
netutils.dll Base Address: 0x7FF87E5A0000 Size: 20480
WKSCLI.DLL Base Address: 0x7FF877FD0000 Size: 49152
SAMCLI.DLL Base Address: 0x7FF87A8E0000 Size: 61440
NTASN1.dll Base Address: 0x7FF87F440000 Size: 69632
FirewallAPI.dll Base Address: 0x7FF87E4B0000 Size: 385024
fwbase.dll Base Address: 0x7FF87E430000 Size: 208896
FWPolicyIOMgr.dll Base Address: 0x7FF86FBA0000 Size: 245760
wdmaud.drv Base Address: 0x7FF8314C0000 Size: 200704
ksuser.dll Base Address: 0x7FF872CD0000 Size: 8192
msacm32.drv Base Address: 0x7FF850B10000 Size: 20480
MSACM32.dll Base Address: 0x7FF848A00000 Size: 77824
midimap.dll Base Address: 0x7FF84F410000 Size: 16384
ondemandconnroutehelper.dll Base Address: 0x7FF849F10000 Size: 45056
dhcpcsvc6.DLL Base Address: 0x7FF878500000 Size: 28672
YimMenu.dll Base Address: 0x7FFFE3640000 Size: 9082880
D3DCOMPILER_47.dll Base Address: 0x7FF87B1C0000 Size: 3043328
xinput1_4.dll Base Address: 0x7FF847430000 Size: 32768
schannel.DLL Base Address: 0x7FF87EA60000 Size: 561152
ncryptsslp.dll Base Address: 0x7FF86D3D0000 Size: 86016
Dumping registers:
RAX: 0x4360
RCX: 0x6
RDX: 0x86C
RBX: 0xB
RSI: 0x1B8801E35F0
RDI: 0x1B8CC2187B0
RSP: 0x947412E6C0
RBP: 0x1B8801E3760
R8:  0x0
R9:  0x1B8CC2187B0
R10: 0x0
R11: 0x1B8CC237480
R12: 0x1B8801E35F0
R13: 0x1B81DF22008
R14: 0x7FFFE3779BD0
R15: 0x0
Dumping stacktrace:
[0]     YimMenu.dll+0x141C1A 0x7FFFE3781C1A
[1]     YimMenu.dll+0x1417DC 0x7FFFE37817DC
[2]     YimMenu.dll+0x11C9DB 0x7FFFE375C9DB
[3]     YimMenu.dll+0x7F7A6E 0x7FFFE3E37A6E
[4]     YimMenu.dll+0x7F6AEE 0x7FFFE3E36AEE
[5]     YimMenu.dll+0x810EBE 0x7FFFE3E50EBE
[6]     YimMenu.dll+0x7F6302 0x7FFFE3E36302
[7]     YimMenu.dll+0x7F7073 0x7FFFE3E37073
[8]     YimMenu.dll+0x7F68E0 0x7FFFE3E368E0
[9]     YimMenu.dll+0x7F1CED 0x7FFFE3E31CED
[10]    YimMenu.dll+0xF6D82 0x7FFFE3736D82
[11]    YimMenu.dll+0x2A90E7 0x7FFFE38E90E7
[12]    YimMenu.dll+0x2AA5B0 0x7FFFE38EA5B0
[13]    YimMenu.dll+0x1DF8E9 0x7FFFE381F8E9
[14]    YimMenu.dll+0x1DF25F 0x7FFFE381F25F
[15]    YimMenu.dll+0x1DD789 0x7FFFE381D789
[16]    YimMenu.dll+0x606AF4 0x7FFFE3C46AF4
[17]    YimMenu.dll+0x608483 0x7FFFE3C48483
[18]    YimMenu.dll+0x6062D1 0x7FFFE3C462D1
[19]    KERNEL32.DLL BaseThreadInitThunk
[20]    ntdll.dll RtlUserThreadStart
--------End of exception--------

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Additional context

is this fixable?

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment] 2023-12-12 00:47
Without a build number or hash from the full log, this is worthless.

**Comment by pierrelasse** [comment] 2023-12-12 10:07
> Without a build number or hash from the full log, this is worthless.

"[x] I've confirmed the issue exists on the latest version of YimMenu"

#

I was able to repro the same error while not being fully loaded into storymode.

**Comment by gir489returns** [comment] 2023-12-13 23:07
We don't support SP at all, and nothing I said that you said invalidated that.

**Comment by Yimura** [comment] 2023-12-13 23:10
Well we support single player somewhat but we're not actively trying to develop it for single player to be fair.

**Comment by pierrelasse** [comment] 2023-12-14 09:02
I rather think that fixing this is not adding more or less support for sp.
I think that to fix it, you would just have to wait for sp to be loaded (like in the rebuild cache), before further initialization.

**Comment by lonelybud** [comment] 2023-12-14 09:07
i think dev cannot help here if you dont provide more information like -

full details like exact timing of injection and whether it is fresh installation of menu etc
full log file
injector used (with the settings)

**Comment by pierrelasse** [comment] 2023-12-14 09:10
I can confirm that it worked on the latest 1-2 days ago.
Im not on pc rn but you can just try injecting too early.
The stacktrace will be almost exact to this one.

**Comment by roadsport** [comment] 2024-02-20 17:32
Having the same exception, 
-latest YimMenu build
-worked just fine before

**Comment by Yimura** [comment] 2024-02-20 17:34
> Having the same exception, -latest YimMenu build -worked just fine before

Your issue is relevant to #2726 for which a fix has been merged into master, a new build under releases should be available in ~10min.

**Comment by Deadlineem** [comment] 2024-02-20 17:48
> > Having the same exception, -latest YimMenu build -worked just fine before
> 
> Your issue is relevant to #2726 for which a fix has been merged into master, a new build under releases should be available in ~10min.

after this fix (i compiled my own with the pd fix) it works but has access violations idky could be related?

**Comment by Deadlineem** [comment] 2024-02-20 17:49
[cout.log](https://github.com/YimMenu/YimMenu/files/14349334/cout.log)
@Yimura @gir489returns current cout.log from last 10 minutes

**Comment by Yimura** [comment] 2024-02-20 17:52
> after this fix (i compiled my own with the pd fix) it works but has access violations idky could be related?

I doubt the issue is related, unless everything that comes after the text `EXCEPTION_ACCESS_VIOLATION` is exactly the same between your log file and what is in this issue.
Usually if there isn't much traction in these issue we close them after some inactivity if the root cause can not be found.
So please verify if the contents of the crash are exactly the same then yes this is right place to report you've got the exact issue, otherwise just make a new issue.

We've had instances of just random people starting to report unrelated EXCEPTION_ACCESS_VIOLATION in other issue and we just couldn't keep track anymore of what we had fixed and what we didn't.

**Comment by Yimura** [comment] 2024-02-20 17:53
@Deadlineem, from the looks of it your crash is unrelated to this issue and you should make a new one.

**Comment by Deadlineem** [comment] 2024-02-20 17:54
> @Deadlineem, from the looks of it your crash is unrelated to this issue and you should make a new one.

10-4 will make a new issue

**Comment by Yimura** [comment] 2024-02-21 21:53
Dated issue, if the issue persists consider opening a new one.

**Closed as completed by Yimura** 2024-02-21 21:53 UTC
Labels: bug
