### ISSUE TITLE
[Bug]: Context menu does nothing but crash the game

### ISSUE THREAD

**Issue by ghost** [Yimura/YimMenu#750] opened 2022-12-25 04:00 UTC
### Describe the bug

Context menu instantly crashes the game

### Steps To Reproduce

1. Enable context menu
2. Press X
3. Goodbye

### Expected Behavior

Watchdogs hackerman!

### Screenshots and/or Logs

[cout.txt](https://github.com/YimMenu/YimMenu/files/10299414/cout.txt)

### Store

Steam

### Additional context

Used latest nightly build as of 12/24

Please remove this feature from the menu

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment] 2022-12-25 10:03
Duplicate of #699

**Closed as completed by Yimura** 2022-12-25 10:03 UTC
Labels: bug
