### ISSUE TITLE
[Bug]: Game Randomly Freezing

### ISSUE THREAD

**Issue by xenical1212** [Yimura/YimMenu#1165] opened 2023-03-31 21:58 UTC
### Describe the bug

When i play gta o it will randomly freeze with this menu injected but if i play without the menu the game doesnt randomly freeze.

### Steps To Reproduce

just inject the menu and play gta for a bit

### Expected Behavior

no freezing

### Store

Steam

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by rrAsus** [comment] 2023-03-31 23:38
after how many hours does it appear?

**Comment by xenical1212** [comment] 2023-04-01 03:32
i dont really check the time but probably 1 or 2 hours

**Comment by Yimura** [comment] 2023-04-01 13:49
Duplicate of #1073

**Closed as completed by Yimura** 2023-04-01 13:49 UTC
Labels: bug
