### ISSUE TITLE
[Request]: protection against stand remote crash

### ISSUE THREAD

**Issue by PromSkid** [Yimura/YimMenu#774] opened 2022-12-29 22:16 UTC
### Problem

stand now has a remote crash which makes the game even more unplayable.

### Solution

make a protection for this or just uninstall gta at this point

### Reason

stand has a remote crash feature that is broken af and makes the game unplayable

**Comment by Yimura** [comment] 2022-12-29 22:20
Duplicate of #773

**Closed as completed** 2022-12-29 23:51 UTC
Labels: request
