### ISSUE TITLE
[Bug]: Hotkeys

### ISSUE THREAD

**Issue by YumoYo** [Yimura/YimMenu#3197] opened 2024-05-28 21:06 UTC
### Describe the bug

when i bind anything in hotkeys with my mouse side buttons ( VK_XBUTTON2 or VK_XBUTTON1 ) they wont work like when i set it to no clip it doesnt get enabled

### Steps To Reproduce

hotkeys
bind to mouse side buttons

### Expected Behavior

Not working?

### Logs

.

### Screenshots / Video

![image](https://github.com/YimMenu/YimMenu/assets/121263528/67bf33b4-166f-4c80-a822-b69b5a3c1567)

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by xiaoxiao921** [comment] 2024-08-02 14:15
Duplicate of #3436

**Closed as completed by xiaoxiao921** 2024-08-02 14:15 UTC
Labels: bug
