### ISSUE TITLE
[Bug]: Players in same session cant join heist room

### ISSUE THREAD

**Issue by epicmusicpt** [Yimura/YimMenu#1074] opened 2023-03-12 02:16 UTC
### Describe the bug

any player friend or not who are in the same session as me cant join my heist room (casino/apartment) they get stuck when joining after invite. only players from diferent session are able to join.

### Steps To Reproduce

go to arcade/apartment ,create heist room (only tested casino and apartment),invite friends/other players in the same session. they stuck when try to join room. 

### Expected Behavior

players/friends in same session should be able to join.

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Rockstar

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment] 2023-03-14 10:51
Duplicate of #1015

**Closed as completed by Yimura** 2023-03-14 10:51 UTC
Labels: bug
