### ISSUE TITLE
[Bug]: player car bugged

### ISSUE THREAD

**Issue by CamioneroTrap** [Yimura/YimMenu#1548] opened 2023-06-27 18:54 UTC
### Describe the bug

when I get into a player's car I see the car standing still, but in reality the car is moving

### Steps To Reproduce

1. get in the car as co-pilot with player 
2. get out of the car and see that it's somewhere else

### Expected Behavior

get into the car and see how the car moves

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Rockstar

### Additional context

sorry if you can't understand, I use a translator

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment] 2023-06-27 18:59
Duplicate of #1540

**Closed as completed by Yimura** 2023-06-27 18:59 UTC
Labels: bug
