### ISSUE TITLE
[Request]: Add player animations/scnarios

### ISSUE THREAD

**Issue by BUZZARDGTA** [Yimura/YimMenu#1035] opened 2023-03-01 14:45 UTC
### Problem

It would be great if someone add animations and scenarios into the menu.

### Solution

.

### Reason

.

### Additional context

Thanks for making this free and open source menu, it's really great and I enjoy a lot playing with it!

**Comment by Yimura** [comment] 2023-03-01 14:53
Duplicate of #187

**Closed as completed** 2023-03-01 14:58 UTC
Labels: request
