### ISSUE TITLE
[Bug]: Custom weapons

### ISSUE THREAD

**Issue by epicmusicpt** [Yimura/YimMenu#1067] opened 2023-03-11 13:29 UTC
### Describe the bug

Custom weapons dont work (only vehicle weapon does)

### Steps To Reproduce

toogle custom weapons, choose like Cage gun , Gravity gun , Delete gun etc...only vehicle weapon works.

### Expected Behavior

Custom weapons should work.

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Rockstar

### Additional context

Tryed on story mode and online
### Build

- [x] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Rxann** [comment] 2023-03-11 19:33
I also experience this problem

**Comment by Yimura** [comment] 2023-03-12 17:09
There are possibly issues with the `entity::take_control_of` function.

It's probably returning false causing those custom weapons to not work as intended.

**Comment by Yimura** [comment] 2023-04-12 18:11
Fixed with #1226

**Closed as completed by Yimura** 2023-04-12 18:11 UTC
Labels: bug
