### ISSUE TITLE
[Bug]: crash when trying to join the online mode

### ISSUE THREAD

**Issue by CamioneroTrap** [Yimura/YimMenu#1511] opened 2023-06-23 11:42 UTC
### Describe the bug

With the new version of the dll the game closes when I try to join a public session with no error message

### Steps To Reproduce

1. Go to story mode gta 5
2. inject the dll with xenos
3. join gta online

### Expected Behavior

I expect the game does not close

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Rockstar

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

**Comment by Yimura** [comment] 2023-06-23 11:45
Hey there, I also noticed some odd things but didn't crash but just to verify if this is the same.

Could you do the following:
1. Open `%appdata%/BigBaseV2/cache` in explorer
2. Remove all the files in this folder
3. Launch GTAV
4. Inject YimMenu

After doing that could you come back here to confirm on if it worked?

**Comment by xiaoxiao921** [comment] 2023-06-23 11:49
This is most likely due to the added ptr but unchanged cache hash

**Comment by CamioneroTrap** [comment] 2023-06-23 11:50
seems to have worked, thank you very much

**Comment by xiaoxiao921** [comment] 2023-06-23 11:52
thanks for the report, let this issue open, we'll close it when we fix the root issue, we found the root cause

**Comment by Yimura** [comment] 2023-06-23 11:52
Related to #1509

**Closed as completed** 2023-06-23 12:56 UTC
Labels: bug
